import ProCGroups.FreeProC.Criteria.InverseLimitsAndFiniteSubsets

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/ProCGroups/FreeProC/FinitelyGenerated.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Finitely generated free pro-C groups

This file adds a finite-rank interface on top of the general free pro-`C` API.  A finite basis
does not need the full converging-family bookkeeping at every use site: convergence to `1` is
automatic, and for concrete finite-group classes the generated-target hypothesis can be discharged
by corestricting to the closed subgroup generated by the image.

For infinite bases, the file also packages the existing finite-subset inverse-limit construction
as a reusable structure.
-/

open scoped Topology

namespace ProCGroups.FreeProC

universe u v w

namespace IsFreeProCGroupOnConvergingSet

/-- For a finite basis and a concrete finite-group class, every target map has a unique
continuous lift.  This is the finite-rank replacement for repeatedly supplying the automatic
`FamilyConvergesToOne` proof by hand. -/
theorem existsUnique_liftHom_of_finite
    (C : ProCGroups.FiniteGroupClass.{u})
    [hVar : Fact (ProCGroups.FiniteGroupClass.Variety C)]
    [hIso : Fact (ProCGroups.FiniteGroupClass.IsomClosed C)]
    {X : Type v} [Finite X]
    {F : Type u} [Group F] [TopologicalSpace F] [IsTopologicalGroup F]
    {ι : X → F}
    (hι :
      IsFreeProCGroupOnConvergingSet
        (ProC := ProCGroups.ProC.finiteGroupClassProCPredicate C) X F ι)
    {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    (hG : (ProCGroups.ProC.finiteGroupClassProCPredicate C) (G := G))
    (φ : X → G) :
    ∃! f : F →ₜ* G, ∀ x, f (ι x) = φ x := by
  exact
    hι.existsUnique_liftHom_of_convergesToOne_of_finiteGroupClass
      C hIso.out hVar.out.subgroupClosed hVar.out.quotientClosed
      hG φ (FamilyConvergesToOne.of_finite_domain (G := G) φ)

/-- The finite-rank lift of a map from the basis into a concrete finite-class pro-`C` target. -/
noncomputable def liftHomOfFinite
    (C : ProCGroups.FiniteGroupClass.{u})
    [Fact (ProCGroups.FiniteGroupClass.Variety C)]
    [Fact (ProCGroups.FiniteGroupClass.IsomClosed C)]
    {X : Type v} [Finite X]
    {F : Type u} [Group F] [TopologicalSpace F] [IsTopologicalGroup F]
    {ι : X → F}
    (hι :
      IsFreeProCGroupOnConvergingSet
        (ProC := ProCGroups.ProC.finiteGroupClassProCPredicate C) X F ι)
    {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    (hG : (ProCGroups.ProC.finiteGroupClassProCPredicate C) (G := G))
    (φ : X → G) :
    F →ₜ* G :=
  Classical.choose
    (ExistsUnique.exists
      (hι.existsUnique_liftHom_of_finite C hG φ))

/-- The finite-rank lift has the prescribed value on each basis element. -/
@[simp] theorem liftHomOfFinite_apply
    (C : ProCGroups.FiniteGroupClass.{u})
    [Fact (ProCGroups.FiniteGroupClass.Variety C)]
    [Fact (ProCGroups.FiniteGroupClass.IsomClosed C)]
    {X : Type v} [Finite X]
    {F : Type u} [Group F] [TopologicalSpace F] [IsTopologicalGroup F]
    {ι : X → F}
    (hι :
      IsFreeProCGroupOnConvergingSet
        (ProC := ProCGroups.ProC.finiteGroupClassProCPredicate C) X F ι)
    {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    (hG : (ProCGroups.ProC.finiteGroupClassProCPredicate C) (G := G))
    (φ : X → G) (x : X) :
    hι.liftHomOfFinite C hG φ (ι x) = φ x :=
  Classical.choose_spec
    (ExistsUnique.exists
      (hι.existsUnique_liftHom_of_finite C hG φ)) x

/-- The finite-rank lift is unique among continuous homomorphisms with the prescribed basis
values. -/
theorem liftHomOfFinite_unique
    (C : ProCGroups.FiniteGroupClass.{u})
    [Fact (ProCGroups.FiniteGroupClass.Variety C)]
    [Fact (ProCGroups.FiniteGroupClass.IsomClosed C)]
    {X : Type v} [Finite X]
    {F : Type u} [Group F] [TopologicalSpace F] [IsTopologicalGroup F]
    {ι : X → F}
    (hι :
      IsFreeProCGroupOnConvergingSet
        (ProC := ProCGroups.ProC.finiteGroupClassProCPredicate C) X F ι)
    {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    (hG : (ProCGroups.ProC.finiteGroupClassProCPredicate C) (G := G))
    (φ : X → G)
    {f : F →ₜ* G} (hf : ∀ x, f (ι x) = φ x) :
    f = hι.liftHomOfFinite C hG φ := by
  rcases hι.existsUnique_liftHom_of_finite C hG φ with
    ⟨g, _hg, huniq⟩
  have hchosen :
      hι.liftHomOfFinite C hG φ = g := by
    apply huniq
    intro x
    exact hι.liftHomOfFinite_apply C hG φ x
  exact (huniq f hf).trans hchosen.symm

/-- A finite discrete converging-set basis gives the usual free pro-`C` universal property for a
concrete finite-group class. -/
theorem isFreeProCGroup_of_finite
    (C : ProCGroups.FiniteGroupClass.{u})
    [hVar : Fact (ProCGroups.FiniteGroupClass.Variety C)]
    [hIso : Fact (ProCGroups.FiniteGroupClass.IsomClosed C)]
    {X : Type u} [TopologicalSpace X] [DiscreteTopology X] [Finite X]
    {F : Type u} [Group F] [TopologicalSpace F] [IsTopologicalGroup F]
    {ι : X → F}
    (hι :
      IsFreeProCGroupOnConvergingSet
        (ProC := ProCGroups.ProC.finiteGroupClassProCPredicate C) X F ι) :
    IsFreeProCGroup (ProC := ProCGroups.ProC.finiteGroupClassProCPredicate C) ι := by
  refine
    { isProC := hι.isProC
      continuous_ι := continuous_of_discreteTopology
      generates_range := hι.generates_range
      existsUnique_lift := ?_ }
  intro G _ _ _ hG φ _hφ
  rcases hι.existsUnique_liftHom_of_finite C hG φ with
    ⟨f, hf, huniq⟩
  refine ⟨f.toMonoidHom, ⟨f.continuous, hf⟩, ?_⟩
  intro g hg
  let gc : F →ₜ* G := { toMonoidHom := g, continuous_toFun := hg.1 }
  exact congrArg ContinuousMonoidHom.toMonoidHom (huniq gc hg.2)

end IsFreeProCGroupOnConvergingSet

/-- A free pro-`C` group with an explicit finite basis `Fin n`. -/
structure FiniteRankData
    (ProC : ProCGroups.ProC.ProCGroupPredicate.{u}) (n : ℕ) where
  carrier : Type u
  instGroup : Group carrier
  instTopologicalSpace : TopologicalSpace carrier
  instIsTopologicalGroup : IsTopologicalGroup carrier
  inclusion : Fin n → carrier
  isFree : IsFreeProCGroupOnConvergingSet (ProC := ProC) (Fin n) carrier inclusion

attribute [instance] FiniteRankData.instGroup
attribute [instance] FiniteRankData.instTopologicalSpace
attribute [instance] FiniteRankData.instIsTopologicalGroup

namespace FiniteRankData

variable {ProC : ProCGroups.ProC.ProCGroupPredicate.{u}} {n : ℕ}

/-- The carrier of finite-rank free pro-`C` data is a pro-`C` group. -/
theorem isProC (Fdata : FiniteRankData ProC n) :
    ProC (G := Fdata.carrier) :=
  Fdata.isFree.isProC

/-- Homomorphisms out of finite-rank free pro-`C` data are determined by the finite basis. -/
theorem hom_ext
    (Fdata : FiniteRankData ProC n)
    {G : Type u} [Group G] [TopologicalSpace G] [T2Space G]
    {f g : Fdata.carrier →ₜ* G}
    (hfg : ∀ i, f (Fdata.inclusion i) = g (Fdata.inclusion i)) :
    f = g :=
  Fdata.isFree.hom_ext hfg

/-- Lift a map from a finite basis into a concrete finite-class pro-`C` target. -/
noncomputable def liftHom
    (C : ProCGroups.FiniteGroupClass.{u})
    [Fact (ProCGroups.FiniteGroupClass.Variety C)]
    [Fact (ProCGroups.FiniteGroupClass.IsomClosed C)]
    {n : ℕ}
    (Fdata :
      FiniteRankData
        (ProC := ProCGroups.ProC.finiteGroupClassProCPredicate C) n)
    {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    (hG : (ProCGroups.ProC.finiteGroupClassProCPredicate C) (G := G))
    (φ : Fin n → G) :
    Fdata.carrier →ₜ* G :=
  Fdata.isFree.liftHomOfFinite C hG φ

/-- The finite-rank lift has the prescribed value on the `i`th basis element. -/
@[simp] theorem liftHom_apply
    (C : ProCGroups.FiniteGroupClass.{u})
    [Fact (ProCGroups.FiniteGroupClass.Variety C)]
    [Fact (ProCGroups.FiniteGroupClass.IsomClosed C)]
    {n : ℕ}
    (Fdata :
      FiniteRankData
        (ProC := ProCGroups.ProC.finiteGroupClassProCPredicate C) n)
    {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    (hG : (ProCGroups.ProC.finiteGroupClassProCPredicate C) (G := G))
    (φ : Fin n → G) (i : Fin n) :
    Fdata.liftHom C hG φ (Fdata.inclusion i) = φ i :=
  Fdata.isFree.liftHomOfFinite_apply C hG φ i

/-- The finite-rank lift is unique among continuous homomorphisms with the prescribed values on
the finite basis. -/
theorem liftHom_unique
    (C : ProCGroups.FiniteGroupClass.{u})
    [Fact (ProCGroups.FiniteGroupClass.Variety C)]
    [Fact (ProCGroups.FiniteGroupClass.IsomClosed C)]
    {n : ℕ}
    (Fdata :
      FiniteRankData
        (ProC := ProCGroups.ProC.finiteGroupClassProCPredicate C) n)
    {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    (hG : (ProCGroups.ProC.finiteGroupClassProCPredicate C) (G := G))
    (φ : Fin n → G)
    {f : Fdata.carrier →ₜ* G} (hf : ∀ i, f (Fdata.inclusion i) = φ i) :
    f = Fdata.liftHom C hG φ :=
  Fdata.isFree.liftHomOfFinite_unique C hG φ hf

/-- The canonical continuous multiplicative equivalence between two finite-rank free pro-`C`
groups with the same rank. -/
noncomputable def equivOfSameRank
    (Fdata Edata : FiniteRankData ProC n) :
    Fdata.carrier ≃ₜ* Edata.carrier :=
  Fdata.isFree.continuousMulEquivOfSameBasis Edata.isFree

/-- The same-rank equivalence sends each basis element to the corresponding basis element. -/
@[simp] theorem equivOfSameRank_apply
    (Fdata Edata : FiniteRankData ProC n) (i : Fin n) :
    Fdata.equivOfSameRank Edata (Fdata.inclusion i) = Edata.inclusion i :=
  Fdata.isFree.continuousMulEquivOfSameBasis_apply Edata.isFree i

end FiniteRankData

/-- The finite-subset inverse system attached to a free pro-`C` group on a basis converging to
`1`.  For an infinite basis this is the usual projective system over all finite sub-bases. -/
structure FiniteSubsetSystem
    (ProC : ProCGroups.ProC.ProCGroupPredicate.{u})
    (X : Type u)
    (F : Type u) [Group F] [TopologicalSpace F] [IsTopologicalGroup F]
    (ι : X → F) where
  system : TopologicalGroupInverseSystemData (I := FiniteSubset X)
  basis : ∀ s : FiniteSubset X, ↥s.1 → system.toInverseSystem.X s
  stage_isFree :
    ∀ s : FiniteSubset X,
      IsFreeProCGroupOnConvergingSet (ProC := ProC)
        ↥s.1 (system.toInverseSystem.X s) (basis s)
  transition_basis :
    ∀ {s t : FiniteSubset X} (hst : s ≤ t) (x : ↥t.1),
      system.toInverseSystem.map hst (basis t x) =
        by
          classical
          exact if hx : x.1 ∈ s.1 then basis s ⟨x.1, hx⟩ else 1
  stage_embedding :
    ∀ s : FiniteSubset X,
      ∃ e : system.toInverseSystem.X s →* F,
        Continuous e ∧
          Function.Injective e ∧
          IsClosed (Set.range e) ∧
          ∀ x : ↥s.1, e (basis s x) = ι x.1
  limitEquiv : Nonempty (F ≃ₜ* system.toInverseSystem.inverseLimit)

/-- Construct the packaged finite-subset system from the explicit permanence hypotheses used by
the general finite-subset theorem. -/
theorem exists_finiteSubsetSystem
    {ProC : ProCGroups.ProC.ProCGroupPredicate.{u}}
    {X : Type u}
    {F : Type u} [Group F] [TopologicalSpace F] [IsTopologicalGroup F]
    {ι : X → F}
    (hProfinite :
      ∀ {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G],
        @ProCGroups.ProC.ProCGroupPredicate.holds ProC G _ _ _ →
          InverseSystems.IsProfiniteSpace G)
    (hClosed :
      ∀ {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
        (_hG : @ProCGroups.ProC.ProCGroupPredicate.holds ProC G _ _ _)
        (H : Subgroup G), IsClosed (H : Set G) →
          @ProCGroups.ProC.ProCGroupPredicate.holds ProC H _ _ _)
    (hFiniteQuot :
      ∀ {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
        (_hG : @ProCGroups.ProC.ProCGroupPredicate.holds ProC G _ _ _)
        (U : OpenNormalSubgroup G),
          @ProCGroups.ProC.ProCGroupPredicate.holds ProC (G ⧸ (U : Subgroup G)) _ _ _)
    (hF : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι) :
    Nonempty (FiniteSubsetSystem ProC X F ι) := by
  rcases exists_finiteSubsetSystem_raw
      (ProC := ProC) (X := X) (F := F) (ι := ι)
      hProfinite hClosed hFiniteQuot hF with
    ⟨S, basis, hbasis, htransition, hembed, hlimit⟩
  exact
    ⟨{ system := S
       basis := basis
       stage_isFree := hbasis
       transition_basis := htransition
       stage_embedding := hembed
       limitEquiv := hlimit }⟩

/-- A free pro-`C` group on a basis converging to `1` is a projective limit of the finite-rank
free pro-`C` groups attached to all finite sub-bases. -/
theorem isLimit_finiteSubsets
    {ProC : ProCGroups.ProC.ProCGroupPredicate.{u}}
    {X : Type u}
    {F : Type u} [Group F] [TopologicalSpace F] [IsTopologicalGroup F]
    {ι : X → F}
    (hProfinite :
      ∀ {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G],
        @ProCGroups.ProC.ProCGroupPredicate.holds ProC G _ _ _ →
          InverseSystems.IsProfiniteSpace G)
    (hClosed :
      ∀ {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
        (_hG : @ProCGroups.ProC.ProCGroupPredicate.holds ProC G _ _ _)
        (H : Subgroup G), IsClosed (H : Set G) →
          @ProCGroups.ProC.ProCGroupPredicate.holds ProC H _ _ _)
    (hFiniteQuot :
      ∀ {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
        (_hG : @ProCGroups.ProC.ProCGroupPredicate.holds ProC G _ _ _)
        (U : OpenNormalSubgroup G),
          @ProCGroups.ProC.ProCGroupPredicate.holds ProC (G ⧸ (U : Subgroup G)) _ _ _)
    (hF : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι) :
    ∃ S : FiniteSubsetSystem ProC X F ι,
      Nonempty (F ≃ₜ* S.system.toInverseSystem.inverseLimit) := by
  rcases exists_finiteSubsetSystem
      (ProC := ProC) (X := X) (F := F) (ι := ι)
      hProfinite hClosed hFiniteQuot hF with
    ⟨S⟩
  exact ⟨S, S.limitEquiv⟩

/-- Infinite-basis spelling of the finite-subset projective-limit theorem.  The construction is
the same as in the arbitrary-basis theorem, but this name is convenient for the standard
infinite-rank use case. -/
theorem isLimit_finiteSubsets_of_infinite
    {ProC : ProCGroups.ProC.ProCGroupPredicate.{u}}
    {X : Type u} [Infinite X]
    {F : Type u} [Group F] [TopologicalSpace F] [IsTopologicalGroup F]
    {ι : X → F}
    (hProfinite :
      ∀ {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G],
        @ProCGroups.ProC.ProCGroupPredicate.holds ProC G _ _ _ →
          InverseSystems.IsProfiniteSpace G)
    (hClosed :
      ∀ {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
        (_hG : @ProCGroups.ProC.ProCGroupPredicate.holds ProC G _ _ _)
        (H : Subgroup G), IsClosed (H : Set G) →
          @ProCGroups.ProC.ProCGroupPredicate.holds ProC H _ _ _)
    (hFiniteQuot :
      ∀ {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
        (_hG : @ProCGroups.ProC.ProCGroupPredicate.holds ProC G _ _ _)
        (U : OpenNormalSubgroup G),
          @ProCGroups.ProC.ProCGroupPredicate.holds ProC (G ⧸ (U : Subgroup G)) _ _ _)
    (hF : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι) :
    ∃ S : FiniteSubsetSystem ProC X F ι,
      Nonempty (F ≃ₜ* S.system.toInverseSystem.inverseLimit) :=
  isLimit_finiteSubsets
    (ProC := ProC) (X := X) (F := F) (ι := ι)
    hProfinite hClosed hFiniteQuot hF

/-- Concrete finite-group-class version of the finite-subset projective-limit system. -/
theorem exists_finiteSubsetSystem_of_class
    (C : ProCGroups.FiniteGroupClass.{u})
    [hVar : Fact (ProCGroups.FiniteGroupClass.Variety C)]
    [hIso : Fact (ProCGroups.FiniteGroupClass.IsomClosed C)]
    {X : Type u}
    {F : Type u} [Group F] [TopologicalSpace F] [IsTopologicalGroup F]
    {ι : X → F}
    (hF :
      IsFreeProCGroupOnConvergingSet
        (ProC := ProCGroups.ProC.finiteGroupClassProCPredicate C) X F ι) :
    Nonempty
      (FiniteSubsetSystem
        (ProCGroups.ProC.finiteGroupClassProCPredicate C) X F ι) := by
  refine exists_finiteSubsetSystem
    (ProC := ProCGroups.ProC.finiteGroupClassProCPredicate C)
    (X := X) (F := F) (ι := ι) ?_ ?_ ?_ hF
  · intro G _ _ _ hG
    let hGprof : ProCGroups.IsProfiniteGroup G :=
      ProCGroups.ProC.isProfiniteGroup_of_finiteGroupClassProCPredicate C hG
    exact (InverseSystems.isProfiniteSpace_iff_compact_t2_totallyDisconnected (X := G)).2
      ⟨ProCGroups.IsProfiniteGroup.compactSpace hGprof,
        ProCGroups.IsProfiniteGroup.t2Space hGprof,
        ProCGroups.IsProfiniteGroup.totallyDisconnectedSpace hGprof⟩
  · intro G _ _ _ hG H hH
    exact
      ProCGroups.ProC.IsProCGroup.of_isClosed_subgroup
        hIso.out hVar.out.subgroupClosed hVar.out.quotientClosed hG H hH
  · intro G _ _ _ hG U
    let hGprof : ProCGroups.IsProfiniteGroup G :=
      ProCGroups.ProC.isProfiniteGroup_of_finiteGroupClassProCPredicate C hG
    letI : CompactSpace G := ProCGroups.IsProfiniteGroup.compactSpace hGprof
    haveI : Finite (G ⧸ (U : Subgroup G)) :=
      openNormalSubgroup_finiteQuotient (G := G) U
    exact
      ProCGroups.ProC.IsProCGroup.of_finite_discrete
        (C := C) (G := G ⧸ (U : Subgroup G))
        hVar.out.quotientClosed
        (ProCGroups.ProC.IsProCGroup.hasAllOpenNormalQuotientsInClass_of_basis_of_quotientClosed
          hIso.out hVar.out.quotientClosed hG U)

/-- Concrete finite-group-class version: a free pro-`C` group on an infinite basis is the
projective limit of its finite-sub-basis free pro-`C` groups. -/
theorem isLimit_finiteSubsets_of_class_of_infinite
    (C : ProCGroups.FiniteGroupClass.{u})
    [Fact (ProCGroups.FiniteGroupClass.Variety C)]
    [Fact (ProCGroups.FiniteGroupClass.IsomClosed C)]
    {X : Type u} [Infinite X]
    {F : Type u} [Group F] [TopologicalSpace F] [IsTopologicalGroup F]
    {ι : X → F}
    (hF :
      IsFreeProCGroupOnConvergingSet
        (ProC := ProCGroups.ProC.finiteGroupClassProCPredicate C) X F ι) :
    ∃ S : FiniteSubsetSystem
      (ProCGroups.ProC.finiteGroupClassProCPredicate C) X F ι,
      Nonempty (F ≃ₜ* S.system.toInverseSystem.inverseLimit) := by
  rcases exists_finiteSubsetSystem_of_class
      (C := C) (X := X) (F := F) (ι := ι) hF with
    ⟨S⟩
  exact ⟨S, S.limitEquiv⟩

end ProCGroups.FreeProC
