import FoxDifferential.Completed.CoefficientRings.AugmentationIdealPrimePower.SubtypeLinear

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/FoxDifferential/Completed/FiniteStage/Basic.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Finite-stage completed Fox calculus

Finite quotient stages are used to compare completed Fox boundaries, derivatives, and relation modules with explicit finite group-algebra calculations.
-/
namespace FoxDifferential

noncomputable section

open ProCGroups.InverseSystems
open ProCGroups.ProC

universe u v

variable (ℓ : ℕ) [Fact (0 < ℓ)]
variable {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
variable {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

section ModNStageMapScalar

variable (n : ℕ) [Fact (0 < n)]

omit [Fact (0 < n)] in
/-- The finite-stage completed group-algebra projection preserves coefficient algebra maps. -/
@[simp]
theorem modNCompletedGroupAlgebraStageMap_algebraMap
    (U : _root_.CompletedGroupAlgebra.CompletedGroupAlgebraIndex G) (c : ModNCompletedCoeff n) :
    modNCompletedGroupAlgebraStageMap n G U
        (algebraMap (ModNCompletedCoeff n) (ModNCompletedGroupRing n G) c) =
      algebraMap (ModNCompletedCoeff n) (ModNCompletedGroupAlgebraStage n G U) c := by
  rcases ZMod.intCast_surjective c with ⟨t, rfl⟩
  simp only [modNCompletedGroupAlgebraStageMap, map_intCast]

end ModNStageMapScalar

section FiniteFoxCommutatorPowerQuotient

variable {F : Type u} [Group F]

/-- Relators defining the finite Fox source quotient: commutators in `N` and `n`th powers in
`N`. -/
def finiteFoxCommutatorPowerRelatorSet (N : Subgroup F) (n : ℕ) : Set F :=
  {g | (∃ a ∈ N, ∃ b ∈ N, ⁅a, b⁆ = g) ∨ ∃ a ∈ N, a ^ n = g}

/-- Normal subgroup generated by commutators in `N` and `n`th powers in `N`. -/
def finiteFoxCommutatorPowerSubgroup (N : Subgroup F) (n : ℕ) : Subgroup F :=
  Subgroup.normalClosure (finiteFoxCommutatorPowerRelatorSet (F := F) N n)

/-- The finite Fox commutator-power subgroup is normal by construction. -/
instance finiteFoxCommutatorPowerSubgroup_normal
    (N : Subgroup F) (n : ℕ) :
    (finiteFoxCommutatorPowerSubgroup (F := F) N n).Normal := by
  dsimp [finiteFoxCommutatorPowerSubgroup]
  infer_instance

/-- The finite Fox commutator-power relator set is contained in `N`. -/
theorem finiteFoxCommutatorPowerRelatorSet_subset
    (N : Subgroup F) (n : ℕ) :
    finiteFoxCommutatorPowerRelatorSet (F := F) N n ⊆ N := by
  intro g hg
  rcases hg with ⟨a, ha, b, hb, rfl⟩ | ⟨a, ha, rfl⟩
  · rw [commutatorElement_def]
    exact N.mul_mem (N.mul_mem (N.mul_mem ha hb) (N.inv_mem ha)) (N.inv_mem hb)
  · exact N.pow_mem ha n

/-- The finite Fox commutator-power subgroup is contained in `N` when `N` is normal. -/
theorem finiteFoxCommutatorPowerSubgroup_le_normal
    (N : Subgroup F) [N.Normal] (n : ℕ) :
    finiteFoxCommutatorPowerSubgroup (F := F) N n ≤ N := by
  exact Subgroup.normalClosure_le_normal
    (finiteFoxCommutatorPowerRelatorSet_subset (F := F) N n)

/-- Natural quotient map `F/[N,N]N^n → F/N`. -/
def finiteFoxCommutatorPowerQuotientMapToNormalQuotient
    (N : Subgroup F) [N.Normal] (n : ℕ) :
    F ⧸ finiteFoxCommutatorPowerSubgroup (F := F) N n →* F ⧸ N :=
  QuotientGroup.map _ _ (MonoidHom.id F)
    (finiteFoxCommutatorPowerSubgroup_le_normal (F := F) N n)

/-- Evaluation of the natural quotient map `F/[N,N]N^n → F/N` on a representative. -/
@[simp]
theorem finiteFoxCommutatorPowerQuotientMapToNormalQuotient_mk
    (N : Subgroup F) [N.Normal] (n : ℕ) (g : F) :
    finiteFoxCommutatorPowerQuotientMapToNormalQuotient (F := F) N n
        (QuotientGroup.mk'
          (finiteFoxCommutatorPowerSubgroup (F := F) N n) g) =
      QuotientGroup.mk' N g := by
  rfl

/-- The natural quotient map `F/[N,N]N^n → F/N` is surjective. -/
theorem finiteFoxCommutatorPowerQuotientMapToNormalQuotient_surjective
    (N : Subgroup F) [N.Normal] (n : ℕ) :
    Function.Surjective
      (finiteFoxCommutatorPowerQuotientMapToNormalQuotient (F := F) N n) := by
  intro y
  rcases QuotientGroup.mk'_surjective N y with ⟨g, rfl⟩
  exact ⟨QuotientGroup.mk'
    (finiteFoxCommutatorPowerSubgroup (F := F) N n) g, rfl⟩

/-- Group-algebra map induced by the natural quotient `F/[N,N]N^n → F/N`. -/
def finiteFoxCommutatorPowerGroupAlgebraMap
    (N : Subgroup F) [N.Normal] (n : ℕ) :
    MonoidAlgebra (ModNCompletedCoeff n)
        (F ⧸ finiteFoxCommutatorPowerSubgroup (F := F) N n) →+*
      MonoidAlgebra (ModNCompletedCoeff n) (F ⧸ N) :=
  MonoidAlgebra.mapDomainRingHom (ModNCompletedCoeff n)
    (finiteFoxCommutatorPowerQuotientMapToNormalQuotient (F := F) N n)

/-- Algebra-hom version of the group-algebra map induced by
`F/[N,N]N^n → F/N`. -/
def finiteFoxCommutatorPowerGroupAlgebraAlgHom
    (N : Subgroup F) [N.Normal] (n : ℕ) :
    MonoidAlgebra (ModNCompletedCoeff n)
        (F ⧸ finiteFoxCommutatorPowerSubgroup (F := F) N n) →ₐ[
      ModNCompletedCoeff n]
      MonoidAlgebra (ModNCompletedCoeff n) (F ⧸ N) :=
  MonoidAlgebra.mapDomainAlgHom (ModNCompletedCoeff n) (ModNCompletedCoeff n)
    (finiteFoxCommutatorPowerQuotientMapToNormalQuotient (F := F) N n)

/-- The algebra-hom and ring-hom versions of the finite Fox quotient map agree on values. -/
@[simp]
theorem finiteFoxCommutatorPowerGroupAlgebraAlgHom_apply
    (N : Subgroup F) [N.Normal] (n : ℕ)
    (x : MonoidAlgebra (ModNCompletedCoeff n)
        (F ⧸ finiteFoxCommutatorPowerSubgroup (F := F) N n)) :
    finiteFoxCommutatorPowerGroupAlgebraAlgHom (F := F) N n x =
      finiteFoxCommutatorPowerGroupAlgebraMap (F := F) N n x := rfl

/-- Augmentation map on the finite Fox source group algebra. -/
def finiteFoxCommutatorPowerSourceGroupAlgebraAugmentation
    (N : Subgroup F) (n : ℕ) :
    MonoidAlgebra (ModNCompletedCoeff n)
        (F ⧸ finiteFoxCommutatorPowerSubgroup (F := F) N n) →ₐ[
      ModNCompletedCoeff n] ModNCompletedCoeff n :=
  MonoidAlgebra.lift (ModNCompletedCoeff n) (ModNCompletedCoeff n)
    (F ⧸ finiteFoxCommutatorPowerSubgroup (F := F) N n)
    (1 : (F ⧸ finiteFoxCommutatorPowerSubgroup (F := F) N n) →*
      ModNCompletedCoeff n)

/-- The source augmentation sends every quotient group basis element to `1`. -/
@[simp]
theorem finiteFoxCommutatorPowerSourceGroupAlgebraAugmentation_of_quotient
    (N : Subgroup F) (n : ℕ)
    (q : F ⧸ finiteFoxCommutatorPowerSubgroup (F := F) N n) :
    finiteFoxCommutatorPowerSourceGroupAlgebraAugmentation (F := F) N n
        (MonoidAlgebra.of (ModNCompletedCoeff n)
          (F ⧸ finiteFoxCommutatorPowerSubgroup (F := F) N n) q) =
      1 := by
  simp only [finiteFoxCommutatorPowerSourceGroupAlgebraAugmentation, MonoidAlgebra.of_apply,
  MonoidAlgebra.lift_single, MonoidHom.one_apply, smul_eq_mul, mul_one]

/-- Evaluation of the finite Fox source-to-target group-algebra map on a represented word. -/
@[simp]
theorem finiteFoxCommutatorPowerGroupAlgebraMap_of
    (N : Subgroup F) [N.Normal] (n : ℕ) (g : F) :
    finiteFoxCommutatorPowerGroupAlgebraMap (F := F) N n
        (MonoidAlgebra.of (ModNCompletedCoeff n)
          (F ⧸ finiteFoxCommutatorPowerSubgroup (F := F) N n)
          (QuotientGroup.mk'
            (finiteFoxCommutatorPowerSubgroup (F := F) N n) g)) =
      MonoidAlgebra.of (ModNCompletedCoeff n) (F ⧸ N) (QuotientGroup.mk' N g) := by
  simp only [finiteFoxCommutatorPowerGroupAlgebraMap, MonoidAlgebra.of, MonoidAlgebra.single,
  QuotientGroup.mk'_apply, MonoidHom.coe_mk, OneHom.coe_mk, MonoidAlgebra.mapDomainRingHom_apply,
  Finsupp.mapDomain_single]
  simpa using congrArg
    (fun q : F ⧸ N => Finsupp.single q (1 : ModNCompletedCoeff n))
    (finiteFoxCommutatorPowerQuotientMapToNormalQuotient_mk (F := F) N n g)

/-- Evaluation of the finite Fox source-to-target group-algebra map on a quotient basis
element. -/
@[simp]
theorem finiteFoxCommutatorPowerGroupAlgebraMap_of_quotient
    (N : Subgroup F) [N.Normal] (n : ℕ)
    (q : F ⧸ finiteFoxCommutatorPowerSubgroup (F := F) N n) :
    finiteFoxCommutatorPowerGroupAlgebraMap (F := F) N n
        (MonoidAlgebra.of (ModNCompletedCoeff n)
          (F ⧸ finiteFoxCommutatorPowerSubgroup (F := F) N n) q) =
      MonoidAlgebra.of (ModNCompletedCoeff n) (F ⧸ N)
        (finiteFoxCommutatorPowerQuotientMapToNormalQuotient (F := F) N n q) := by
  rcases QuotientGroup.mk'_surjective
    (finiteFoxCommutatorPowerSubgroup (F := F) N n) q with ⟨g, rfl⟩
  rw [finiteFoxCommutatorPowerGroupAlgebraMap_of,
    finiteFoxCommutatorPowerQuotientMapToNormalQuotient_mk]

omit [Fact (0 < ℓ)] in
/-- Evaluation of the finite Fox source-to-target group-algebra map on a single coefficient
basis term. -/
@[simp]
theorem finiteFoxCommutatorPowerGroupAlgebraMap_single_apply
    (N : Subgroup F) [N.Normal] (n : ℕ)
    (q : F ⧸ finiteFoxCommutatorPowerSubgroup (F := F) N n)
    (a : ModNCompletedCoeff n) :
    finiteFoxCommutatorPowerGroupAlgebraMap (F := F) N n
        (MonoidAlgebra.single q a) =
      MonoidAlgebra.single
        (finiteFoxCommutatorPowerQuotientMapToNormalQuotient (F := F) N n q) a := by
  rw [finiteFoxCommutatorPowerGroupAlgebraMap]
  exact Finsupp.mapDomain_single

end FiniteFoxCommutatorPowerQuotient

end

end FoxDifferential
