import FoxDifferential.Completed.FiniteStage.RelationSubmodule

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/FoxDifferential/Completed/FiniteStage/BoundaryQuotient.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Finite-stage boundary quotient

This file adds the quotient-obstruction formulation of the finite-stage problem.  After quotienting
coordinate vectors by the submodule generated by relation boundaries, the finite Fox boundary
`∂` descends.  Injectivity of the descended boundary is equivalent to module-level exactness at the
coordinate module.
-/

namespace FoxDifferential

noncomputable section

open ProCGroups.InverseSystems
open ProCGroups.ProC

universe u

variable {X : Type u} [DecidableEq X]
variable (N : Subgroup (FreeGroup X)) [N.Normal] (n : ℕ)

/-- Finite coordinate vectors modulo the submodule generated by finite relation boundaries. -/
abbrev finiteFoxStageCoordinateModuloRelations : Type u :=
  finiteFoxStageCoordinateVector (X := X) N n ⧸
    finiteFoxStageRelationBoundarySubmodule (X := X) N n

/-- The finite Fox boundary descends to the quotient by relation boundaries. -/
def finiteFoxStageBoundaryModuloRelations [Fintype X] :
    finiteFoxStageCoordinateModuloRelations (X := X) N n →ₗ[
      finiteFoxStageTargetGroupAlgebra (X := X) N n]
      finiteFoxStageTargetGroupAlgebra (X := X) N n :=
  Submodule.liftQ (finiteFoxStageRelationBoundarySubmodule (X := X) N n)
    (finiteFoxStageFoxBoundary (X := X) N n)
    (finiteFoxStageRelationBoundarySubmodule_le_boundaryCycleSubmodule (X := X) N n)

@[simp]
theorem finiteFoxStageBoundaryModuloRelations_mk
    [Fintype X] (v : finiteFoxStageCoordinateVector (X := X) N n) :
    finiteFoxStageBoundaryModuloRelations (X := X) N n
        (Submodule.Quotient.mk v : finiteFoxStageCoordinateModuloRelations (X := X) N n) =
      finiteFoxStageFoxBoundary (X := X) N n v := by
  rfl

/-- A boundary cycle represents zero in the relation quotient when module-level finite exactness
holds. -/
theorem finiteFoxStageCoordinateModuloRelations_mk_eq_zero_of_cycle
    [Fintype X]
    (hexact : finiteFoxStageRelationBoundaryModuleExact (X := X) N n)
    {v : finiteFoxStageCoordinateVector (X := X) N n}
    (hv : v ∈ finiteFoxStageBoundaryCycleSubmodule (X := X) N n) :
    (Submodule.Quotient.mk v : finiteFoxStageCoordinateModuloRelations (X := X) N n) = 0 := by
  exact (Submodule.Quotient.mk_eq_zero
    (p := finiteFoxStageRelationBoundarySubmodule (X := X) N n) (x := v)).2
    (hexact hv)

/-- If module-level finite exactness holds, the descended finite boundary has trivial kernel. -/
theorem finiteFoxStageBoundaryModuloRelations_injective_of_relationBoundaryModuleExact
    [Fintype X]
    (hexact : finiteFoxStageRelationBoundaryModuleExact (X := X) N n) :
    Function.Injective (finiteFoxStageBoundaryModuloRelations (X := X) N n) := by
  have hker : ∀ q : finiteFoxStageCoordinateModuloRelations (X := X) N n,
      finiteFoxStageBoundaryModuloRelations (X := X) N n q = 0 → q = 0 := by
    intro q
    refine Submodule.Quotient.induction_on
      (p := finiteFoxStageRelationBoundarySubmodule (X := X) N n) q ?_
    intro v hv
    rw [finiteFoxStageBoundaryModuloRelations_mk] at hv
    have hvcycle : v ∈ finiteFoxStageBoundaryCycleSubmodule (X := X) N n := hv
    exact finiteFoxStageCoordinateModuloRelations_mk_eq_zero_of_cycle
      (X := X) N n hexact hvcycle
  intro x y hxy
  have hsub : finiteFoxStageBoundaryModuloRelations (X := X) N n (x - y) = 0 := by
    rw [map_sub, hxy, sub_self]
  exact sub_eq_zero.mp (hker (x - y) hsub)

/-- Injectivity of the descended finite boundary implies module-level finite exactness. -/
theorem finiteFoxStageRelationBoundaryModuleExact_of_boundaryModuloRelations_injective
    [Fintype X]
    (hinj : Function.Injective (finiteFoxStageBoundaryModuloRelations (X := X) N n)) :
    finiteFoxStageRelationBoundaryModuleExact (X := X) N n := by
  intro v hv
  have hq :
      (Submodule.Quotient.mk v : finiteFoxStageCoordinateModuloRelations (X := X) N n) = 0 := by
    apply hinj
    calc
      finiteFoxStageBoundaryModuloRelations (X := X) N n
          (Submodule.Quotient.mk v : finiteFoxStageCoordinateModuloRelations (X := X) N n) =
        finiteFoxStageFoxBoundary (X := X) N n v := by
          rw [finiteFoxStageBoundaryModuloRelations_mk]
      _ = 0 := hv
      _ = finiteFoxStageBoundaryModuloRelations (X := X) N n
          (0 : finiteFoxStageCoordinateModuloRelations (X := X) N n) := by
          simp only [map_zero]
  exact (Submodule.Quotient.mk_eq_zero
    (p := finiteFoxStageRelationBoundarySubmodule (X := X) N n) (x := v)).1 hq

end

end FoxDifferential
