import FoxDifferential.Completed.FiniteStage.RelationSubmodule
import FoxDifferential.Completed.FiniteStage.BoundarySubgroups

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/FoxDifferential/Completed/FiniteStage/RelationRealization.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Realizing the finite-stage relation submodule by source-kernel derivatives

`RelationSubmodule.lean` constructs the module generated by finite-stage relation derivatives.
This file proves that the generated submodule is not larger than the actual source-kernel
derivative image: the relation-boundary image is closed under the finite target group algebra by
conjugating relations.
-/

namespace FoxDifferential

noncomputable section

open ProCGroups.InverseSystems
open ProCGroups.ProC

universe u

variable {X : Type u} [DecidableEq X]
variable (N : Subgroup (FreeGroup X)) [N.Normal] (n : ℕ)

/-- The additive source-kernel derivative set is closed under integer multiples. -/
theorem finiteFoxStageSourceKernelDerivativeSet_zsmul_mem
    (m : ℤ) {v : finiteFoxStageCoordinateVector (X := X) N n}
    (hv : v ∈ finiteFoxStageSourceKernelDerivativeSet (X := X) N n) :
    m • v ∈ finiteFoxStageSourceKernelDerivativeSet (X := X) N n := by
  have hv' : v ∈ finiteFoxStageSourceKernelDerivativeAddSubgroup (X := X) N n := hv
  exact (finiteFoxStageSourceKernelDerivativeAddSubgroup (X := X) N n).zsmul_mem hv' m

/-- The source-kernel derivative set is stable under multiplication by target-group basis
coefficients.  This is the finite algebraic form of conjugating a relation by a chosen lift of a
target quotient element. -/
theorem finiteFoxStageSourceKernelDerivativeSet_basis_smul_mem
    (h : finiteFoxStageTargetQuotient (X := X) N)
    {v : finiteFoxStageCoordinateVector (X := X) N n}
    (hv : v ∈ finiteFoxStageSourceKernelDerivativeSet (X := X) N n) :
    (MonoidAlgebra.of (ModNCompletedCoeff n)
        (finiteFoxStageTargetQuotient (X := X) N) h) • v ∈
      finiteFoxStageSourceKernelDerivativeSet (X := X) N n := by
  have hvRange : v ∈ finiteFoxStageRelationBoundaryRange (X := X) N n := hv
  exact finiteFoxStageRelationBoundaryRange_basis_smul_mem (X := X) N n h hvRange

/-- Word-level finite relation derivatives are stable under multiplication by target-group basis
coefficients, after rewriting the source-kernel and word-level descriptions. -/
theorem finiteFoxStageKernelWordDerivativeSet_basis_smul_mem
    (h : finiteFoxStageTargetQuotient (X := X) N)
    {v : finiteFoxStageCoordinateVector (X := X) N n}
    (hv : v ∈ finiteFoxStageKernelWordDerivativeSet (X := X) N n) :
    (MonoidAlgebra.of (ModNCompletedCoeff n)
        (finiteFoxStageTargetQuotient (X := X) N) h) • v ∈
      finiteFoxStageKernelWordDerivativeSet (X := X) N n := by
  rw [← finiteFoxStageSourceKernelDerivativeSet_eq_kernelWordDerivativeSet (X := X) N n]
  rw [← finiteFoxStageSourceKernelDerivativeSet_eq_kernelWordDerivativeSet (X := X) N n] at hv
  exact finiteFoxStageSourceKernelDerivativeSet_basis_smul_mem (X := X) N n h hv

/-- Module-level finite exactness gives function-level finite exactness for the relation boundary
followed by the Fox boundary. -/
theorem finiteFoxStageRelationBoundaryExact_of_relationBoundaryModuleExact
    [Fintype X]
    (hexact : finiteFoxStageRelationBoundaryModuleExact (X := X) N n) :
    finiteFoxStageRelationBoundaryExact (X := X) N n :=
  finiteFoxStageRelationBoundaryExact_of_boundaryCyclesCoveredBySourceKernel
    (X := X) N n
    (finiteFoxStageBoundaryCyclesCoveredBySourceKernel_of_relationBoundaryModuleExact
      (X := X) N n hexact)

/-- Module-level finite exactness gives finite semidirect coverage of boundary cycles `(v,1)`. -/
theorem finiteFoxStageSemiBoundaryCyclesCovered_of_relBoundaryModuleExact
    [Fintype X]
    (hexact : finiteFoxStageRelationBoundaryModuleExact (X := X) N n) :
    finiteFoxStageSemidirectBoundaryCyclesCoveredBySourceKernel (X := X) N n :=
  (finiteFoxStageSemidirectBoundaryCyclesCoveredBySourceKernel_iff (X := X) N n).2
    (finiteFoxStageBoundaryCyclesCoveredBySourceKernel_of_relationBoundaryModuleExact
      (X := X) N n hexact)


end

end FoxDifferential
