import FoxDifferential.Completed.FiniteStage.SourceBoundary

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/FoxDifferential/Completed/FiniteStage/RelationIdealDerivative.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Derivatives of the finite-stage relation ideal

This file attacks the last finite algebra layer in the completed Crowell density proof.
The source-to-target group-algebra kernel has already been identified with the relation
augmentation ideal generated by `q - 1`.  Here we differentiate that ideal and prove that its
finite Fox derivatives land in the relation-boundary submodule.  Combining this with the
calculation that differentiating the source boundary `Σ a_i([x_i]-1)` recovers the target
coordinate vector closes the source-boundary relation-ideal reduction.
-/

namespace FoxDifferential

noncomputable section

open ProCGroups.InverseSystems
open ProCGroups.ProC

universe u

variable {X : Type u} [DecidableEq X]
variable (N : Subgroup (FreeGroup X)) [N.Normal] (n : ℕ)

/-- The vector of target-valued finite Fox derivatives of a source group-algebra element. -/
def finiteFoxStageGroupAlgebraDerivativeVector
    (x : finiteFoxStageSourceGroupAlgebra (X := X) N n) :
    finiteFoxStageCoordinateVector (X := X) N n :=
  fun i => finiteFoxStageGroupAlgebraDerivative (X := X) N n i x

@[simp]
theorem finiteFoxStageGroupAlgebraDerivativeVector_apply
    (x : finiteFoxStageSourceGroupAlgebra (X := X) N n) (i : X) :
    finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n x i =
      finiteFoxStageGroupAlgebraDerivative (X := X) N n i x :=
  rfl

@[simp]
theorem finiteFoxStageGroupAlgebraDerivativeVector_zero :
    finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n 0 = 0 := by
  funext i
  simp only [finiteFoxStageGroupAlgebraDerivativeVector_apply, map_zero, Pi.zero_apply]

@[simp]
theorem finiteFoxStageGroupAlgebraDerivativeVector_add
    (x y : finiteFoxStageSourceGroupAlgebra (X := X) N n) :
    finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n (x + y) =
      finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n x +
        finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n y := by
  funext i
  simp only [finiteFoxStageGroupAlgebraDerivativeVector, map_add, Pi.add_apply]

@[simp]
theorem finiteFoxStageGroupAlgebraDerivativeVector_neg
    (x : finiteFoxStageSourceGroupAlgebra (X := X) N n) :
    finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n (-x) =
      -finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n x := by
  funext i
  simp only [finiteFoxStageGroupAlgebraDerivativeVector_apply, map_neg, Pi.neg_apply]

@[simp]
theorem finiteFoxStageGroupAlgebraDerivativeVector_sub
    (x y : finiteFoxStageSourceGroupAlgebra (X := X) N n) :
    finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n (x - y) =
      finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n x -
        finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n y := by
  funext i
  simp only [finiteFoxStageGroupAlgebraDerivativeVector, map_sub, Pi.sub_apply]

/-- Product rule for the vector of target-valued derivatives. -/
theorem finiteFoxStageGroupAlgebraDerivativeVector_mul
    (x y : finiteFoxStageSourceGroupAlgebra (X := X) N n) :
    finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n (x * y) =
      (algebraMap (ModNCompletedCoeff n)
        (finiteFoxStageTargetGroupAlgebra (X := X) N n)
        (finiteFoxCommutatorPowerSourceGroupAlgebraAugmentation
          (F := FreeGroup X) N n y)) •
        finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n x +
    finiteFoxCommutatorPowerGroupAlgebraMap (F := FreeGroup X) N n x •
        finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n y := by
  funext i
  simp only [finiteFoxStageGroupAlgebraDerivativeVector, finiteFoxStageGroupAlgebraDerivative_mul,
  Algebra.smul_def, MonoidAlgebra.coe_algebraMap, Algebra.algebraMap_self, RingHom.coe_id, Function.comp_apply, id_eq,
  Pi.add_apply, Pi.smul_apply, smul_eq_mul]

/-- The derivative vector of a relation augmentation generator is the corresponding relation
boundary vector. -/
theorem finiteFoxStageGroupAlgebraDerivativeVector_relationAugmentationGenerator
    (q : finiteFoxStageRelationGroup (X := X) N n) :
    finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n
        (finiteFoxStageRelationAugmentationGenerator (X := X) N n q) =
      finiteFoxStageRelationBoundaryAddMonoidHom (X := X) N n (Additive.ofMul q) := by
  funext i
  rw [finiteFoxStageGroupAlgebraDerivativeVector_apply,
    finiteFoxStageRelationBoundaryAddMonoidHom_of]
  rw [finiteFoxStageRelationAugmentationGenerator, map_sub,
    finiteFoxStageGroupAlgebraDerivative_of_quotient,
    finiteFoxStageGroupAlgebraDerivative_one, sub_zero]
  rfl

omit [DecidableEq X] in
/-- Relation augmentation generators have zero source augmentation. -/
theorem finiteFoxStageRelationAugmentationGenerator_sourceAugmentation_eq_zero
    (q : finiteFoxStageRelationGroup (X := X) N n) :
    finiteFoxCommutatorPowerSourceGroupAlgebraAugmentation
        (F := FreeGroup X) N n
        (finiteFoxStageRelationAugmentationGenerator (X := X) N n q) = 0 := by
  rw [finiteFoxStageRelationAugmentationGenerator, map_sub, map_one,
    finiteFoxCommutatorPowerSourceGroupAlgebraAugmentation_of_quotient]
  simp only [sub_self]

omit [DecidableEq X] in
/-- Relation augmentation generators have zero target image. -/
theorem finiteFoxStageRelationAugmentationGenerator_groupAlgebraMap_eq_zero
    (q : finiteFoxStageRelationGroup (X := X) N n) :
    finiteFoxCommutatorPowerGroupAlgebraMap (F := FreeGroup X) N n
        (finiteFoxStageRelationAugmentationGenerator (X := X) N n q) = 0 := by
  exact
    (mem_finiteFoxStageGroupAlgebraMapKernelIdeal (X := X) (N := N) (n := n)).1
      (finiteFoxStageRelationAugmentationGenerator_mem_groupAlgebraMapKernel
        (X := X) N n q)

/-- The derivative vector of every element of the finite relation augmentation ideal lies in the
relation-boundary submodule.  The proof keeps the two extra invariants used by the product rule:
elements of this ideal have zero target image and zero augmentation. -/
theorem finiteFoxGADeriv_mem_relBoundarySubmodule_of_mem_relAugIdeal
    {x : finiteFoxStageSourceGroupAlgebra (X := X) N n}
    (hx : x ∈ finiteFoxStageRelationAugmentationIdeal (X := X) N n) :
    finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n x ∈
      finiteFoxStageRelationBoundarySubmodule (X := X) N n := by
  let P : finiteFoxStageSourceGroupAlgebra (X := X) N n → Prop := fun z =>
    finiteFoxCommutatorPowerGroupAlgebraMap (F := FreeGroup X) N n z = 0 ∧
      finiteFoxCommutatorPowerSourceGroupAlgebraAugmentation (F := FreeGroup X) N n z = 0 ∧
        finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n z ∈
          finiteFoxStageRelationBoundarySubmodule (X := X) N n
  have hP : P x := by
    change x ∈ Submodule.span (finiteFoxStageSourceGroupAlgebra (X := X) N n)
        (Set.range (finiteFoxStageRelationAugmentationGenerator (X := X) N n)) at hx
    refine Submodule.span_induction (p := fun z _ => P z) ?hgen ?hzero ?hadd ?hsmul hx
    · rintro z ⟨q, rfl⟩
      refine ⟨?_, ?_, ?_⟩
      · exact finiteFoxStageRelationAugmentationGenerator_groupAlgebraMap_eq_zero
          (X := X) N n q
      · exact finiteFoxStageRelationAugmentationGenerator_sourceAugmentation_eq_zero
          (X := X) N n q
      · rw [finiteFoxStageGroupAlgebraDerivativeVector_relationAugmentationGenerator]
        exact finiteFoxStageRelationBoundaryAddMonoidHom_mem_relationBoundarySubmodule
          (X := X) N n (Additive.ofMul q)
    · refine ⟨?_, ?_, ?_⟩
      · simp only [map_zero]
      · simp only [map_zero]
      · simp only [finiteFoxStageGroupAlgebraDerivativeVector_zero, zero_mem]
    · intro a b _ _ ha hb
      rcases ha with ⟨ha_map, ha_aug, ha_der⟩
      rcases hb with ⟨hb_map, hb_aug, hb_der⟩
      refine ⟨?_, ?_, ?_⟩
      · rw [map_add, ha_map, hb_map, add_zero]
      · rw [map_add, ha_aug, hb_aug, add_zero]
      · rw [finiteFoxStageGroupAlgebraDerivativeVector_add]
        exact (finiteFoxStageRelationBoundarySubmodule (X := X) N n).add_mem ha_der hb_der
    · intro a z _ hz
      rcases hz with ⟨hz_map, hz_aug, hz_der⟩
      refine ⟨?_, ?_, ?_⟩
      · change finiteFoxCommutatorPowerGroupAlgebraMap (F := FreeGroup X) N n (a * z) = 0
        rw [RingHom.map_mul, hz_map, mul_zero]
      · change finiteFoxCommutatorPowerSourceGroupAlgebraAugmentation
            (F := FreeGroup X) N n (a * z) = 0
        rw [map_mul, hz_aug, mul_zero]
      · have hderivative :
            finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n (a * z) =
              finiteFoxCommutatorPowerGroupAlgebraMap (F := FreeGroup X) N n a •
                finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n z := by
          rw [finiteFoxStageGroupAlgebraDerivativeVector_mul]
          rw [hz_aug]
          simp only [MonoidAlgebra.coe_algebraMap, Algebra.algebraMap_self, RingHom.coe_id, Function.comp_apply, id_eq,
  Finsupp.single_zero, zero_smul, zero_add]
        change finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n (a * z) ∈
          finiteFoxStageRelationBoundarySubmodule (X := X) N n
        rw [hderivative]
        exact (finiteFoxStageRelationBoundarySubmodule (X := X) N n).smul_mem _ hz_der
  exact hP.2.2

/-- Differentiating the source Fox boundary recovers the coordinatewise source-to-target image. -/
theorem finiteFoxStageGroupAlgebraDerivativeVector_sourceFoxBoundary
    [Fintype X]
    (a : finiteFoxStageSourceCoordinateVector (X := X) N n) :
    finiteFoxStageGroupAlgebraDerivativeVector (X := X) N n
        (finiteFoxStageSourceFoxBoundary (X := X) N n a) =
      finiteFoxStageCoordinateSourceToTarget (X := X) N n a := by
  funext j
  rw [finiteFoxStageGroupAlgebraDerivativeVector_apply,
    finiteFoxStageSourceFoxBoundary_apply,
    finiteFoxStageCoordinateSourceToTarget_apply]
  have hgen_aug (i : X) :
      finiteFoxCommutatorPowerSourceGroupAlgebraAugmentation
          (F := FreeGroup X) N n
          (MonoidAlgebra.of (ModNCompletedCoeff n)
              (FreeGroup X ⧸ finiteFoxCommutatorPowerSubgroup (F := FreeGroup X) N n)
              (QuotientGroup.mk'
                (finiteFoxCommutatorPowerSubgroup (F := FreeGroup X) N n)
                (FreeGroup.of i)) - 1) = 0 := by
    rw [map_sub, map_one, finiteFoxCommutatorPowerSourceGroupAlgebraAugmentation_of_quotient]
    simp only [sub_self]
  have hgen_derivative (i : X) :
      finiteFoxStageGroupAlgebraDerivative (X := X) N n j
          (MonoidAlgebra.of (ModNCompletedCoeff n)
              (FreeGroup X ⧸ finiteFoxCommutatorPowerSubgroup (F := FreeGroup X) N n)
              (QuotientGroup.mk'
                (finiteFoxCommutatorPowerSubgroup (F := FreeGroup X) N n)
                (FreeGroup.of i)) - 1) =
        (Pi.single i (1 : finiteFoxStageTargetGroupAlgebra (X := X) N n) :
          X → finiteFoxStageTargetGroupAlgebra (X := X) N n) j := by
    rw [map_sub, finiteFoxStageGroupAlgebraDerivative_of,
      finiteFoxStageGroupAlgebraDerivative_one, sub_zero]
    simp only [finiteFoxStageDerivative, finiteFoxStageDerivativeVector_of]
  calc
    finiteFoxStageGroupAlgebraDerivative (X := X) N n j
        (∑ i : X,
          a i *
            (MonoidAlgebra.of (ModNCompletedCoeff n)
              (FreeGroup X ⧸ finiteFoxCommutatorPowerSubgroup (F := FreeGroup X) N n)
              (QuotientGroup.mk'
                (finiteFoxCommutatorPowerSubgroup (F := FreeGroup X) N n)
                (FreeGroup.of i)) - 1))
        =
      ∑ i : X,
        finiteFoxCommutatorPowerGroupAlgebraMap (F := FreeGroup X) N n (a i) *
          ((Pi.single i (1 : finiteFoxStageTargetGroupAlgebra (X := X) N n) :
            X → finiteFoxStageTargetGroupAlgebra (X := X) N n) j) := by
        rw [map_sum]
        apply Finset.sum_congr rfl
        intro i hi
        rw [finiteFoxStageGroupAlgebraDerivative_mul]
        rw [hgen_aug i, zero_smul, zero_add, hgen_derivative i]
    _ = finiteFoxCommutatorPowerGroupAlgebraMap (F := FreeGroup X) N n (a j) := by
        rw [Finset.sum_eq_single j]
        · simp only [Pi.single_eq_same, mul_one]
        · intro i _ hij
          rw [Pi.single_eq_of_ne hij.symm]
          simp only [mul_zero]
        · simp only [Finset.mem_univ, not_true_eq_false, Pi.single_eq_same, mul_one, IsEmpty.forall_iff]

/-- The source-boundary relation-ideal reduction is a theorem: if the source boundary of a lift is
in the relation ideal, differentiating that boundary gives the desired relation-boundary vector. -/
theorem finiteFoxStageSourceBoundaryRelationIdealReduction_of_relationIdeal_derivatives
    [Fintype X] :
    finiteFoxStageSourceBoundaryRelationIdealReduction (X := X) N n := by
  intro a ha
  have hderivative :=
    finiteFoxGADeriv_mem_relBoundarySubmodule_of_mem_relAugIdeal
      (X := X) N n (x := finiteFoxStageSourceFoxBoundary (X := X) N n a) ha
  rw [finiteFoxStageGroupAlgebraDerivativeVector_sourceFoxBoundary (X := X) N n a] at hderivative
  exact hderivative

/-- Finite-stage relation-boundary module exactness follows from differentiating the relation
augmentation ideal. -/
theorem finiteFoxStageRelationBoundaryModuleExact_of_relationIdeal_derivatives
    [Fintype X] :
    finiteFoxStageRelationBoundaryModuleExact (X := X) N n :=
  finiteFoxStageRelationBoundaryModuleExact_of_sourceBoundaryRelReduction
    (X := X) N n
    (finiteFoxStageSourceBoundaryRelationIdealReduction_of_relationIdeal_derivatives
      (X := X) N n)

/-- Finite-stage coordinate coverage follows from the relation-ideal derivative calculation. -/
theorem finiteFoxStageBoundaryCyclesCoveredBySourceKernel_of_relationIdeal_derivatives
    [Fintype X] :
    finiteFoxStageBoundaryCyclesCoveredBySourceKernel (X := X) N n :=
  finiteFoxStageBoundaryCyclesCoveredBySourceKernel_of_relationBoundaryModuleExact
    (X := X) N n
    (finiteFoxStageRelationBoundaryModuleExact_of_relationIdeal_derivatives (X := X) N n)

/-- Finite-stage semidirect coverage follows from the relation-ideal derivative calculation. -/
theorem finiteFoxStageSemiBoundaryCyclesCovered_of_relDeriv
    [Fintype X] :
    finiteFoxStageSemidirectBoundaryCyclesCoveredBySourceKernel (X := X) N n :=
  (finiteFoxStageSemidirectBoundaryCyclesCoveredBySourceKernel_iff (X := X) N n).2
    (finiteFoxStageBoundaryCyclesCoveredBySourceKernel_of_relationIdeal_derivatives
      (X := X) N n)

end

end FoxDifferential
