import FoxDifferential.Completed.FiniteStage.RelationAction

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/FoxDifferential/Completed/FiniteStage/RelationSubmodule.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Finite-stage relation-boundary submodule

The finite-stage relation boundary image is naturally an additive subgroup, because it comes from
`ker(F/[N,N]N^n -> F/N)`.  The finite Blanchfield--Lyndon statement is module-theoretic, so this
file packages the `Z/nZ[F/N]`-submodule generated by those relation-boundary vectors and separates
module-level exactness from the stronger set-level source-kernel coverage needed in the completed
density step.
-/

namespace FoxDifferential

noncomputable section

open ProCGroups.InverseSystems
open ProCGroups.ProC

universe u

variable {X : Type u} [DecidableEq X]
variable (N : Subgroup (FreeGroup X)) [N.Normal] (n : ℕ)

/-- The `Z/nZ[F/N]`-submodule generated by finite-stage relation-boundary vectors. -/
def finiteFoxStageRelationBoundarySubmodule :
    Submodule (finiteFoxStageTargetGroupAlgebra (X := X) N n)
      (finiteFoxStageCoordinateVector (X := X) N n) :=
  Submodule.span (finiteFoxStageTargetGroupAlgebra (X := X) N n)
    (finiteFoxStageRelationBoundaryRange (X := X) N n :
      Set (finiteFoxStageCoordinateVector (X := X) N n))

/-- Every actual relation-boundary vector lies in the generated relation-boundary submodule. -/
theorem finiteFoxStageRelationBoundaryRange_subset_relationBoundarySubmodule :
    (finiteFoxStageRelationBoundaryRange (X := X) N n :
      Set (finiteFoxStageCoordinateVector (X := X) N n)) ⊆
        finiteFoxStageRelationBoundarySubmodule (X := X) N n := by
  exact Submodule.subset_span

/-- A relation boundary of a finite-stage relation lies in the generated submodule. -/
theorem finiteFoxStageRelationBoundaryAddMonoidHom_mem_relationBoundarySubmodule
    (q : Additive (finiteFoxStageRelationGroup (X := X) N n)) :
    finiteFoxStageRelationBoundaryAddMonoidHom (X := X) N n q ∈
      finiteFoxStageRelationBoundarySubmodule (X := X) N n := by
  apply finiteFoxStageRelationBoundaryRange_subset_relationBoundarySubmodule (X := X) N n
  exact (mem_finiteFoxStageRelationBoundaryRange_iff (X := X) N n).2 ⟨q, rfl⟩

/-- The actual relation-boundary image is stable under arbitrary finite group-algebra scalars. -/
theorem finiteFoxStageRelationBoundaryRange_smul_mem
    (a : finiteFoxStageTargetGroupAlgebra (X := X) N n)
    {v : finiteFoxStageCoordinateVector (X := X) N n}
    (hv : v ∈ finiteFoxStageRelationBoundaryRange (X := X) N n) :
    a • v ∈ finiteFoxStageRelationBoundaryRange (X := X) N n := by
  classical
  refine MonoidAlgebra.induction_linear
    (M := finiteFoxStageTargetQuotient (X := X) N)
    (R := ModNCompletedCoeff n)
    (p := fun a : finiteFoxStageTargetGroupAlgebra (X := X) N n =>
      a • v ∈ finiteFoxStageRelationBoundaryRange (X := X) N n)
    a ?zero ?add ?single
  · simp only [zero_smul, zero_mem]
  · intro a b ha hb
    rw [add_smul]
    exact (finiteFoxStageRelationBoundaryRange (X := X) N n).add_mem ha hb
  · intro h c
    rcases ZMod.intCast_surjective c with ⟨m, rfl⟩
    have hbase :
        (MonoidAlgebra.of (ModNCompletedCoeff n)
            (finiteFoxStageTargetQuotient (X := X) N) h) • v ∈
          finiteFoxStageRelationBoundaryRange (X := X) N n :=
      finiteFoxStageRelationBoundaryRange_basis_smul_mem (X := X) N n h hv
    have hsingle :
        ((MonoidAlgebra.single h (m : ModNCompletedCoeff n) :
            finiteFoxStageTargetGroupAlgebra (X := X) N n) • v :
          finiteFoxStageCoordinateVector (X := X) N n) =
          (m : ℤ) •
            ((MonoidAlgebra.of (ModNCompletedCoeff n)
              (finiteFoxStageTargetQuotient (X := X) N) h) • v :
              finiteFoxStageCoordinateVector (X := X) N n) := by
      have hsingleAlg :
          (MonoidAlgebra.single h (m : ModNCompletedCoeff n) :
              finiteFoxStageTargetGroupAlgebra (X := X) N n) =
            (m : ModNCompletedCoeff n) •
              MonoidAlgebra.of (ModNCompletedCoeff n)
                (finiteFoxStageTargetQuotient (X := X) N) h := by
        simp only [MonoidAlgebra.of, MonoidHom.coe_mk, OneHom.coe_mk, MonoidAlgebra.smul_single, smul_eq_mul, mul_one]
      rw [hsingleAlg]
      rw [smul_assoc]
      exact Int.cast_smul_eq_zsmul (ModNCompletedCoeff n) m
        ((MonoidAlgebra.of (ModNCompletedCoeff n)
          (finiteFoxStageTargetQuotient (X := X) N) h) • v :
          finiteFoxStageCoordinateVector (X := X) N n)
    rw [hsingle]
    exact (finiteFoxStageRelationBoundaryRange (X := X) N n).zsmul_mem hbase m

/-- The actual relation-boundary image as a finite group-algebra submodule. -/
def finiteFoxStageRelationBoundaryImageSubmodule :
    Submodule (finiteFoxStageTargetGroupAlgebra (X := X) N n)
      (finiteFoxStageCoordinateVector (X := X) N n) where
  carrier := finiteFoxStageRelationBoundaryRange (X := X) N n
  zero_mem' := (finiteFoxStageRelationBoundaryRange (X := X) N n).zero_mem
  add_mem' := by
    intro x y hx hy
    exact (finiteFoxStageRelationBoundaryRange (X := X) N n).add_mem hx hy
  smul_mem' := by
    intro a v hv
    exact finiteFoxStageRelationBoundaryRange_smul_mem (X := X) N n a hv

@[simp]
theorem finiteFoxStageRelationBoundaryImageSubmodule_coe :
    ((finiteFoxStageRelationBoundaryImageSubmodule (X := X) N n :
        Submodule (finiteFoxStageTargetGroupAlgebra (X := X) N n)
          (finiteFoxStageCoordinateVector (X := X) N n)) :
          Set (finiteFoxStageCoordinateVector (X := X) N n)) =
      finiteFoxStageSourceKernelDerivativeSet (X := X) N n := by
  simp only [finiteFoxStageRelationBoundaryImageSubmodule, finiteFoxStageRelationBoundaryRange_coe,
  Submodule.coe_set_mk, AddSubmonoid.coe_set_mk, AddSubsemigroup.coe_set_mk]

/-- The generated relation-boundary submodule is the actual relation-boundary image, because the
image is already stable under the finite target group algebra. -/
theorem finiteFoxStageRelationBoundarySubmodule_eq_imageSubmodule :
    finiteFoxStageRelationBoundarySubmodule (X := X) N n =
      finiteFoxStageRelationBoundaryImageSubmodule (X := X) N n := by
  apply le_antisymm
  · refine Submodule.span_le.2 ?_
    intro v hv
    exact hv
  · intro v hv
    exact finiteFoxStageRelationBoundaryRange_subset_relationBoundarySubmodule (X := X) N n hv


/-- The relation-boundary submodule is contained in the finite Fox boundary cycles. -/
theorem finiteFoxStageRelationBoundarySubmodule_le_boundaryCycleSubmodule
    [Fintype X] :
    finiteFoxStageRelationBoundarySubmodule (X := X) N n ≤
      finiteFoxStageBoundaryCycleSubmodule (X := X) N n := by
  refine Submodule.span_le.2 ?_
  intro v hv
  exact finiteFoxStageRelationBoundary_range_le_boundaryCycleSubmodule (X := X) N n hv

/-- Module-level finite-stage exactness at the coordinate module:
`ker ∂` is contained in the submodule generated by finite relation boundaries. -/
def finiteFoxStageRelationBoundaryModuleExact [Fintype X] : Prop :=
  finiteFoxStageBoundaryCycleSubmodule (X := X) N n ≤
    finiteFoxStageRelationBoundarySubmodule (X := X) N n

/-- Function-level relation-boundary exactness implies the module-level finite exactness target. -/
theorem finiteFoxStageRelationBoundaryModuleExact_of_relationBoundaryExact
    [Fintype X]
    (hexact : finiteFoxStageRelationBoundaryExact (X := X) N n) :
    finiteFoxStageRelationBoundaryModuleExact (X := X) N n := by
  intro v hv
  have hcovered : finiteFoxStageBoundaryCyclesCoveredBySourceKernel (X := X) N n :=
    finiteFoxStageBoundaryCyclesCoveredBySourceKernel_of_relationBoundaryExact
      (X := X) N n hexact
  have hvsource : v ∈ finiteFoxStageSourceKernelDerivativeSet (X := X) N n :=
    hcovered hv
  have hvrange : v ∈ finiteFoxStageRelationBoundaryRange (X := X) N n := by
    change v ∈ finiteFoxStageSourceKernelDerivativeSet (X := X) N n
    exact hvsource
  exact finiteFoxStageRelationBoundaryRange_subset_relationBoundarySubmodule
    (X := X) N n hvrange

/-- The set-level finite coverage target implies the module-level finite exactness target. -/
theorem finiteFoxStageRelationBoundaryModuleExact_of_boundaryCyclesCoveredBySourceKernel
    [Fintype X]
    (hcovered : finiteFoxStageBoundaryCyclesCoveredBySourceKernel (X := X) N n) :
    finiteFoxStageRelationBoundaryModuleExact (X := X) N n := by
  intro v hv
  have hvsource : v ∈ finiteFoxStageSourceKernelDerivativeSet (X := X) N n := hcovered hv
  have hvrange : v ∈ finiteFoxStageRelationBoundaryRange (X := X) N n := by
    change v ∈ finiteFoxStageSourceKernelDerivativeSet (X := X) N n
    exact hvsource
  exact finiteFoxStageRelationBoundaryRange_subset_relationBoundarySubmodule
    (X := X) N n hvrange

/-- Module-level finite exactness is strong enough to recover the set-level source-kernel coverage,
because the relation-boundary image is already a finite group-algebra submodule. -/
theorem finiteFoxStageBoundaryCyclesCoveredBySourceKernel_of_relationBoundaryModuleExact
    [Fintype X]
    (hexact : finiteFoxStageRelationBoundaryModuleExact (X := X) N n) :
    finiteFoxStageBoundaryCyclesCoveredBySourceKernel (X := X) N n := by
  intro v hv
  have hvrel : v ∈ finiteFoxStageRelationBoundarySubmodule (X := X) N n := hexact hv
  rw [finiteFoxStageRelationBoundarySubmodule_eq_imageSubmodule (X := X) N n] at hvrel
  simpa [finiteFoxStageRelationBoundaryImageSubmodule] using hvrel


/-- Module exactness is equivalent to equality between `ker ∂` and the generated relation-boundary
submodule. -/
theorem finiteFoxStageRelationBoundaryModuleExact_iff_submodule_eq_boundaryCycleSubmodule
    [Fintype X] :
    finiteFoxStageRelationBoundaryModuleExact (X := X) N n ↔
      finiteFoxStageRelationBoundarySubmodule (X := X) N n =
        finiteFoxStageBoundaryCycleSubmodule (X := X) N n := by
  constructor
  · intro hexact
    exact le_antisymm
      (finiteFoxStageRelationBoundarySubmodule_le_boundaryCycleSubmodule (X := X) N n)
      hexact
  · intro h v hv
    rw [h]
    exact hv

/-- Function-level finite exactness identifies `ker ∂` with the generated relation-boundary
submodule. -/
theorem relationBoundarySubmodule_eq_boundaryCycleSubmodule_of_relExact
    [Fintype X]
    (hexact : finiteFoxStageRelationBoundaryExact (X := X) N n) :
    finiteFoxStageRelationBoundarySubmodule (X := X) N n =
      finiteFoxStageBoundaryCycleSubmodule (X := X) N n :=
  (finiteFoxStageRelationBoundaryModuleExact_iff_submodule_eq_boundaryCycleSubmodule
    (X := X) N n).1
    (finiteFoxStageRelationBoundaryModuleExact_of_relationBoundaryExact
      (X := X) N n hexact)

end

end FoxDifferential
