import FoxDifferential.Completed.FiniteStage.RelationIdealPrimitive

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/FoxDifferential/Completed/FiniteStage/SourceCycleReduction.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Source-cycle reduction for finite-stage Crowell exactness

This file isolates the exact remaining finite algebra problem into two independent statements.
First, relation-ideal boundary terms should have relation-compatible source primitives.  Second,
source boundary cycles should project to the relation-boundary submodule.  Together they imply the
source-boundary relation-ideal reduction used by `SourceBoundary.lean` and hence the finite-stage
coverage statement.
-/

namespace FoxDifferential

noncomputable section

open ProCGroups.InverseSystems
open ProCGroups.ProC

universe u

variable {X : Type u} [DecidableEq X]
variable (N : Subgroup (FreeGroup X)) [N.Normal] (n : ℕ)

/-- Source boundary cycles in the source coordinate module. -/
def finiteFoxStageSourceBoundaryCycleSubmodule [Fintype X] :
    Submodule (finiteFoxStageSourceGroupAlgebra (X := X) N n)
      (finiteFoxStageSourceCoordinateVector (X := X) N n) :=
  LinearMap.ker (finiteFoxStageSourceFoxBoundary (X := X) N n)

omit [DecidableEq X] [N.Normal] in
@[simp]
theorem mem_finiteFoxStageSourceBoundaryCycleSubmodule [Fintype X]
    {p : finiteFoxStageSourceCoordinateVector (X := X) N n} :
    p ∈ finiteFoxStageSourceBoundaryCycleSubmodule (X := X) N n ↔
      finiteFoxStageSourceFoxBoundary (X := X) N n p = 0 :=
  Iff.rfl

/-- Source-cycle projection exactness: every source Fox cycle maps to the target relation-boundary
submodule.  This is the source-quotient analogue of exactness before the relation-ideal
correction. -/
def finiteFoxStageSourceCycleProjectionExact [Fintype X] : Prop :=
  ∀ p : finiteFoxStageSourceCoordinateVector (X := X) N n,
    p ∈ finiteFoxStageSourceBoundaryCycleSubmodule (X := X) N n →
      finiteFoxStageCoordinateSourceToTarget (X := X) N n p ∈
        finiteFoxStageRelationBoundarySubmodule (X := X) N n

/-- Left-submodule version of the source-boundary reduction. -/
def finiteFoxStageSourceBoundaryLeftRelationReduction [Fintype X] : Prop :=
  ∀ a : finiteFoxStageSourceCoordinateVector (X := X) N n,
    finiteFoxStageSourceFoxBoundary (X := X) N n a ∈
      finiteFoxStageRelationAugmentationLeftSubmodule (X := X) N n →
      finiteFoxStageCoordinateSourceToTarget (X := X) N n a ∈
        finiteFoxStageRelationBoundarySubmodule (X := X) N n

/-- Source-cycle projection exactness implies the reduction for the left relation-augmentation
submodule, because elements of the left relation-augmentation submodule have explicit
relation-compatible primitives. -/
theorem finiteFoxStageSourceBoundaryLeftRelationReduction_of_sourceCycleProjectionExact
    [Fintype X]
    (hcycle : finiteFoxStageSourceCycleProjectionExact (X := X) N n) :
    finiteFoxStageSourceBoundaryLeftRelationReduction (X := X) N n := by
  intro a ha
  rcases finiteFoxStageSourceBoundaryPrimitive_of_mem_relationAugmentationLeftSubmodule
      (X := X) N n ha with ⟨p, hpboundary, hprel⟩
  have hcycle_ap :
      a - p ∈ finiteFoxStageSourceBoundaryCycleSubmodule (X := X) N n := by
    change finiteFoxStageSourceFoxBoundary (X := X) N n (a - p) = 0
    rw [map_sub, hpboundary]
    exact sub_self _
  have haprel := hcycle (a - p) hcycle_ap
  have hmap :
      finiteFoxStageCoordinateSourceToTarget (X := X) N n a =
        finiteFoxStageCoordinateSourceToTarget (X := X) N n p +
          finiteFoxStageCoordinateSourceToTarget (X := X) N n (a - p) := by
    have hsub := map_sub (finiteFoxStageCoordinateSourceToTarget (X := X) N n) a p
    calc
      finiteFoxStageCoordinateSourceToTarget (X := X) N n a =
          finiteFoxStageCoordinateSourceToTarget (X := X) N n p +
            (finiteFoxStageCoordinateSourceToTarget (X := X) N n a -
              finiteFoxStageCoordinateSourceToTarget (X := X) N n p) := by
            abel
      _ = finiteFoxStageCoordinateSourceToTarget (X := X) N n p +
            finiteFoxStageCoordinateSourceToTarget (X := X) N n (a - p) := by
            rw [← hsub]
  rw [hmap]
  exact (finiteFoxStageRelationBoundarySubmodule (X := X) N n).add_mem hprel haprel

/-- If the two-sided relation augmentation ideal is already generated by the same relation
augmentation elements as a left source-submodule, source-cycle projection exactness implies the
source-boundary relation-ideal reduction used in the finite-stage exactness file. -/
theorem finiteFoxStageSourceBoundaryRelationIdealReduction_of_relationIdeal_le_leftSubmodule
    [Fintype X]
    (hideal_left :
      ∀ x : finiteFoxStageSourceGroupAlgebra (X := X) N n,
        x ∈ finiteFoxStageRelationAugmentationIdeal (X := X) N n →
          x ∈ finiteFoxStageRelationAugmentationLeftSubmodule (X := X) N n)
    (hcycle : finiteFoxStageSourceCycleProjectionExact (X := X) N n) :
    finiteFoxStageSourceBoundaryRelationIdealReduction (X := X) N n := by
  intro a ha
  exact finiteFoxStageSourceBoundaryLeftRelationReduction_of_sourceCycleProjectionExact
    (X := X) N n hcycle a (hideal_left _ ha)

/-- Finite-stage source-cycle projection exactness gives relation-boundary module exactness. -/
theorem finiteFoxStageRelationBoundaryModuleExact_of_relIdealLeftGen_and_sourceCycleProjExact
    [Fintype X]
    (hideal_left :
      ∀ x : finiteFoxStageSourceGroupAlgebra (X := X) N n,
        x ∈ finiteFoxStageRelationAugmentationIdeal (X := X) N n →
          x ∈ finiteFoxStageRelationAugmentationLeftSubmodule (X := X) N n)
    (hcycle : finiteFoxStageSourceCycleProjectionExact (X := X) N n) :
    finiteFoxStageRelationBoundaryModuleExact (X := X) N n :=
  finiteFoxStageRelationBoundaryModuleExact_of_sourceBoundaryRelReduction
    (X := X) N n
    (finiteFoxStageSourceBoundaryRelationIdealReduction_of_relationIdeal_le_leftSubmodule
      (X := X) N n hideal_left hcycle)

/-- The same inputs give finite coordinate coverage. -/
theorem finiteFoxStageBoundaryCyclesCovered_of_relIdealLeftGen_and_sourceCycleProjExact
    [Fintype X]
    (hideal_left :
      ∀ x : finiteFoxStageSourceGroupAlgebra (X := X) N n,
        x ∈ finiteFoxStageRelationAugmentationIdeal (X := X) N n →
          x ∈ finiteFoxStageRelationAugmentationLeftSubmodule (X := X) N n)
    (hcycle : finiteFoxStageSourceCycleProjectionExact (X := X) N n) :
    finiteFoxStageBoundaryCyclesCoveredBySourceKernel (X := X) N n :=
  finiteFoxStageBoundaryCyclesCoveredBySourceKernel_of_relationBoundaryModuleExact
    (X := X) N n
    (finiteFoxStageRelationBoundaryModuleExact_of_relIdealLeftGen_and_sourceCycleProjExact
      (X := X) N n hideal_left hcycle)

/-- The same inputs give finite semidirect coverage. -/
theorem finiteFoxStageSemiBoundaryCyclesCovered_of_relIdealLeftGen_and_sourceCycleProjExact
    [Fintype X]
    (hideal_left :
      ∀ x : finiteFoxStageSourceGroupAlgebra (X := X) N n,
        x ∈ finiteFoxStageRelationAugmentationIdeal (X := X) N n →
          x ∈ finiteFoxStageRelationAugmentationLeftSubmodule (X := X) N n)
    (hcycle : finiteFoxStageSourceCycleProjectionExact (X := X) N n) :
    finiteFoxStageSemidirectBoundaryCyclesCoveredBySourceKernel (X := X) N n :=
  finiteFoxStageSemiBoundaryCyclesCovered_of_sourceBoundaryRelReduction
    (X := X) N n
    (finiteFoxStageSourceBoundaryRelationIdealReduction_of_relationIdeal_le_leftSubmodule
      (X := X) N n hideal_left hcycle)

end

end FoxDifferential
