import FoxDifferential.Completed.FiniteStage.RelationIdeal
import FoxDifferential.Completed.FiniteStage.BoundaryQuotient
import FoxDifferential.Completed.FiniteStage.SemidirectCycles

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/FoxDifferential/Completed/FiniteStage/SourceBoundary.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Source-coordinate lifts of finite Fox boundary cycles

This file adds the source-side coordinate layer needed for the finite-stage exactness attack.
A target cycle `v ∈ ker ∂` can be lifted coordinatewise to the source group algebra
`(Z/nZ)[F/([N,N]N^n)]`; its source Fox boundary then lies in the explicit relation augmentation
ideal generated by `q - 1` for finite-stage relations `q`.
-/

namespace FoxDifferential

noncomputable section

open ProCGroups.InverseSystems
open ProCGroups.ProC

universe u

variable {X : Type u} [DecidableEq X]
variable (N : Subgroup (FreeGroup X)) [N.Normal] (n : ℕ)

/-- Source-valued coordinate vectors over `(Z/nZ)[F/([N,N]N^n)]`. -/
abbrev finiteFoxStageSourceCoordinateVector : Type u :=
  X → finiteFoxStageSourceGroupAlgebra (X := X) N n

/-- The source Fox boundary/Euler map
`a ↦ Σ_i a_i([x_i]-1)` over the source quotient. -/
def finiteFoxStageSourceFoxBoundary [Fintype X] :
    finiteFoxStageSourceCoordinateVector (X := X) N n →ₗ[
      finiteFoxStageSourceGroupAlgebra (X := X) N n]
      finiteFoxStageSourceGroupAlgebra (X := X) N n where
  toFun v :=
    ∑ i : X,
      v i *
        (MonoidAlgebra.of (ModNCompletedCoeff n)
          (FreeGroup X ⧸ finiteFoxCommutatorPowerSubgroup (F := FreeGroup X) N n)
          (QuotientGroup.mk'
            (finiteFoxCommutatorPowerSubgroup (F := FreeGroup X) N n)
            (FreeGroup.of i)) - 1)
  map_add' := by
    intro v w
    simp only [Pi.add_apply, QuotientGroup.mk'_apply, MonoidAlgebra.of_apply, add_mul, Finset.sum_add_distrib]
  map_smul' := by
    intro r v
    simp only [Pi.smul_apply, smul_eq_mul, QuotientGroup.mk'_apply, MonoidAlgebra.of_apply, mul_assoc,
  RingHom.id_apply, Finset.mul_sum]

omit [DecidableEq X] [N.Normal] in
@[simp]
theorem finiteFoxStageSourceFoxBoundary_apply [Fintype X]
    (v : finiteFoxStageSourceCoordinateVector (X := X) N n) :
    finiteFoxStageSourceFoxBoundary (X := X) N n v =
      ∑ i : X,
        v i *
          (MonoidAlgebra.of (ModNCompletedCoeff n)
            (FreeGroup X ⧸ finiteFoxCommutatorPowerSubgroup (F := FreeGroup X) N n)
            (QuotientGroup.mk'
              (finiteFoxCommutatorPowerSubgroup (F := FreeGroup X) N n)
              (FreeGroup.of i)) - 1) :=
  rfl

/-- Apply the finite source-to-target group-algebra map coordinatewise. -/
def finiteFoxStageCoordinateSourceToTarget :
    finiteFoxStageSourceCoordinateVector (X := X) N n →ₗ[ModNCompletedCoeff n]
      finiteFoxStageCoordinateVector (X := X) N n where
  toFun v := fun i =>
    finiteFoxCommutatorPowerGroupAlgebraMap (F := FreeGroup X) N n (v i)
  map_add' := by
    intro v w
    funext i
    simp only [Pi.add_apply, map_add]
  map_smul' := by
    intro a v
    funext i
    simp only [Pi.smul_apply, finiteFoxCommutatorPowerGroupAlgebraMap_smul, RingHom.id_apply]

omit [DecidableEq X] in
@[simp]
theorem finiteFoxStageCoordinateSourceToTarget_apply
    (v : finiteFoxStageSourceCoordinateVector (X := X) N n) (i : X) :
    finiteFoxStageCoordinateSourceToTarget (X := X) N n v i =
      finiteFoxCommutatorPowerGroupAlgebraMap (F := FreeGroup X) N n (v i) :=
  rfl

omit [DecidableEq X] in
/-- The source boundary commutes with the source-to-target group-algebra map. -/
theorem finiteFoxStageFoxBoundary_coordinateSourceToTarget
    [Fintype X]
    (v : finiteFoxStageSourceCoordinateVector (X := X) N n) :
    finiteFoxStageFoxBoundary (X := X) N n
        (finiteFoxStageCoordinateSourceToTarget (X := X) N n v) =
      finiteFoxCommutatorPowerGroupAlgebraMap (F := FreeGroup X) N n
        (finiteFoxStageSourceFoxBoundary (X := X) N n v) := by
  rw [finiteFoxStageFoxBoundary_apply, finiteFoxStageSourceFoxBoundary_apply]
  rw [map_sum]
  apply Finset.sum_congr rfl
  intro i hi
  rw [finiteFoxStageCoordinateSourceToTarget_apply, RingHom.map_mul, map_sub, map_one,
    finiteFoxCommutatorPowerGroupAlgebraMap_of]

omit [DecidableEq X] in
/-- The coordinatewise source-to-target map is surjective. -/
theorem finiteFoxStageCoordinateSourceToTarget_surjective :
    Function.Surjective (finiteFoxStageCoordinateSourceToTarget (X := X) N n) := by
  intro v
  have hcoord : ∀ i : X,
      ∃ a : finiteFoxStageSourceGroupAlgebra (X := X) N n,
        finiteFoxCommutatorPowerGroupAlgebraMap (F := FreeGroup X) N n a = v i := by
    intro i
    exact finiteFoxCommutatorPowerGroupAlgebraMap_surjective (X := X) N n (v i)
  choose a ha using hcoord
  refine ⟨a, ?_⟩
  funext i
  exact ha i

omit [DecidableEq X] in
/-- If a source coordinate vector lifts a target boundary cycle, then its source boundary lies in
 the source-to-target group-algebra kernel. -/
theorem finiteFoxStageSourceFoxBoundary_mem_groupAlgebraMapKernel_of_lift_cycle
    [Fintype X]
    {v : finiteFoxStageCoordinateVector (X := X) N n}
    {a : finiteFoxStageSourceCoordinateVector (X := X) N n}
    (ha : finiteFoxStageCoordinateSourceToTarget (X := X) N n a = v)
    (hv : v ∈ finiteFoxStageBoundaryCycleSubmodule (X := X) N n) :
    finiteFoxStageSourceFoxBoundary (X := X) N n a ∈
      finiteFoxStageGroupAlgebraMapKernelIdeal (X := X) N n := by
  rw [mem_finiteFoxStageGroupAlgebraMapKernelIdeal]
  calc
    finiteFoxCommutatorPowerGroupAlgebraMap (F := FreeGroup X) N n
        (finiteFoxStageSourceFoxBoundary (X := X) N n a) =
      finiteFoxStageFoxBoundary (X := X) N n
        (finiteFoxStageCoordinateSourceToTarget (X := X) N n a) := by
        exact (finiteFoxStageFoxBoundary_coordinateSourceToTarget (X := X) N n a).symm
    _ = finiteFoxStageFoxBoundary (X := X) N n v := by
        rw [ha]
    _ = 0 := hv

omit [DecidableEq X] in
/-- If a source coordinate vector lifts a target boundary cycle, then its source boundary lies in
 the explicit relation augmentation ideal. -/
theorem finiteFoxStageSourceFoxBoundary_mem_relationAugmentationIdeal_of_lift_cycle
    [Fintype X]
    {v : finiteFoxStageCoordinateVector (X := X) N n}
    {a : finiteFoxStageSourceCoordinateVector (X := X) N n}
    (ha : finiteFoxStageCoordinateSourceToTarget (X := X) N n a = v)
    (hv : v ∈ finiteFoxStageBoundaryCycleSubmodule (X := X) N n) :
    finiteFoxStageSourceFoxBoundary (X := X) N n a ∈
      finiteFoxStageRelationAugmentationIdeal (X := X) N n := by
  rw [← finiteFoxStage_mem_groupAlgebraMapKernelIdeal_iff_relationAugmentationIdeal (X := X) N n]
  exact finiteFoxStageSourceFoxBoundary_mem_groupAlgebraMapKernel_of_lift_cycle
    (X := X) N n ha hv

omit [DecidableEq X] in
/-- Every finite target boundary cycle has a source-coordinate lift whose source boundary is in the
relation augmentation ideal. -/
theorem exists_finiteFoxStageSourceCoordinate_lift_boundaryCycle_relationIdeal
    [Fintype X]
    (v : finiteFoxStageCoordinateVector (X := X) N n)
    (hv : v ∈ finiteFoxStageBoundaryCycleSubmodule (X := X) N n) :
    ∃ a : finiteFoxStageSourceCoordinateVector (X := X) N n,
      finiteFoxStageCoordinateSourceToTarget (X := X) N n a = v ∧
        finiteFoxStageSourceFoxBoundary (X := X) N n a ∈
          finiteFoxStageRelationAugmentationIdeal (X := X) N n := by
  rcases finiteFoxStageCoordinateSourceToTarget_surjective (X := X) N n v with ⟨a, ha⟩
  exact ⟨a, ha,
    finiteFoxStageSourceFoxBoundary_mem_relationAugmentationIdeal_of_lift_cycle
      (X := X) N n ha hv⟩

/-- Source-boundary relation-ideal reduction: if every source coordinate vector whose source
boundary lies in the relation augmentation ideal projects to a relation-boundary vector, then the
finite-stage coordinate complex is exact. -/
def finiteFoxStageSourceBoundaryRelationIdealReduction [Fintype X] : Prop :=
  ∀ a : finiteFoxStageSourceCoordinateVector (X := X) N n,
    finiteFoxStageSourceFoxBoundary (X := X) N n a ∈
      finiteFoxStageRelationAugmentationIdeal (X := X) N n →
      finiteFoxStageCoordinateSourceToTarget (X := X) N n a ∈
        finiteFoxStageRelationBoundarySubmodule (X := X) N n

/-- The source-boundary relation-ideal reduction implies finite-stage module exactness. -/
theorem finiteFoxStageRelationBoundaryModuleExact_of_sourceBoundaryRelReduction
    [Fintype X]
    (hreduce : finiteFoxStageSourceBoundaryRelationIdealReduction (X := X) N n) :
    finiteFoxStageRelationBoundaryModuleExact (X := X) N n := by
  intro v hv
  rcases exists_finiteFoxStageSourceCoordinate_lift_boundaryCycle_relationIdeal
      (X := X) N n v hv with ⟨a, ha, hboundary⟩
  have hrel := hreduce a hboundary
  simpa [ha] using hrel

/-- The source-boundary relation-ideal reduction implies finite-stage coordinate coverage. -/
theorem finiteFoxStageBoundaryCyclesCovered_of_sourceBoundaryRelReduction
    [Fintype X]
    (hreduce : finiteFoxStageSourceBoundaryRelationIdealReduction (X := X) N n) :
    finiteFoxStageBoundaryCyclesCoveredBySourceKernel (X := X) N n :=
  finiteFoxStageBoundaryCyclesCoveredBySourceKernel_of_relationBoundaryModuleExact
    (X := X) N n
    (finiteFoxStageRelationBoundaryModuleExact_of_sourceBoundaryRelReduction
      (X := X) N n hreduce)

/-- The source-boundary relation-ideal reduction gives injectivity of the finite quotient
obstruction boundary. -/
theorem finiteFoxStageBoundaryModuloRelations_inj_of_sourceBoundaryRelReduction
    [Fintype X]
    (hreduce : finiteFoxStageSourceBoundaryRelationIdealReduction (X := X) N n) :
    Function.Injective (finiteFoxStageBoundaryModuloRelations (X := X) N n) :=
  finiteFoxStageBoundaryModuloRelations_injective_of_relationBoundaryModuleExact
    (X := X) N n
    (finiteFoxStageRelationBoundaryModuleExact_of_sourceBoundaryRelReduction
      (X := X) N n hreduce)

/-- The source-boundary relation-ideal reduction gives the finite semidirect coverage statement. -/
theorem finiteFoxStageSemiBoundaryCyclesCovered_of_sourceBoundaryRelReduction
    [Fintype X]
    (hreduce : finiteFoxStageSourceBoundaryRelationIdealReduction (X := X) N n) :
    finiteFoxStageSemidirectBoundaryCyclesCoveredBySourceKernel (X := X) N n :=
  (finiteFoxStageSemidirectBoundaryCyclesCoveredBySourceKernel_iff (X := X) N n).2
    (finiteFoxStageBoundaryCyclesCovered_of_sourceBoundaryRelReduction
      (X := X) N n hreduce)

end

end FoxDifferential
