import CrowellExactSequence.Profinite.ContinuousMagnus.Injectivity
import CrowellExactSequence.Profinite.SequenceMaps
import CrowellExactSequence.Profinite.Exactness

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/CrowellExactSequence/Profinite/FreeExactness.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Free pro-C Crowell exactness over pro-C integer coefficients

The public route is the paper sequence

```text
N^ab(C) -> A_psi(C) -> Z_C[[H]] -> Z_C.
```

This file only assembles the displayed maps.  Injectivity of `d_N`, exactness at `A_psi(C)`, and
exactness at `Z_C[[H]]` are the paper obligations.  For a finite free presentation, exactness at
`Z_C[[H]]` can be derived from surjectivity of `psi`.
-/

namespace CrowellExactSequence

noncomputable section

open FoxDifferential
open ProCGroups.ProC

universe u

variable {H : Type u} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
variable {ProC : ProCGroupPredicate.{u}}

variable [ProCGroups.FiniteGroupClass.ContainsTrivialQuotients ProC.finiteQuotientClass]

/-- Free pro-`C` exactness at `Z_C[[H]]`, supplied by a finite free basis and surjectivity of
`psi`. -/
theorem freeProC_presentedCrowellGroupAlgebraExactProCInteger_of_psi_surjective
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi) :
    Function.Exact
      (presentedCompletedDifferentialToCompletedGroupAlgebraProCInteger
        (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi)
      (zcCompletedGroupAlgebraAugmentation ProC.finiteQuotientClass H) := by
  letI : Fact (ProCGroups.FiniteGroupClass.FiniteOnly ProC.finiteQuotientClass) :=
    ⟨by
      intro Q _ hQ
      exact ProCGroupPredicate.finiteQuotientFinite ProC hQ⟩
  let family : Fin r → sourceData.carrier :=
    freeProCChosenFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  have htargetGen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := H) (Set.range (fun i : Fin r => psi (family i))) := by
    simpa [family] using
      freeProCChosenFamilyOfBasisCard_image_generates_of_surjective
        (ProC := ProC) sourceData hbasis psi hpsi
  exact
    exact_presentedCompletedToZC_of_boundary_family_topologicallyGenerates
      (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass
      (ProCGroupPredicate.finiteQuotientFormation ProC) psi family htargetGen

/-- Free pro-`C` exactness at `Z_C[[H]]` for the separated middle term, supplied by a finite
free basis and surjectivity of `psi`. -/
theorem freeProC_presentedSeparatedCrowellGroupAlgebraExactProCInteger_of_psi_surjective
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi) :
    Function.Exact
      (presentedSeparatedDifferentialToCompletedGroupAlgebraProCInteger
        (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass
        (ProCGroupPredicate.finiteQuotientHereditary ProC) psi)
      (zcCompletedGroupAlgebraAugmentation ProC.finiteQuotientClass H) := by
  letI : Fact (ProCGroups.FiniteGroupClass.FiniteOnly ProC.finiteQuotientClass) :=
    ⟨by
      intro Q _ hQ
      exact ProCGroupPredicate.finiteQuotientFinite ProC hQ⟩
  let family : Fin r → sourceData.carrier :=
    freeProCChosenFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  have htargetGen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := H) (Set.range (fun i : Fin r => psi (family i))) := by
    simpa [family] using
      freeProCChosenFamilyOfBasisCard_image_generates_of_surjective
        (ProC := ProC) sourceData hbasis psi hpsi
  exact
    exact_presentedSepToZC_of_boundary_family_topologicallyGenerates
      (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass
      (ProCGroupPredicate.finiteQuotientHereditary ProC)
      (ProCGroupPredicate.finiteQuotientFormation ProC) psi family htargetGen

omit [ProCGroups.FiniteGroupClass.ContainsTrivialQuotients ProC.finiteQuotientClass] in
/-- The closed subgroup generated by the completed Fox graph of a finite free pro-`C` basis is
pro-`C`.  The only target-side input is surjectivity of `psi`; it makes `H` a pro-`C` group, and
the ambient semidirect product is then pro-`C` by the right-projection exact sequence. -/
theorem freeProCClosedGeneratedTarget_proC_of_surjective
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.HasFiniteQuotientHereditary] [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi) :
    ProC
      (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC)
          (fun i : ULift.{u} (Fin r) =>
            psi (freeProCChosenULiftFamilyOfBasisCard
              (ProC := ProC) sourceData hbasis i)) : Subgroup
            (ZCCompletedFoxSemidirect
              ProC.finiteQuotientClass (ULift.{u} (Fin r)) H))) := by
  let family : ULift.{u} (Fin r) → sourceData.carrier :=
    freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  letI : ProCGroup ProC H :=
    ProCGroup.of_surjective (G := sourceData.carrier) ProC psi hpsi
  letI : ProCGroup ProC
      (ZCCompletedFoxSemidirect ProC.finiteQuotientClass (ULift.{u} (Fin r)) H) :=
    FoxDifferential.proCGroup_zcCompletedFoxSemidirect
      (X := ULift.{u} (Fin r)) (H := H) ProC
  simpa [family] using
    FoxDifferential.freeProCZCCompletedFoxSemidirectClosedGeneratedTarget_proC
      (ProC := ProC)
      (fun i : ULift.{u} (Fin r) => psi (family i))

omit [ProC.finiteQuotientClass.ContainsTrivialQuotients] in
/-- Free pro-`C` finite-stage separation of `A_psi(C)` from the relation-reflection form of the
finite source/target/coefficient reductions.  The remaining mathematical content is precisely the
reflection hypothesis. -/
theorem freeProC_zcDiffModuleStageProjsSeparate_of_finiteRelationReductionsReflectRelations
    (sourceData : FreeProCSourceData ProC)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hreflect :
      zcCompletedDifferentialModuleFiniteRelationReductionsReflectRelations
        ProC.finiteQuotientClass psi.toMonoidHom) :
    zcCompletedDifferentialModuleStageProjectionsSeparate
      ProC.finiteQuotientClass psi.toMonoidHom :=
  zcDiffModuleStageProjsSeparate_of_preStageProjsSeparate
    ProC.finiteQuotientClass psi.toMonoidHom
    ((zcDiffModulePreStageProjsSeparate_iff_finiteRelationReductionsReflectRelations
      ProC.finiteQuotientClass psi.toMonoidHom).2 hreflect)

omit [ProC.finiteQuotientClass.ContainsTrivialQuotients] in
/-- Free pro-`C` Hausdorffness of the finite-stage completed topology on `A_psi(C)`, reduced to
the relation-reflection form of finite-stage separation. -/
theorem freeProC_t2Space_zcDiffModuleNaturalTopology_of_finiteRelationReductionsReflectRelations
    (sourceData : FreeProCSourceData ProC)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hreflect :
      zcCompletedDifferentialModuleFiniteRelationReductionsReflectRelations
        ProC.finiteQuotientClass psi.toMonoidHom) :
    @T2Space
      (ZCCompletedDifferentialModule ProC.finiteQuotientClass psi.toMonoidHom)
      (zcCompletedDifferentialModuleNaturalTopology
        ProC.finiteQuotientClass psi.toMonoidHom) :=
  t2Space_zcCompletedDifferentialModuleNaturalTopology_of_separating
    ProC.finiteQuotientClass psi.toMonoidHom
    (freeProC_zcDiffModuleStageProjsSeparate_of_finiteRelationReductionsReflectRelations
      (H := H) (ProC := ProC) sourceData psi hreflect)

/-- Free pro-`C` finite-stage separation of `A_psi(C)`, reduced to closedness of the completed
crossed-differential relation submodule in the finite-stage topology on the pre-module. -/
theorem freeProC_zcDiffModuleStageProjsSeparate_of_relSubmoduleClosed
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientHereditary]
    (sourceData : FreeProCSourceData ProC)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hclosed :
      zcCompletedDifferentialModuleRelationSubmoduleClosed
        ProC.finiteQuotientClass psi.toMonoidHom) :
    zcCompletedDifferentialModuleStageProjectionsSeparate
      ProC.finiteQuotientClass psi.toMonoidHom := by
  letI :
      Nonempty
        (ZCCompletedDifferentialModuleIndex
          ProC.finiteQuotientClass psi.toMonoidHom) :=
    ⟨zcCompletedDifferentialModuleComapIndex
      (C := ProC.finiteQuotientClass) (G := sourceData.carrier) (H := H)
      (ProCGroupPredicate.finiteQuotientHereditary ProC) psi
      ((ProCGroups.Completion.ProCIntegerIndex.terminal
          (C := ProC.finiteQuotientClass) inferInstance),
        zcCompletedGroupAlgebraTopIndex ProC.finiteQuotientClass H)⟩
  have hdir :
      Directed (· ≤ ·)
        (id :
          ZCCompletedDifferentialModuleIndex
              ProC.finiteQuotientClass psi.toMonoidHom →
            ZCCompletedDifferentialModuleIndex
              ProC.finiteQuotientClass psi.toMonoidHom) :=
    directed_zcCompletedDifferentialModuleIndex
      (C := ProC.finiteQuotientClass) (G := sourceData.carrier) (H := H)
      (ProCGroupPredicate.finiteQuotientFormation ProC)
      (ProCGroupPredicate.finiteQuotientHereditary ProC) psi
  exact
    freeProC_zcDiffModuleStageProjsSeparate_of_finiteRelationReductionsReflectRelations
      (H := H) (ProC := ProC) sourceData psi
      (zcDiffModuleFiniteRelationReductionsReflectRelations_of_relSubmoduleClosed
        ProC.finiteQuotientClass psi.toMonoidHom hdir hclosed)

/-- Free pro-`C` Hausdorffness of the finite-stage completed topology on `A_psi(C)`, reduced to
closedness of the completed crossed-differential relation submodule in the finite-stage
pre-module topology. -/
theorem freeProC_t2Space_zcDiffModuleNaturalTopology_of_relSubmoduleClosed
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientHereditary]
    (sourceData : FreeProCSourceData ProC)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hclosed :
      zcCompletedDifferentialModuleRelationSubmoduleClosed
        ProC.finiteQuotientClass psi.toMonoidHom) :
    @T2Space
      (ZCCompletedDifferentialModule ProC.finiteQuotientClass psi.toMonoidHom)
      (zcCompletedDifferentialModuleNaturalTopology
        ProC.finiteQuotientClass psi.toMonoidHom) :=
  t2Space_zcCompletedDifferentialModuleNaturalTopology_of_separating
    ProC.finiteQuotientClass psi.toMonoidHom
    (freeProC_zcDiffModuleStageProjsSeparate_of_relSubmoduleClosed
      (H := H) (ProC := ProC) sourceData psi hclosed)

omit [ProCGroups.FiniteGroupClass.ContainsTrivialQuotients ProC.finiteQuotientClass] in
/-- For a free pro-`C` source, the current finite-stage separation target is exactly the
closedness of the completed crossed-differential relation submodule in the finite-stage
pre-module topology. -/
theorem freeProC_zcDiffModuleRelSubmoduleClosed_iff_stageProjsSeparate
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientHereditary]
    (sourceData : FreeProCSourceData ProC)
    (psi : ContinuousMonoidHom sourceData.carrier H) :
    zcCompletedDifferentialModuleRelationSubmoduleClosed
        ProC.finiteQuotientClass psi.toMonoidHom ↔
      zcCompletedDifferentialModuleStageProjectionsSeparate
        ProC.finiteQuotientClass psi.toMonoidHom := by
  letI :
      Nonempty
        (ZCCompletedDifferentialModuleIndex
          ProC.finiteQuotientClass psi.toMonoidHom) :=
    ⟨zcCompletedDifferentialModuleComapIndex
      (C := ProC.finiteQuotientClass) (G := sourceData.carrier) (H := H)
      (ProCGroupPredicate.finiteQuotientHereditary ProC) psi
      ((ProCGroups.Completion.ProCIntegerIndex.terminal
          (C := ProC.finiteQuotientClass) inferInstance),
        zcCompletedGroupAlgebraTopIndex ProC.finiteQuotientClass H)⟩
  have hdir :
      Directed (· ≤ ·)
        (id :
          ZCCompletedDifferentialModuleIndex
              ProC.finiteQuotientClass psi.toMonoidHom →
            ZCCompletedDifferentialModuleIndex
              ProC.finiteQuotientClass psi.toMonoidHom) :=
    directed_zcCompletedDifferentialModuleIndex
      (C := ProC.finiteQuotientClass) (G := sourceData.carrier) (H := H)
      (ProCGroupPredicate.finiteQuotientFormation ProC)
      (ProCGroupPredicate.finiteQuotientHereditary ProC) psi
  exact
    zcDiffModuleRelSubmoduleClosed_iff_stageProjsSeparate
      ProC.finiteQuotientClass psi.toMonoidHom hdir

omit [ProCGroups.FiniteGroupClass.ContainsTrivialQuotients ProC.finiteQuotientClass] in
/-- For a free pro-`C` source, closedness of the completed crossed-differential relation
submodule is equivalent to Hausdorffness of the finite-stage natural topology on the algebraic
module `A_psi(C)`.

This is the free-source formulation of the separation frontier: proving `A_psi(C)` is separated
for the finite-stage natural topology is exactly the same remaining task as proving relation
submodule closedness. -/
theorem freeProC_zcDiffModuleRelSubmoduleClosed_iff_t2_naturalTopology
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientHereditary]
    (sourceData : FreeProCSourceData ProC)
    (psi : ContinuousMonoidHom sourceData.carrier H) :
    zcCompletedDifferentialModuleRelationSubmoduleClosed
        ProC.finiteQuotientClass psi.toMonoidHom ↔
      @T2Space
        (ZCCompletedDifferentialModule ProC.finiteQuotientClass psi.toMonoidHom)
        (zcCompletedDifferentialModuleNaturalTopology
          ProC.finiteQuotientClass psi.toMonoidHom) := by
  letI :
      Nonempty
        (ZCCompletedDifferentialModuleIndex
          ProC.finiteQuotientClass psi.toMonoidHom) :=
    ⟨zcCompletedDifferentialModuleComapIndex
      (C := ProC.finiteQuotientClass) (G := sourceData.carrier) (H := H)
      (ProCGroupPredicate.finiteQuotientHereditary ProC) psi
      ((ProCGroups.Completion.ProCIntegerIndex.terminal
          (C := ProC.finiteQuotientClass) inferInstance),
        zcCompletedGroupAlgebraTopIndex ProC.finiteQuotientClass H)⟩
  have hdir :
      Directed (· ≤ ·)
        (id :
          ZCCompletedDifferentialModuleIndex
              ProC.finiteQuotientClass psi.toMonoidHom →
            ZCCompletedDifferentialModuleIndex
              ProC.finiteQuotientClass psi.toMonoidHom) :=
    directed_zcCompletedDifferentialModuleIndex
      (C := ProC.finiteQuotientClass) (G := sourceData.carrier) (H := H)
      (ProCGroupPredicate.finiteQuotientFormation ProC)
      (ProCGroupPredicate.finiteQuotientHereditary ProC) psi
  exact
    zcCompletedDifferentialModuleRelationSubmoduleClosed_iff_t2_naturalTopology
      ProC.finiteQuotientClass psi.toMonoidHom hdir

omit [ProC.finiteQuotientClass.ContainsTrivialQuotients] in
/-- The closed-generated module expansion used in the free finite-basis route is continuous for
the finite-stage completed topology on `A_psi(C)`. -/
theorem freeProC_hmodule_continuous_naturalTopology
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi) :
    @Continuous sourceData.carrier
      (ZCCompletedDifferentialModule ProC.finiteQuotientClass psi.toMonoidHom)
      inferInstance
      (zcCompletedDifferentialModuleNaturalTopology
        ProC.finiteQuotientClass psi.toMonoidHom)
      (fun g : sourceData.carrier =>
        presentedCompletedDifferentialFamilyMapProCInteger
          (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
          (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis)
          (freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
            (ProC := ProC)
            (freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis)
            (fun i : ULift.{u} (Fin r) =>
              psi (freeProCChosenULiftFamilyOfBasisCard
                (ProC := ProC) sourceData hbasis i))
            (freeProCClosedGeneratedTarget_proC_of_surjective
              (H := H) (ProC := ProC) sourceData hbasis psi hpsi)
            (freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
              (ProC := ProC)
              (fun i : ULift.{u} (Fin r) =>
                psi (freeProCChosenULiftFamilyOfBasisCard
                  (ProC := ProC) sourceData hbasis i)))
            g)) := by
  let family : ULift.{u} (Fin r) → sourceData.carrier :=
    freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  let hfree :=
    freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis
  let htarget :=
    freeProCClosedGeneratedTarget_proC_of_surjective
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi
  let hφconv :=
    freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
      (ProC := ProC) (fun i : ULift.{u} (Fin r) => psi (family i))
  simpa [family, hfree, htarget, hφconv] using
    continuous_closedGenerated_module_expansion_naturalTopology
      (G := sourceData.carrier) (H := H) ProC psi family hfree htarget hφconv

/-- The closed-generated coordinate map for the chosen finite free pro-`C` basis. -/
def freeProCChosenULift_closedGeneratedCoordinateMap
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi) :
    ZCCompletedDifferentialModule ProC.finiteQuotientClass psi.toMonoidHom →ₗ[
      ZCCompletedGroupAlgebra ProC.finiteQuotientClass H]
      ZCFreeFoxCoordinates ProC.finiteQuotientClass
        (X := ULift.{u} (Fin r)) (H := H) := by
  letI : Fact (ProCGroups.FiniteGroupClass.FiniteOnly ProC.finiteQuotientClass) :=
    ⟨by
      intro Q _ hQ
      exact ProCGroupPredicate.finiteQuotientFinite ProC hQ⟩
  let family : ULift.{u} (Fin r) → sourceData.carrier :=
    freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  let hfree :=
    freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis
  let htarget :=
    freeProCClosedGeneratedTarget_proC_of_surjective
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi
  let hφconv :=
    freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
      (ProC := ProC) (fun i : ULift.{u} (Fin r) => psi (family i))
  have hH : ProC (G := H) :=
    (ProCGroup.of_surjective (G := sourceData.carrier) ProC psi hpsi).isProC
  have hφHconv :
      ProCGroups.FreeProC.FamilyConvergesToOne
        (G := H) (fun i : ULift.{u} (Fin r) => psi (family i)) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_convergesToOne
        (ProC := ProC) sourceData hbasis psi.toMonoidHom
  have hφHgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := H) (Set.range (fun i : ULift.{u} (Fin r) => psi (family i))) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_generates_of_surjective
        (ProC := ProC) sourceData hbasis psi hpsi
  exact
    closedGeneratedDerivativeCoordinatesLinearMapProCInteger
      (G := sourceData.carrier) (H := H) ProC psi family hfree htarget hφconv
      hH hφHconv hφHgen

/-- The separated finite-family map for the chosen finite free pro-`C` basis. -/
def freeProCChosenULift_sepFamilyMap
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H) :
    ZCFreeFoxCoordinates ProC.finiteQuotientClass
        (X := ULift.{u} (Fin r)) (H := H) →ₗ[
      ZCCompletedGroupAlgebra ProC.finiteQuotientClass H]
      ZCSeparatedCompletedDifferentialModule
        ProC.finiteQuotientClass psi.toMonoidHom :=
  presentedSeparatedDifferentialFamilyMapProCInteger
    (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
    (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis)

omit [ProC.finiteQuotientClass.ContainsTrivialQuotients] in
/-- On a basis vector, the separated finite-family map is the separated universal
differential of the corresponding chosen free generator. -/
@[simp 900]
theorem freeProCChosenULift_sepFamilyMap_single
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (i : ULift.{u} (Fin r)) :
    freeProCChosenULift_sepFamilyMap
        (H := H) (ProC := ProC) sourceData hbasis psi
        (Pi.single i (1 : ZCCompletedGroupAlgebra ProC.finiteQuotientClass H)) =
      zcSeparatedUniversalDifferential
        ProC.finiteQuotientClass psi.toMonoidHom
        (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis i) := by
  exact
    presentedSeparatedDifferentialFamilyMapProCInteger_single
      (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
      (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis) i

/-- The separated closed-generated coordinate map for the chosen finite free pro-`C` basis. -/
def freeProCChosenULift_sepCoordinateMap
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    [T1Space
      (ZCFreeFoxCoordinates ProC.finiteQuotientClass
        (X := ULift.{u} (Fin r)) (H := H))] :
    ZCSeparatedCompletedDifferentialModule
        ProC.finiteQuotientClass psi.toMonoidHom →ₗ[
      ZCCompletedGroupAlgebra ProC.finiteQuotientClass H]
      ZCFreeFoxCoordinates ProC.finiteQuotientClass
        (X := ULift.{u} (Fin r)) (H := H) := by
  letI : Fact (ProCGroups.FiniteGroupClass.FiniteOnly ProC.finiteQuotientClass) :=
    ⟨by
      intro Q _ hQ
      exact ProCGroupPredicate.finiteQuotientFinite ProC hQ⟩
  letI :
      Nonempty
        (ZCCompletedDifferentialModuleIndex
          ProC.finiteQuotientClass psi.toMonoidHom) :=
    ⟨zcCompletedDifferentialModuleComapIndex
      (C := ProC.finiteQuotientClass) (G := sourceData.carrier) (H := H)
      (ProCGroupPredicate.finiteQuotientHereditary ProC) psi
      ((ProCGroups.Completion.ProCIntegerIndex.terminal
          (C := ProC.finiteQuotientClass) inferInstance),
        zcCompletedGroupAlgebraTopIndex ProC.finiteQuotientClass H)⟩
  have hdir :
      Directed (· ≤ ·)
        (id :
          ZCCompletedDifferentialModuleIndex
              ProC.finiteQuotientClass psi.toMonoidHom →
            ZCCompletedDifferentialModuleIndex
              ProC.finiteQuotientClass psi.toMonoidHom) :=
    directed_zcCompletedDifferentialModuleIndex
      (C := ProC.finiteQuotientClass) (G := sourceData.carrier) (H := H)
      (ProCGroupPredicate.finiteQuotientFormation ProC)
      (ProCGroupPredicate.finiteQuotientHereditary ProC) psi
  let family : ULift.{u} (Fin r) → sourceData.carrier :=
    freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  let hfree :=
    freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis
  let htarget :=
    freeProCClosedGeneratedTarget_proC_of_surjective
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi
  let hφconv :=
    freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
      (ProC := ProC) (fun i : ULift.{u} (Fin r) => psi (family i))
  have hH : ProC (G := H) :=
    (ProCGroup.of_surjective (G := sourceData.carrier) ProC psi hpsi).isProC
  have hφHconv :
      ProCGroups.FreeProC.FamilyConvergesToOne
        (G := H) (fun i : ULift.{u} (Fin r) => psi (family i)) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_convergesToOne
        (ProC := ProC) sourceData hbasis psi.toMonoidHom
  have hφHgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := H) (Set.range (fun i : ULift.{u} (Fin r) => psi (family i))) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_generates_of_surjective
        (ProC := ProC) sourceData hbasis psi hpsi
  exact
    separatedClosedGeneratedDerivativeCoordinatesLinearMapProCInteger
      (G := sourceData.carrier) (H := H) ProC psi family hfree htarget hφconv
      hdir sourceData.proCGroup.isProCGroup hH hφHconv hφHgen

/-- The separated coordinate map sends the separated universal differential to
the closed-generated Fox derivative vector. -/
@[simp 900]
theorem freeProCChosenULift_sepCoordinateMap_universal
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    [T1Space
      (ZCFreeFoxCoordinates ProC.finiteQuotientClass
        (X := ULift.{u} (Fin r)) (H := H))]
    (g : sourceData.carrier) :
    freeProCChosenULift_sepCoordinateMap
        (H := H) (ProC := ProC) sourceData hbasis psi hpsi
        (zcSeparatedUniversalDifferential
          ProC.finiteQuotientClass psi.toMonoidHom g) =
      freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
        (ProC := ProC)
        (freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis)
        (fun i : ULift.{u} (Fin r) =>
          psi (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis i))
        (freeProCClosedGeneratedTarget_proC_of_surjective
          (H := H) (ProC := ProC) sourceData hbasis psi hpsi)
        (freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
          (ProC := ProC)
          (fun i : ULift.{u} (Fin r) =>
            psi (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis i)))
        g := by
  letI : Fact (ProCGroups.FiniteGroupClass.FiniteOnly ProC.finiteQuotientClass) :=
    ⟨by
      intro Q _ hQ
      exact ProCGroupPredicate.finiteQuotientFinite ProC hQ⟩
  letI :
      Nonempty
        (ZCCompletedDifferentialModuleIndex
          ProC.finiteQuotientClass psi.toMonoidHom) :=
    ⟨zcCompletedDifferentialModuleComapIndex
      (C := ProC.finiteQuotientClass) (G := sourceData.carrier) (H := H)
      (ProCGroupPredicate.finiteQuotientHereditary ProC) psi
      ((ProCGroups.Completion.ProCIntegerIndex.terminal
          (C := ProC.finiteQuotientClass) inferInstance),
        zcCompletedGroupAlgebraTopIndex ProC.finiteQuotientClass H)⟩
  have hdir :
      Directed (· ≤ ·)
        (id :
          ZCCompletedDifferentialModuleIndex
              ProC.finiteQuotientClass psi.toMonoidHom →
            ZCCompletedDifferentialModuleIndex
              ProC.finiteQuotientClass psi.toMonoidHom) :=
    directed_zcCompletedDifferentialModuleIndex
      (C := ProC.finiteQuotientClass) (G := sourceData.carrier) (H := H)
      (ProCGroupPredicate.finiteQuotientFormation ProC)
      (ProCGroupPredicate.finiteQuotientHereditary ProC) psi
  let family : ULift.{u} (Fin r) → sourceData.carrier :=
    freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  let hfree :=
    freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis
  let htarget :=
    freeProCClosedGeneratedTarget_proC_of_surjective
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi
  let hφconv :=
    freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
      (ProC := ProC) (fun i : ULift.{u} (Fin r) => psi (family i))
  have hH : ProC (G := H) :=
    (ProCGroup.of_surjective (G := sourceData.carrier) ProC psi hpsi).isProC
  have hφHconv :
      ProCGroups.FreeProC.FamilyConvergesToOne
        (G := H) (fun i : ULift.{u} (Fin r) => psi (family i)) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_convergesToOne
        (ProC := ProC) sourceData hbasis psi.toMonoidHom
  have hφHgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := H) (Set.range (fun i : ULift.{u} (Fin r) => psi (family i))) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_generates_of_surjective
        (ProC := ProC) sourceData hbasis psi hpsi
  simpa [freeProCChosenULift_sepCoordinateMap, family, hfree, htarget, hφconv] using
    separatedClosedGeneratedDerivativeCoordinatesLinearMapProCInteger_universal
      (G := sourceData.carrier) (H := H) ProC psi family hfree htarget hφconv
      hdir sourceData.proCGroup.isProCGroup hH hφHconv hφHgen g

/-- The separated coordinate equivalence for the chosen finite free pro-`C` basis. -/
def freeProCChosenULift_sepCoordinateEquiv
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    [T1Space
      (ZCFreeFoxCoordinates ProC.finiteQuotientClass
        (X := ULift.{u} (Fin r)) (H := H))] :
    ZCSeparatedCompletedDifferentialModule
        ProC.finiteQuotientClass psi.toMonoidHom ≃ₗ[
      ZCCompletedGroupAlgebra ProC.finiteQuotientClass H]
      ZCFreeFoxCoordinates ProC.finiteQuotientClass
        (X := ULift.{u} (Fin r)) (H := H) := by
  letI : Fact (ProCGroups.FiniteGroupClass.FiniteOnly ProC.finiteQuotientClass) :=
    ⟨by
      intro Q _ hQ
      exact ProCGroupPredicate.finiteQuotientFinite ProC hQ⟩
  letI :
      Nonempty
        (ZCCompletedDifferentialModuleIndex
          ProC.finiteQuotientClass psi.toMonoidHom) :=
    ⟨zcCompletedDifferentialModuleComapIndex
      (C := ProC.finiteQuotientClass) (G := sourceData.carrier) (H := H)
      (ProCGroupPredicate.finiteQuotientHereditary ProC) psi
      ((ProCGroups.Completion.ProCIntegerIndex.terminal
          (C := ProC.finiteQuotientClass) inferInstance),
        zcCompletedGroupAlgebraTopIndex ProC.finiteQuotientClass H)⟩
  have hdir :
      Directed (· ≤ ·)
        (id :
          ZCCompletedDifferentialModuleIndex
              ProC.finiteQuotientClass psi.toMonoidHom →
            ZCCompletedDifferentialModuleIndex
              ProC.finiteQuotientClass psi.toMonoidHom) :=
    directed_zcCompletedDifferentialModuleIndex
      (C := ProC.finiteQuotientClass) (G := sourceData.carrier) (H := H)
      (ProCGroupPredicate.finiteQuotientFormation ProC)
      (ProCGroupPredicate.finiteQuotientHereditary ProC) psi
  let family : ULift.{u} (Fin r) → sourceData.carrier :=
    freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  let hfree :=
    freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis
  let htarget :=
    freeProCClosedGeneratedTarget_proC_of_surjective
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi
  let hφconv :=
    freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
      (ProC := ProC) (fun i : ULift.{u} (Fin r) => psi (family i))
  have hH : ProC (G := H) :=
    (ProCGroup.of_surjective (G := sourceData.carrier) ProC psi hpsi).isProC
  have hφHconv :
      ProCGroups.FreeProC.FamilyConvergesToOne
        (G := H) (fun i : ULift.{u} (Fin r) => psi (family i)) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_convergesToOne
        (ProC := ProC) sourceData hbasis psi.toMonoidHom
  have hφHgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := H) (Set.range (fun i : ULift.{u} (Fin r) => psi (family i))) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_generates_of_surjective
        (ProC := ProC) sourceData hbasis psi hpsi
  exact
    separatedClosedGeneratedDerivativeCoordinateLinearEquivProCInteger
      (G := sourceData.carrier) (H := H) ProC psi family hfree htarget hφconv
      hdir sourceData.proCGroup.isProCGroup hH hφHconv hφHgen

/-- Continuous Magnus injectivity for the separated boundary
`d_N^sep : N^ab(C) -> A_psi(C)_sep`.

The target is the separated finite-stage quotient, so no algebraic relation-submodule closedness
or separate well-definedness hypothesis for `d_N` is needed. -/
theorem freeProC_profKerAbBoundaryAddZCSep_inj_of_continuousMagnus
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    [T1Space
      (ZCFreeFoxCoordinates ProC.finiteQuotientClass
        (X := ULift.{u} (Fin r)) (H := H))] :
    Function.Injective
      (profiniteKernelAbelianizationBoundaryAddProCIntegerSep
        (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi) := by
  apply
    profKerAbBoundaryAddZCSep_inj_of_kernel_le_closedCommutator
      (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
  intro n hnsep
  let htarget :=
    freeProCClosedGeneratedTarget_proC_of_surjective
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi
  apply
    freeProC_closedGeneratedFoxVector_kernel_le_closedCommutator
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi htarget n
  have hcoord_zero :
      freeProCCompletedFoxDerivativeVectorViaClosedGeneratedProCInteger
          (H := H) (ProC := ProC) sourceData hbasis psi htarget n.1 = 0 := by
    have happly :=
      congrArg
        (freeProCChosenULift_sepCoordinateMap
          (H := H) (ProC := ProC) sourceData hbasis psi hpsi) hnsep
    rw [freeProCChosenULift_sepCoordinateMap_universal] at happly
    simpa [freeProCCompletedFoxDerivativeVectorViaClosedGeneratedProCInteger, htarget] using happly
  exact hcoord_zero

omit [ProC.finiteQuotientClass.ContainsTrivialQuotients] in
/-- Closed-generated fundamental formula for the chosen finite free pro-`C` basis after applying
an arbitrary finite `A_psi(C)` stage projection.

This is the unconditional finite-stage statement: it uses continuous crossed-differential
uniqueness into the finite discrete stage and does not assume finite-stage separation of the
algebraic module `A_psi(C)`. -/
theorem freeProCChosenULift_closedGenerated_fundamental_formula_stageProj
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    (i : ZCCompletedDifferentialModuleIndex
        ProC.finiteQuotientClass psi.toMonoidHom)
    (g : sourceData.carrier) :
    zcCompletedDifferentialModuleStageProjection
        ProC.finiteQuotientClass psi.toMonoidHom i
        (presentedCompletedDifferentialFamilyMapProCInteger
          (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
          (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis)
          (freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
            (ProC := ProC)
            (freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis)
            (fun i : ULift.{u} (Fin r) =>
              psi (freeProCChosenULiftFamilyOfBasisCard
                (ProC := ProC) sourceData hbasis i))
            (freeProCClosedGeneratedTarget_proC_of_surjective
              (H := H) (ProC := ProC) sourceData hbasis psi hpsi)
            (freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
              (ProC := ProC)
              (fun i : ULift.{u} (Fin r) =>
                psi (freeProCChosenULiftFamilyOfBasisCard
                  (ProC := ProC) sourceData hbasis i)))
            g)) =
      zcCompletedDifferentialModuleStageProjection
        ProC.finiteQuotientClass psi.toMonoidHom i
        (zcUniversalDifferential ProC.finiteQuotientClass psi.toMonoidHom g) := by
  letI : Fact (ProCGroups.FiniteGroupClass.FiniteOnly ProC.finiteQuotientClass) :=
    ⟨by
      intro Q _ hQ
      exact ProCGroupPredicate.finiteQuotientFinite ProC hQ⟩
  let family : ULift.{u} (Fin r) → sourceData.carrier :=
    freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  let hfree :=
    freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis
  let htarget :=
    freeProCClosedGeneratedTarget_proC_of_surjective
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi
  let hφconv :=
    freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
      (ProC := ProC) (fun i : ULift.{u} (Fin r) => psi (family i))
  have hH : ProC (G := H) :=
    (ProCGroup.of_surjective (G := sourceData.carrier) ProC psi hpsi).isProC
  have hφHconv :
      ProCGroups.FreeProC.FamilyConvergesToOne
        (G := H) (fun i : ULift.{u} (Fin r) => psi (family i)) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_convergesToOne
        (ProC := ProC) sourceData hbasis psi.toMonoidHom
  have hφHgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := H) (Set.range (fun i : ULift.{u} (Fin r) => psi (family i))) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_generates_of_surjective
        (ProC := ProC) sourceData hbasis psi hpsi
  simpa [family, hfree, htarget, hφconv] using
    closedGenerated_fundamental_formula_stageProj
      (G := sourceData.carrier) (H := H) ProC psi family hfree htarget hφconv
      hH hφHconv hφHgen i g

omit [ProC.finiteQuotientClass.ContainsTrivialQuotients] in
/-- Closed-generated fundamental formula for the chosen finite free pro-`C` basis, with all
continuity inputs taken from the finite-stage completed topology on `A_psi(C)`.

The remaining hypothesis is exactly the finite-stage separation statement for that topology. -/
theorem freeProCChosenULift_closedGen_fundFormula_of_stageProjsSeparate
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    (hsep :
      zcCompletedDifferentialModuleStageProjectionsSeparate
        ProC.finiteQuotientClass psi.toMonoidHom) :
    ∀ g : sourceData.carrier,
      presentedCompletedDifferentialFamilyMapProCInteger
          (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
          (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis)
          (freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
            (ProC := ProC)
            (freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis)
            (fun i : ULift.{u} (Fin r) =>
              psi (freeProCChosenULiftFamilyOfBasisCard
                (ProC := ProC) sourceData hbasis i))
            (freeProCClosedGeneratedTarget_proC_of_surjective
              (H := H) (ProC := ProC) sourceData hbasis psi hpsi)
            (freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
              (ProC := ProC)
              (fun i : ULift.{u} (Fin r) =>
                psi (freeProCChosenULiftFamilyOfBasisCard
                  (ProC := ProC) sourceData hbasis i)))
            g) =
        zcUniversalDifferential ProC.finiteQuotientClass psi.toMonoidHom g := by
  let family : ULift.{u} (Fin r) → sourceData.carrier :=
    freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  let hfree :=
    freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis
  let htarget :=
    freeProCClosedGeneratedTarget_proC_of_surjective
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi
  let hφconv :=
    freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
      (ProC := ProC) (fun i : ULift.{u} (Fin r) => psi (family i))
  have hH : ProC (G := H) :=
    (ProCGroup.of_surjective (G := sourceData.carrier) ProC psi hpsi).isProC
  have hφHconv :
      ProCGroups.FreeProC.FamilyConvergesToOne
        (G := H) (fun i : ULift.{u} (Fin r) => psi (family i)) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_convergesToOne
        (ProC := ProC) sourceData hbasis psi.toMonoidHom
  have hφHgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := H) (Set.range (fun i : ULift.{u} (Fin r) => psi (family i))) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_generates_of_surjective
        (ProC := ProC) sourceData hbasis psi hpsi
  simpa [family, hfree, htarget, hφconv] using
    closedGenerated_fundamental_formula_naturalTopology_of_separating
      (G := sourceData.carrier) (H := H) ProC psi family hfree htarget hφconv
      hsep hH hφHconv hφHgen

/-- Closed-generated fundamental formula for the chosen finite free pro-`C` basis, reduced to
closedness of the completed crossed-differential relation submodule.

This is a conditional route theorem: the remaining mathematical content is the closedness
statement, equivalently the finite-stage separation statement for `A_psi(C)`. -/
theorem freeProCChosenULift_closedGen_fundFormula_of_relSubmoduleClosed
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    (hclosed :
      zcCompletedDifferentialModuleRelationSubmoduleClosed
        ProC.finiteQuotientClass psi.toMonoidHom) :
    ∀ g : sourceData.carrier,
      presentedCompletedDifferentialFamilyMapProCInteger
          (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
          (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis)
          (freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
            (ProC := ProC)
            (freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis)
            (fun i : ULift.{u} (Fin r) =>
              psi (freeProCChosenULiftFamilyOfBasisCard
                (ProC := ProC) sourceData hbasis i))
            (freeProCClosedGeneratedTarget_proC_of_surjective
              (H := H) (ProC := ProC) sourceData hbasis psi hpsi)
            (freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
              (ProC := ProC)
              (fun i : ULift.{u} (Fin r) =>
                psi (freeProCChosenULiftFamilyOfBasisCard
                  (ProC := ProC) sourceData hbasis i)))
            g) =
        zcUniversalDifferential ProC.finiteQuotientClass psi.toMonoidHom g := by
  exact
    freeProCChosenULift_closedGen_fundFormula_of_stageProjsSeparate
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi
      (freeProC_zcDiffModuleStageProjsSeparate_of_relSubmoduleClosed
        (H := H) (ProC := ProC) sourceData psi hclosed)

omit [ProCGroups.FiniteGroupClass.ContainsTrivialQuotients ProC.finiteQuotientClass] in
/-- Free pro-`C` closedness of the completed crossed-differential relation submodule from a
non-circular closed-generated fundamental formula.

The finite-stage continuity of the closed-generated coordinate map is supplied by the concrete
pro-`C` source structure of `sourceData.carrier`; hence this theorem isolates the remaining paper
input as exactly the module-valued fundamental formula in the algebraic `A_psi(C)`. -/
theorem freeProC_zcDiffModuleRelSubmoduleClosed_of_closedGen_fundFormula
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    (hfundamental :
      let htarget :=
        freeProCClosedGeneratedTarget_proC_of_surjective
          (H := H) (ProC := ProC) sourceData hbasis psi hpsi
      ∀ g : sourceData.carrier,
        presentedCompletedDifferentialFamilyMapProCInteger
            (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
            (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis)
            (freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
              (ProC := ProC)
              (freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis)
              (fun i : ULift.{u} (Fin r) =>
                psi (freeProCChosenULiftFamilyOfBasisCard
                  (ProC := ProC) sourceData hbasis i))
              htarget
              (freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
                (ProC := ProC)
                (fun i : ULift.{u} (Fin r) =>
                  psi (freeProCChosenULiftFamilyOfBasisCard
                    (ProC := ProC) sourceData hbasis i)))
              g) =
          zcUniversalDifferential ProC.finiteQuotientClass psi.toMonoidHom g) :
    zcCompletedDifferentialModuleRelationSubmoduleClosed
      ProC.finiteQuotientClass psi.toMonoidHom := by
  letI : Fact (ProCGroups.FiniteGroupClass.FiniteOnly ProC.finiteQuotientClass) :=
    ⟨by
      intro Q _ hQ
      exact ProCGroupPredicate.finiteQuotientFinite ProC hQ⟩
  let family : ULift.{u} (Fin r) → sourceData.carrier :=
    freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  let hfree :=
    freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis
  let htarget :=
    freeProCClosedGeneratedTarget_proC_of_surjective
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi
  let hφconv :=
    freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
      (ProC := ProC) (fun i : ULift.{u} (Fin r) => psi (family i))
  have hHProCGroup : ProCGroup ProC H :=
    ProCGroup.of_surjective (G := sourceData.carrier) ProC psi hpsi
  have hH : ProC (G := H) :=
    hHProCGroup.isProC
  have hφHconv :
      ProCGroups.FreeProC.FamilyConvergesToOne
        (G := H) (fun i : ULift.{u} (Fin r) => psi (family i)) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_convergesToOne
        (ProC := ProC) sourceData hbasis psi.toMonoidHom
  have hφHgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := H) (Set.range (fun i : ULift.{u} (Fin r) => psi (family i))) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_generates_of_surjective
        (ProC := ProC) sourceData hbasis psi hpsi
  exact
    zcDiffModuleRelSubmoduleClosed_of_closedGenCoord_isProCGroup_of_fundFormula
      (G := sourceData.carrier) (H := H) ProC psi family hfree htarget hφconv
      sourceData.proCGroup.isProCGroup hH hφHconv hφHgen
      (by simpa [family, hfree, htarget, hφconv] using hfundamental)

/-- For the chosen finite free pro-`C` basis, relation-submodule closedness is exactly
injectivity of the closed-generated coordinate map.

This is the free-source form of Morishita's coordinate theorem before the final augmentation-ideal
or relation-reflection argument: after this point the only missing theorem is the unconditional
injectivity of this coordinate map. -/
-- Do not derive coordinate injectivity from the fundamental formula; both are downstream of closedness.
theorem freeProC_zcDiffModuleRelSubmoduleClosed_iff_closedGenCoord_inj
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi) :
    zcCompletedDifferentialModuleRelationSubmoduleClosed
        ProC.finiteQuotientClass psi.toMonoidHom ↔
      Function.Injective
        (freeProCChosenULift_closedGeneratedCoordinateMap
          (H := H) (ProC := ProC) sourceData hbasis psi hpsi) := by
  letI : Fact (ProCGroups.FiniteGroupClass.FiniteOnly ProC.finiteQuotientClass) :=
    ⟨by
      intro Q _ hQ
      exact ProCGroupPredicate.finiteQuotientFinite ProC hQ⟩
  letI :
      Nonempty
        (ZCCompletedDifferentialModuleIndex
          ProC.finiteQuotientClass psi.toMonoidHom) :=
    ⟨zcCompletedDifferentialModuleComapIndex
      (C := ProC.finiteQuotientClass) (G := sourceData.carrier) (H := H)
      (ProCGroupPredicate.finiteQuotientHereditary ProC) psi
      ((ProCGroups.Completion.ProCIntegerIndex.terminal
          (C := ProC.finiteQuotientClass) inferInstance),
        zcCompletedGroupAlgebraTopIndex ProC.finiteQuotientClass H)⟩
  have hdir :
      Directed (· ≤ ·)
        (id :
          ZCCompletedDifferentialModuleIndex
              ProC.finiteQuotientClass psi.toMonoidHom →
            ZCCompletedDifferentialModuleIndex
              ProC.finiteQuotientClass psi.toMonoidHom) :=
    directed_zcCompletedDifferentialModuleIndex
      (C := ProC.finiteQuotientClass) (G := sourceData.carrier) (H := H)
      (ProCGroupPredicate.finiteQuotientFormation ProC)
      (ProCGroupPredicate.finiteQuotientHereditary ProC) psi
  let family : ULift.{u} (Fin r) → sourceData.carrier :=
    freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  let hfree :=
    freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis
  let htarget :=
    freeProCClosedGeneratedTarget_proC_of_surjective
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi
  let hφconv :=
    freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
      (ProC := ProC) (fun i : ULift.{u} (Fin r) => psi (family i))
  have hH : ProC (G := H) :=
    (ProCGroup.of_surjective (G := sourceData.carrier) ProC psi hpsi).isProC
  have hφHconv :
      ProCGroups.FreeProC.FamilyConvergesToOne
        (G := H) (fun i : ULift.{u} (Fin r) => psi (family i)) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_convergesToOne
        (ProC := ProC) sourceData hbasis psi.toMonoidHom
  have hφHgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := H) (Set.range (fun i : ULift.{u} (Fin r) => psi (family i))) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_generates_of_surjective
        (ProC := ProC) sourceData hbasis psi hpsi
  have hiff :=
    zcDiffModuleRelSubmoduleClosed_iff_closedGenCoord_inj_of_isProCGroup
      (G := sourceData.carrier) (H := H) ProC psi family hfree htarget hφconv
      hdir sourceData.proCGroup.isProCGroup hH hφHconv hφHgen
  simpa [freeProCChosenULift_closedGeneratedCoordinateMap, family, hfree, htarget, hφconv,
    hH, hφHconv, hφHgen] using hiff

/-- The closed-generated coordinate-injectivity form of the remaining Morishita frontier.

Once the augmentation-ideal identification proves this injectivity, the finite-stage
relation-submodule closedness used by the Crowell and BL route theorems follows immediately. -/
theorem freeProC_zcDiffModuleRelSubmoduleClosed_of_closedGenCoord_inj
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    (hcoord_inj :
      Function.Injective
        (freeProCChosenULift_closedGeneratedCoordinateMap
          (H := H) (ProC := ProC) sourceData hbasis psi hpsi)) :
    zcCompletedDifferentialModuleRelationSubmoduleClosed
      ProC.finiteQuotientClass psi.toMonoidHom :=
  (freeProC_zcDiffModuleRelSubmoduleClosed_iff_closedGenCoord_inj
    (H := H) (ProC := ProC) sourceData hbasis psi hpsi).2 hcoord_inj

/-- Coordinate-injectivity form of the closed-generated fundamental formula. -/
theorem freeProCChosenULift_closedGen_fundFormula_of_closedGenCoord_inj
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    (hcoord_inj :
      Function.Injective
        (freeProCChosenULift_closedGeneratedCoordinateMap
          (H := H) (ProC := ProC) sourceData hbasis psi hpsi)) :
    let htarget :=
      freeProCClosedGeneratedTarget_proC_of_surjective
        (H := H) (ProC := ProC) sourceData hbasis psi hpsi
    ∀ g : sourceData.carrier,
      presentedCompletedDifferentialFamilyMapProCInteger
          (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
          (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis)
          (freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
            (ProC := ProC)
            (freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis)
            (fun i : ULift.{u} (Fin r) =>
              psi (freeProCChosenULiftFamilyOfBasisCard
                (ProC := ProC) sourceData hbasis i))
            htarget
            (freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
              (ProC := ProC)
              (fun i : ULift.{u} (Fin r) =>
                psi (freeProCChosenULiftFamilyOfBasisCard
                  (ProC := ProC) sourceData hbasis i)))
            g) =
        zcUniversalDifferential ProC.finiteQuotientClass psi.toMonoidHom g := by
  exact
    freeProCChosenULift_closedGen_fundFormula_of_relSubmoduleClosed
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi
      (freeProC_zcDiffModuleRelSubmoduleClosed_of_closedGenCoord_inj
        (H := H) (ProC := ProC) sourceData hbasis psi hpsi hcoord_inj)

omit [ProC.finiteQuotientClass.ContainsTrivialQuotients] in
/-- For the chosen finite free pro-`C` basis, the closed-generated Fox graph internally supplies
the well-definedness of `d_N`. -/
theorem freeProC_completedBoundaryKillsTopCommZC_of_closedGen_and_psi_surj
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    (htarget :
      ProC
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC)
            (fun i : ULift.{u} (Fin r) =>
              psi (freeProCChosenULiftFamilyOfBasisCard
                (ProC := ProC) sourceData hbasis i)) : Subgroup
              (ZCCompletedFoxSemidirect
                ProC.finiteQuotientClass (ULift.{u} (Fin r)) H))))
    (hbasis_A :
      IsPresentedCompletedDifferentialFamilyBasisProCInteger
        (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
        (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis)) :
    CompletedBoundaryKillsTopologicalCommutatorProCInteger
      (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi := by
  let family : ULift.{u} (Fin r) → sourceData.carrier :=
    freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  let hfree :=
    freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis
  let hφconv :=
    freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
      (ProC := ProC) (fun i : ULift.{u} (Fin r) => psi (family i))
  have hHProCGroup : ProCGroup ProC H :=
    ProCGroup.of_surjective (G := sourceData.carrier) ProC psi hpsi
  have hH : ProC (G := H) :=
    hHProCGroup.isProC
  have hφHconv :
      ProCGroups.FreeProC.FamilyConvergesToOne
        (G := H) (fun i : ULift.{u} (Fin r) => psi (family i)) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_convergesToOne
        (ProC := ProC) sourceData hbasis psi.toMonoidHom
  have hφHgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := H) (Set.range (fun i : ULift.{u} (Fin r) => psi (family i))) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_generates_of_surjective
        (ProC := ProC) sourceData hbasis psi hpsi
  have hleft_graph_eq :
      ∀ g : sourceData.carrier,
        freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
            (ProC := ProC) hfree (fun i : ULift.{u} (Fin r) => psi (family i))
            htarget hφconv g =
          presentedCompletedDifferentialFamilyCoordinatesProCInteger
            (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi family hbasis_A
            (zcUniversalDifferential ProC.finiteQuotientClass psi.toMonoidHom g) := by
    exact
      freeProCZCCompletedFoxDerivativeVectorViaClosedGen_eq_presentedCoordinates_zcUnivDiff
        (G := sourceData.carrier) (H := H) ProC psi family hbasis_A hfree hH htarget hφconv
        hφHconv hφHgen
  exact
    completedBoundaryKillsTopCommZC_of_closedGen_leftGraph
      (G := sourceData.carrier) (H := H) ProC psi family hbasis_A hfree htarget hφconv
      hleft_graph_eq

/-- Exactness at the separated Crowell middle term from the standard all-finite-quotient stage
family.

This is the direct separated route: finite stages show that every completed Fox boundary cycle
lies in the closed-generated Fox graph target, and the separated coordinate equivalence turns that
closed-generated lift into an integration by an element of `ker psi`.  No algebraic
`A_psi(C)` basis or relation-submodule closedness hypothesis is used. -/
theorem freeProC_exactAtSepA_of_continuousMagnus_zcBifilteredAllFiniteQuotientStages
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    [T1Space
      (ZCFreeFoxCoordinates ProC.finiteQuotientClass
        (X := ULift.{u} (Fin r)) (H := H))] :
    Function.Exact
      (profiniteKernelAbelianizationBoundaryAddProCIntegerSep
        (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi)
      (presentedSeparatedDifferentialToCompletedGroupAlgebraProCInteger
        (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass
        (ProCGroupPredicate.finiteQuotientHereditary ProC) psi) := by
  letI : Fact (ProCGroups.FiniteGroupClass.FiniteOnly ProC.finiteQuotientClass) :=
    ⟨by
      intro Q _ hQ
      exact ProCGroupPredicate.finiteQuotientFinite ProC hQ⟩
  letI : CompactSpace sourceData.carrier :=
    ProCGroup.compactSpace ProC sourceData.carrier
  let family : ULift.{u} (Fin r) → sourceData.carrier :=
    freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  let hfree :=
    freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis
  let htarget :=
    freeProCClosedGeneratedTarget_proC_of_surjective
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi
  let hφconv :=
    freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
      (ProC := ProC) (fun i : ULift.{u} (Fin r) => psi (family i))
  have hHProCGroup : ProCGroup ProC H :=
    ProCGroup.of_surjective (G := sourceData.carrier) ProC psi hpsi
  have hH : ProC (G := H) :=
    hHProCGroup.isProC
  have hH_isProC : IsProCGroup ProC.finiteQuotientClass H :=
    hHProCGroup.isProCGroup
  have hφHconv :
      ProCGroups.FreeProC.FamilyConvergesToOne
        (G := H) (fun i : ULift.{u} (Fin r) => psi (family i)) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_convergesToOne
        (ProC := ProC) sourceData hbasis psi.toMonoidHom
  have hφHgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := H) (Set.range (fun i : ULift.{u} (Fin r) => psi (family i))) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_generates_of_surjective
        (ProC := ProC) sourceData hbasis psi hpsi
  let φ : ULift.{u} (Fin r) → H := fun i => psi (family i)
  let coords :=
    freeProCChosenULift_sepCoordinateEquiv
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi
  let Dcoords : sourceData.carrier →
      ZCFreeFoxCoordinates ProC.finiteQuotientClass
        (X := ULift.{u} (Fin r)) (H := H) :=
    fun g =>
      freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
        (ProC := ProC) hfree φ htarget hφconv g
  have hright_graph_eq :
      freeProCZCCompletedFoxRightHomViaClosedGenerated
          (ProC := ProC) hfree φ htarget hφconv =
        psi.toMonoidHom := by
    exact
      freeProCZCCompletedFoxRightHomViaClosedGenerated_eq_continuousHom
        (ProC := ProC) (ULift.{u} (Fin r)) H hfree hH φ htarget hφconv
        hφHconv hφHgen psi (by intro i; rfl)
  have hcycle_closed :
      freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ ⊆
        ((freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass
              (ULift.{u} (Fin r)) H)) : Set
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass
              (ULift.{u} (Fin r)) H)) := by
    exact
      freeProCZCFoxBoundaryCycles_subset_closedGenTarget_of_zcBiAllStages_coeffGraphRelDeriv
        (ProC := ProC) (X := ULift.{u} (Fin r)) (H := H) φ hH_isProC hφHgen
  refine
    exact_boundaryAddZC_sep_of_coord_cycle_lift
      (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass
      (ProCGroupPredicate.finiteQuotientHereditary ProC) psi family coords ?_ Dcoords ?_ ?_
  · rfl
  · intro n
    simpa [coords, Dcoords, family, hfree, htarget, hφconv, φ] using
      (freeProCChosenULift_sepCoordinateMap_universal
        (H := H) (ProC := ProC) sourceData hbasis psi hpsi n.1).symm
  · intro v hv
    have hboundaryMap :
        blanchfieldLyndonFiniteFamilyMap
            (R := ZCCompletedGroupAlgebra ProC.finiteQuotientClass H)
            (fun i : ULift.{u} (Fin r) =>
              presentedCompletedDifferentialBoundaryProCInteger
                (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi (family i)) =
          zcFreeGroupFoxBoundary
            ProC.finiteQuotientClass
            (FreeGroup.lift φ) :=
      finiteBLMap_boundaryZC_eq_zcFreeGroupFoxBoundary
        (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi family
    have hvBoundary :
        zcFreeGroupFoxBoundary ProC.finiteQuotientClass (FreeGroup.lift φ) v = 0 := by
      simpa [hboundaryMap, φ] using hv
    have hy :
        ({ left := v, right := (1 : H) } :
          ZCCompletedFoxSemidirect ProC.finiteQuotientClass
            (ULift.{u} (Fin r)) H) ∈
          freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ := by
      constructor
      · rfl
      · exact hvBoundary
    have hyTarget := hcycle_closed hy
    rcases
      freeProCZCFoxSemiLiftViaClosedGen_exists_preimage_of_mem_closedGenTarget
        (ProC := ProC) hfree φ htarget hφconv hyTarget with
      ⟨g, hg⟩
    have hleft : Dcoords g = v := by
      have h := congrArg
        (fun z : ZCCompletedFoxSemidirect ProC.finiteQuotientClass
            (ULift.{u} (Fin r)) H => z.left) hg
      simpa [Dcoords, freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated] using h
    have hrightLift :
        freeProCZCCompletedFoxRightHomViaClosedGenerated
            (ProC := ProC) hfree φ htarget hφconv g = 1 := by
      have h := congrArg
        (fun z : ZCCompletedFoxSemidirect ProC.finiteQuotientClass
            (ULift.{u} (Fin r)) H => z.right) hg
      simpa [freeProCZCCompletedFoxRightHomViaClosedGenerated] using h
    have hright : psi g = 1 := by
      simpa [hright_graph_eq] using hrightLift
    exact ⟨⟨g, hright⟩, hleft⟩

omit [ProCGroups.FiniteGroupClass.ContainsTrivialQuotients ProC.finiteQuotientClass] in
/-- The universe-lifted chosen free basis is an `A_psi(C)` basis once the closed-generated
derivative vector satisfies the completed fundamental formula. -/
theorem chosenULift_hbasis_A_of_closedGen_fundFormula
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    (htarget :
      ProC
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC)
            (fun i : ULift.{u} (Fin r) =>
              psi (freeProCChosenULiftFamilyOfBasisCard
                (ProC := ProC) sourceData hbasis i)) : Subgroup
              (ZCCompletedFoxSemidirect
                ProC.finiteQuotientClass (ULift.{u} (Fin r)) H))))
    (hfundamental :
      ∀ g : sourceData.carrier,
        presentedCompletedDifferentialFamilyMapProCInteger
            (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
            (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis)
            (freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
              (ProC := ProC)
              (freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis)
              (fun i : ULift.{u} (Fin r) =>
                psi (freeProCChosenULiftFamilyOfBasisCard
                  (ProC := ProC) sourceData hbasis i))
              htarget
              (freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
                (ProC := ProC)
                (fun i : ULift.{u} (Fin r) =>
                  psi (freeProCChosenULiftFamilyOfBasisCard
                    (ProC := ProC) sourceData hbasis i)))
              g) =
          zcUniversalDifferential ProC.finiteQuotientClass psi.toMonoidHom g) :
    IsPresentedCompletedDifferentialFamilyBasisProCInteger
      (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
      (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis) := by
  let family : ULift.{u} (Fin r) → sourceData.carrier :=
    freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  let hfree :=
    freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis
  let hφconv :=
    freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
      (ProC := ProC) (fun i : ULift.{u} (Fin r) => psi (family i))
  have hHProCGroup : ProCGroup ProC H :=
    ProCGroup.of_surjective (G := sourceData.carrier) ProC psi hpsi
  have hH : ProC (G := H) :=
    hHProCGroup.isProC
  have hφHconv :
      ProCGroups.FreeProC.FamilyConvergesToOne
        (G := H) (fun i : ULift.{u} (Fin r) => psi (family i)) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_convergesToOne
        (ProC := ProC) sourceData hbasis psi.toMonoidHom
  have hφHgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := H) (Set.range (fun i : ULift.{u} (Fin r) => psi (family i))) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_generates_of_surjective
        (ProC := ProC) sourceData hbasis psi hpsi
  exact
    isPresentedCompletedDifferentialFamilyBasisZC_of_closedGen_fundFormula
      (G := sourceData.carrier) (H := H) ProC psi family hfree
      (by simpa [family] using htarget) hφconv hH hφHconv hφHgen
      (by simpa [family, hfree, hφconv] using hfundamental)

omit [ProC.finiteQuotientClass.ContainsTrivialQuotients] in
/-- The universe-lifted chosen free basis is an `A_psi(C)` basis when the closed-generated
module-valued fundamental formula follows from continuity into a Hausdorff topology on
`A_psi(C)`.

This is the topological version of
`chosenULift_hbasis_A_of_closedGen_fundFormula`: it
derives the former `hfundamental` hypothesis from continuous-crossed-differential uniqueness. -/
theorem chosenULift_hbasis_A_of_closedGen_fundFormula_continuous
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    [TopologicalSpace (ZCCompletedDifferentialModule
      ProC.finiteQuotientClass psi.toMonoidHom)]
    [T2Space (ZCCompletedDifferentialModule
      ProC.finiteQuotientClass psi.toMonoidHom)]
    (htarget :
      ProC
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC)
            (fun i : ULift.{u} (Fin r) =>
              psi (freeProCChosenULiftFamilyOfBasisCard
                (ProC := ProC) sourceData hbasis i)) : Subgroup
              (ZCCompletedFoxSemidirect
                ProC.finiteQuotientClass (ULift.{u} (Fin r)) H))))
    (hmodule_continuous :
      Continuous
        (fun g : sourceData.carrier =>
          presentedCompletedDifferentialFamilyMapProCInteger
              (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
              (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis)
              (freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
                (ProC := ProC)
                (freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis)
                (fun i : ULift.{u} (Fin r) =>
                  psi (freeProCChosenULiftFamilyOfBasisCard
                    (ProC := ProC) sourceData hbasis i))
                htarget
                (freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
                  (ProC := ProC)
                  (fun i : ULift.{u} (Fin r) =>
                    psi (freeProCChosenULiftFamilyOfBasisCard
                      (ProC := ProC) sourceData hbasis i)))
                g)))
    (huniv_continuous :
      Continuous
        (fun g : sourceData.carrier =>
          zcUniversalDifferential ProC.finiteQuotientClass psi.toMonoidHom g)) :
    IsPresentedCompletedDifferentialFamilyBasisProCInteger
      (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
      (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis) := by
  let family : ULift.{u} (Fin r) → sourceData.carrier :=
    freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis
  let hfree :=
    freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis
  let hφconv :=
    freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
      (ProC := ProC) (fun i : ULift.{u} (Fin r) => psi (family i))
  have hHProCGroup : ProCGroup ProC H :=
    ProCGroup.of_surjective (G := sourceData.carrier) ProC psi hpsi
  have hH : ProC (G := H) :=
    hHProCGroup.isProC
  have hφHconv :
      ProCGroups.FreeProC.FamilyConvergesToOne
        (G := H) (fun i : ULift.{u} (Fin r) => psi (family i)) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_convergesToOne
        (ProC := ProC) sourceData hbasis psi.toMonoidHom
  have hφHgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := H) (Set.range (fun i : ULift.{u} (Fin r) => psi (family i))) := by
    simpa [family] using
      freeProCChosenULiftFamilyOfBasisCard_image_generates_of_surjective
        (ProC := ProC) sourceData hbasis psi hpsi
  have hfundamental :
      ∀ g : sourceData.carrier,
        presentedCompletedDifferentialFamilyMapProCInteger
            (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi family
            (freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
              (ProC := ProC) hfree (fun i : ULift.{u} (Fin r) => psi (family i))
              (by simpa [family] using htarget) hφconv g) =
          zcUniversalDifferential ProC.finiteQuotientClass psi.toMonoidHom g :=
    closedGenerated_fundamental_formula_of_continuous
      (G := sourceData.carrier) (H := H) ProC psi family hfree
      (by simpa [family] using htarget) hφconv hH hφHconv hφHgen
      (by simpa [family, hfree, hφconv] using hmodule_continuous)
      (by simpa using huniv_continuous)
  exact
    chosenULift_hbasis_A_of_closedGen_fundFormula
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi htarget
      (by simpa [family, hfree, hφconv] using hfundamental)

/-- The universe-lifted chosen free basis is an `A_psi(C)` basis, reduced to closedness of the
completed crossed-differential relation submodule.

This is a conditional route theorem: it removes the topology, Hausdorffness, continuity, and
fundamental-formula inputs, but still depends on the closedness statement that is the remaining
B9 finite-stage separation problem. -/
theorem freeProCChosenULiftFamilyOfBasisCard_hbasis_A_of_relationSubmoduleClosed
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    (hclosed :
      zcCompletedDifferentialModuleRelationSubmoduleClosed
        ProC.finiteQuotientClass psi.toMonoidHom) :
    IsPresentedCompletedDifferentialFamilyBasisProCInteger
      (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
      (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis) := by
  let htarget :=
    freeProCClosedGeneratedTarget_proC_of_surjective
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi
  have hfundamental :
      ∀ g : sourceData.carrier,
        presentedCompletedDifferentialFamilyMapProCInteger
            (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
            (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis)
            (freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
              (ProC := ProC)
              (freeProCChosenULiftFamilyOfBasisCard_isFree (ProC := ProC) sourceData hbasis)
              (fun i : ULift.{u} (Fin r) =>
                psi (freeProCChosenULiftFamilyOfBasisCard
                  (ProC := ProC) sourceData hbasis i))
              htarget
              (freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
                (ProC := ProC)
                (fun i : ULift.{u} (Fin r) =>
                  psi (freeProCChosenULiftFamilyOfBasisCard
                    (ProC := ProC) sourceData hbasis i)))
              g) =
          zcUniversalDifferential ProC.finiteQuotientClass psi.toMonoidHom g := by
    simpa [htarget] using
      freeProCChosenULift_closedGen_fundFormula_of_relSubmoduleClosed
        (H := H) (ProC := ProC) sourceData hbasis psi hpsi hclosed
  exact
    chosenULift_hbasis_A_of_closedGen_fundFormula
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi htarget hfundamental

/-- Coordinate-injectivity form of the finite `A_psi(C)` basis theorem. -/
theorem freeProCChosenULiftFamilyOfBasisCard_hbasis_A_of_closedGenCoord_inj
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi)
    (hcoord_inj :
      Function.Injective
        (freeProCChosenULift_closedGeneratedCoordinateMap
          (H := H) (ProC := ProC) sourceData hbasis psi hpsi)) :
    IsPresentedCompletedDifferentialFamilyBasisProCInteger
      (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi
      (freeProCChosenULiftFamilyOfBasisCard (ProC := ProC) sourceData hbasis) :=
  freeProCChosenULiftFamilyOfBasisCard_hbasis_A_of_relationSubmoduleClosed
    (H := H) (ProC := ProC) sourceData hbasis psi hpsi
    (freeProC_zcDiffModuleRelSubmoduleClosed_of_closedGenCoord_inj
      (H := H) (ProC := ProC) sourceData hbasis psi hpsi hcoord_inj)

/-- Free pro-`C` separated Crowell exactness from the standard all-finite-quotient stage
family and surjectivity of `psi`.

This is the public separated Crowell assembly theorem.  The exactness at the separated middle
term is proved internally from the all-finite stage family, and injectivity is supplied by
continuous Magnus. -/
theorem freeProC_presentedSepCrowellZC_of_continuousMagnus_zcBiAllStages_of_psi_surj
    [T2Space H]
    [ProC.HasFiniteQuotientFormation] [ProC.HasFiniteQuotientFinite]
    [ProC.HasFiniteQuotientHereditary] [ProC.HasFiniteQuotientMelnikovFormation]
    [ProC.DeterminedByFiniteQuotients]
    (sourceData : FreeProCSourceData ProC)
    {r : Nat} (hbasis : Cardinal.mk sourceData.basis = r)
    (psi : ContinuousMonoidHom sourceData.carrier H)
    (hpsi : Function.Surjective psi) :
    Function.Injective
        (profiniteKernelAbelianizationBoundaryAddProCIntegerSep
          (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi) ∧
      Function.Exact
        (profiniteKernelAbelianizationBoundaryAddProCIntegerSep
          (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass psi)
        (presentedSeparatedDifferentialToCompletedGroupAlgebraProCInteger
          (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass
          (ProCGroupPredicate.finiteQuotientHereditary ProC) psi) ∧
        Function.Exact
          (presentedSeparatedDifferentialToCompletedGroupAlgebraProCInteger
            (G := sourceData.carrier) (H := H) ProC.finiteQuotientClass
            (ProCGroupPredicate.finiteQuotientHereditary ProC) psi)
          (zcCompletedGroupAlgebraAugmentation ProC.finiteQuotientClass H) ∧
          Function.Surjective
            (zcCompletedGroupAlgebraAugmentation ProC.finiteQuotientClass H) :=
by
  exact
    ⟨freeProC_profKerAbBoundaryAddZCSep_inj_of_continuousMagnus
        (H := H) (ProC := ProC) sourceData hbasis psi hpsi,
      freeProC_exactAtSepA_of_continuousMagnus_zcBifilteredAllFiniteQuotientStages
        (H := H) (ProC := ProC) sourceData hbasis psi hpsi,
      freeProC_presentedSeparatedCrowellGroupAlgebraExactProCInteger_of_psi_surjective
        (H := H) (ProC := ProC) sourceData hbasis psi hpsi,
      zcCompletedGroupAlgebraAugmentation_surjective
        (C := ProC.finiteQuotientClass) (H := H)⟩

end

end CrowellExactSequence
