import FoxDifferential.Completed.Continuous.Free.DiscreteGenerators
import FoxDifferential.Completed.Continuous.Free.Rules
import FoxDifferential.Completed.Continuous.Topology

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/FoxDifferential/Completed/Continuous/Universal/Basic.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Continuous crossed differentials

Crossed differentials, universal differential modules, Fox boundaries, Euler formulas, and Jacobians are the common algebraic layer used by Crowell and metabelian applications.
-/
namespace FoxDifferential

noncomputable section

open scoped BigOperators

universe u v

section UniversalTopology

variable (C : ProCGroups.FiniteGroupClass.{v})
variable {G : Type u} [Group G] [TopologicalSpace G]
variable {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

/-- The final topology on the completed universal differential module generated by the universal
crossed differential `G -> d_{Z_C[[H]]} G`.

Unlike the finite-rank free-coordinate topology, this topology is available for an arbitrary source
group and states the genuine topological universal property: a map out is continuous exactly when
its composite with the universal differential is continuous. -/
def zcCompletedDifferentialModuleUniversalTopology (ψ : G →* H) :
    TopologicalSpace (ZCCompletedDifferentialModule C ψ) :=
  TopologicalSpace.coinduced (zcUniversalDifferential C ψ) inferInstance

/-- The universal crossed differential is continuous for the final universal topology. -/
theorem continuous_zcUniversalDifferential_universalTopology
    (ψ : G →* H) :
    @Continuous G (ZCCompletedDifferentialModule C ψ) inferInstance
      (zcCompletedDifferentialModuleUniversalTopology C ψ)
      (zcUniversalDifferential C ψ) :=
  continuous_coinduced_rng

variable {A : Type*} [AddCommGroup A] [Module (ZCCompletedGroupAlgebra C H) A]
variable [TopologicalSpace A]

/-- Topological universal property of the completed differential module with its final topology.

For an arbitrary source group, the universal linear map representing a crossed differential is
continuous exactly when the crossed differential itself is continuous. -/
theorem continuous_zcCompletedDifferentialModuleLift_universalTopology_iff
    {ψ : G →* H} {delta : G → A}
    (hdelta : IsCrossedDifferential (zcCompletedGroupAlgebraScalar C ψ) delta) :
    @Continuous (ZCCompletedDifferentialModule C ψ) A
        (zcCompletedDifferentialModuleUniversalTopology C ψ) inferInstance
        (zcCompletedDifferentialModuleLift (A := A) C ψ delta hdelta) ↔
      Continuous delta := by
  rw [continuous_coinduced_dom]
  have hcomp :
      (zcCompletedDifferentialModuleLift (A := A) C ψ delta hdelta) ∘
          (zcUniversalDifferential C ψ) = delta := by
    funext g
    exact zcCompletedDifferentialModuleLift_universal
      (A := A) C ψ delta hdelta g
  rw [hcomp]

section ContinuousLinearMapPackaging

variable (ψ : G →* H)

instance zcCompletedDifferentialModuleUniversalTopologyInst :
    TopologicalSpace (ZCCompletedDifferentialModule C ψ) :=
  zcCompletedDifferentialModuleUniversalTopology C ψ

/-- The representing universal lift as a continuous linear map for the final universal topology,
from a continuous crossed differential. -/
def zcCompletedDifferentialModuleLiftUniversalContinuousLinearMap
    (delta : G → A)
    (hdelta : IsCrossedDifferential (zcCompletedGroupAlgebraScalar C ψ) delta)
    (hcont : Continuous delta) :
    ZCCompletedDifferentialModule C ψ →L[ZCCompletedGroupAlgebra C H] A where
  toLinearMap := zcCompletedDifferentialModuleLift (A := A) C ψ delta hdelta
  cont :=
    (continuous_zcCompletedDifferentialModuleLift_universalTopology_iff
      (C := C) (G := G) (H := H) (A := A) (ψ := ψ) (delta := delta) hdelta).2 hcont

/-- Evaluation of the universal-topology continuous lift. -/
@[simp]
theorem zcCompletedDifferentialModuleLiftUniversalContinuousLinearMap_apply
    (delta : G → A)
    (hdelta : IsCrossedDifferential (zcCompletedGroupAlgebraScalar C ψ) delta)
    (hcont : Continuous delta)
    (m : ZCCompletedDifferentialModule C ψ) :
    zcCompletedDifferentialModuleLiftUniversalContinuousLinearMap
        (C := C) (G := G) (H := H) (A := A) ψ delta hdelta hcont m =
      zcCompletedDifferentialModuleLift (A := A) C ψ delta hdelta m :=
  rfl

/-- Topological universal representation theorem for completed crossed differentials.

With the final universal topology on the completed differential module, continuous crossed
differentials `G -> A` are equivalent to continuous `Z_C[[H]]`-linear maps out of the completed
universal differential module. -/
def zcCompletedContinuousCrossedDifferentialEquivContinuousLinearMap :
    {delta : G → A //
        IsCrossedDifferential (zcCompletedGroupAlgebraScalar C ψ) delta ∧ Continuous delta} ≃
      (ZCCompletedDifferentialModule C ψ →L[ZCCompletedGroupAlgebra C H] A) where
  toFun delta :=
    zcCompletedDifferentialModuleLiftUniversalContinuousLinearMap
      (C := C) (G := G) (H := H) (A := A) ψ delta.1 delta.2.1 delta.2.2
  invFun f :=
    ⟨fun g => f (zcUniversalDifferential C ψ g), by
      constructor
      · intro g h
        change f (zcUniversalDifferential C ψ (g * h)) =
          f (zcUniversalDifferential C ψ g) +
            zcCompletedGroupAlgebraScalar C ψ g •
              f (zcUniversalDifferential C ψ h)
        rw [zcUniversalDifferential_mul]
        simp only [zcCompletedGroupAlgebraScalar_apply, map_add, map_smul]
      · exact f.cont.comp (continuous_zcUniversalDifferential_universalTopology C ψ)⟩
  left_inv delta := by
    apply Subtype.ext
    funext g
    exact zcCompletedDifferentialModuleLift_universal
      (A := A) C ψ delta.1 delta.2.1 g
  right_inv f := by
    apply ContinuousLinearMap.ext
    intro m
    have hdelta :
        IsCrossedDifferential (zcCompletedGroupAlgebraScalar C ψ)
          (fun g => f (zcUniversalDifferential C ψ g)) := by
      intro g h
      change f (zcUniversalDifferential C ψ (g * h)) =
        f (zcUniversalDifferential C ψ g) +
          zcCompletedGroupAlgebraScalar C ψ g •
            f (zcUniversalDifferential C ψ h)
      rw [zcUniversalDifferential_mul]
      simp only [zcCompletedGroupAlgebraScalar_apply, map_add, map_smul]
    have hlin :
        f.toLinearMap =
          zcCompletedDifferentialModuleLift (A := A) C ψ
            (fun g => f (zcUniversalDifferential C ψ g)) hdelta := by
      apply zcCompletedDifferentialModuleLift_unique (A := A) C ψ
      intro g
      rfl
    exact congrFun (congrArg DFunLike.coe hlin.symm) m

end ContinuousLinearMapPackaging

/-- The universal boundary map from the completed differential module to `Z_C[[H]]` is continuous
for the final universal topology whenever the target homomorphism is continuous. -/
theorem continuous_zcToCompletedGroupAlgebra_universalTopology
    (ψ : G →* H) (hψ : Continuous ψ) :
    @Continuous (ZCCompletedDifferentialModule C ψ) (ZCCompletedGroupAlgebra C H)
      (zcCompletedDifferentialModuleUniversalTopology C ψ) inferInstance
      (zcToCompletedGroupAlgebra C ψ) := by
  exact
    (continuous_zcCompletedDifferentialModuleLift_universalTopology_iff
      (C := C) (G := G) (H := H) (A := ZCCompletedGroupAlgebra C H)
      (ψ := ψ) (delta := zcCompletedGroupAlgebraBoundary C ψ)
      (zcCompletedGroupAlgebraBoundary_isCrossedDifferential C ψ)).2
      (continuous_zcCompletedGroupAlgebraBoundary (C := C) (G := H) ψ hψ)

end UniversalTopology

section FreeGroupUniversalTopology

variable (C : ProCGroups.FiniteGroupClass.{v})
variable [Fact (ProCGroups.FiniteGroupClass.FiniteOnly C)]
variable {X : Type u} [Fintype X] [DecidableEq X]
variable {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

/-- The finite-rank topology on the completed universal module, induced by completed Fox
coordinates.  This is intentionally a named topology, not a global instance. -/
def zcCompletedDifferentialModuleFreeTopology (ψ : FreeGroup X →* H) :
    TopologicalSpace (ZCCompletedDifferentialModule C ψ) :=
  TopologicalSpace.induced (zcDifferentialToFreeFoxCoordinates C ψ) inferInstance

omit [Fact (ProCGroups.FiniteGroupClass.FiniteOnly C)] [Fintype X] in
/-- The coordinate map out of the completed universal module is continuous for the finite-rank
coordinate-induced topology. -/
theorem continuous_zcDifferentialToFreeFoxCoordinates_freeTopology
    (ψ : FreeGroup X →* H) :
    @Continuous (ZCCompletedDifferentialModule C ψ)
      (ZCFreeFoxCoordinates C (X := X) (H := H))
      (zcCompletedDifferentialModuleFreeTopology C ψ) inferInstance
      (zcDifferentialToFreeFoxCoordinates C ψ) :=
  continuous_induced_dom

omit [Fact (ProCGroups.FiniteGroupClass.FiniteOnly C)] in
/-- The coordinate-to-universal-module map is continuous for the finite-rank coordinate-induced
topology. -/
theorem continuous_zcFreeFoxCoordinatesLinearMap_freeTopology
    (ψ : FreeGroup X →* H) :
    @Continuous (ZCFreeFoxCoordinates C (X := X) (H := H))
      (ZCCompletedDifferentialModule C ψ) inferInstance
      (zcCompletedDifferentialModuleFreeTopology C ψ)
      (zcFreeFoxCoordinatesLinearMap C ψ) := by
  rw [continuous_induced_rng]
  have hcomp :
      (zcDifferentialToFreeFoxCoordinates C ψ) ∘
        (zcFreeFoxCoordinatesLinearMap C ψ) =
        id := by
    funext v
    exact congrFun
      (congrArg DFunLike.coe
        (zcDifferentialToFreeFoxCoordinates_comp_zcFreeFoxCoordinatesLinearMap C ψ)) v
  rw [hcomp]
  exact continuous_id

/-- The coordinate module `Z_C[[H]]^X` has continuous scalar multiplication. -/
instance instContinuousSMulZCFreeFoxCoordinates :
    ContinuousSMul (ZCCompletedGroupAlgebra C H)
      (ZCFreeFoxCoordinates C (X := X) (H := H)) :=
  inferInstance

/-- The finite-rank completed universal module has continuous scalar multiplication for the
coordinate-induced topology. -/
instance instContinuousSMulZCCompletedDifferentialModuleFreeTopology
    (ψ : FreeGroup X →* H) :
    @ContinuousSMul (ZCCompletedGroupAlgebra C H)
      (ZCCompletedDifferentialModule C ψ)
      inferInstance inferInstance (zcCompletedDifferentialModuleFreeTopology C ψ) :=
  ContinuousSMul.induced (zcDifferentialToFreeFoxCoordinates C ψ)

variable {A : Type*} [AddCommGroup A] [Module (ZCCompletedGroupAlgebra C H) A]

/-- The finite coordinate linear map attached to the generator values of a completed crossed
differential. -/
def zcFreeCrossedDifferentialCoordinateLift
    (delta : FreeGroup X → A) :
    ZCFreeFoxCoordinates C (X := X) (H := H) →ₗ[ZCCompletedGroupAlgebra C H] A where
  toFun v := ∑ x : X, v x • delta (FreeGroup.of x)
  map_add' v w := by
    simp only [Pi.add_apply, add_smul, Finset.sum_add_distrib]
  map_smul' r v := by
    simp only [Pi.smul_apply, smul_eq_mul, RingHom.id_apply, Finset.smul_sum, smul_smul]

omit [Fact (ProCGroups.FiniteGroupClass.FiniteOnly C)] [DecidableEq X] in
/-- Evaluation formula for the coordinate lift attached to generator values. -/
theorem zcFreeCrossedDifferentialCoordinateLift_apply
    (delta : FreeGroup X → A)
    (v : ZCFreeFoxCoordinates C (X := X) (H := H)) :
    zcFreeCrossedDifferentialCoordinateLift (H := H) C delta v =
      ∑ x : X, v x • delta (FreeGroup.of x) :=
  rfl

omit [Fact (ProCGroups.FiniteGroupClass.FiniteOnly C)] in
/-- The coordinate lift applied to the completed free derivative vector recovers the crossed
differential it represents. -/
theorem zcFreeCrossedDifferentialCoordinateLift_derivativeVector
    (ψ : FreeGroup X →* H) (delta : FreeGroup X → A)
    (hdelta : IsCrossedDifferential (zcCompletedGroupAlgebraScalar C ψ) delta)
    (w : FreeGroup X) :
    zcFreeCrossedDifferentialCoordinateLift (H := H) C delta
        (zcFreeGroupFoxDerivativeVector C ψ w) =
      delta w := by
  let L := zcFreeCrossedDifferentialCoordinateLift (H := H) C delta
  let beta : FreeGroup X → A := fun w => L (zcFreeGroupFoxDerivativeVector C ψ w)
  have hbeta :
      IsCrossedDifferential (zcCompletedGroupAlgebraScalar C ψ) beta :=
    IsCrossedDifferential.map_linear (zcFreeGroupFoxDerivativeVector_isCrossedDifferential C ψ) L
  have hbasis : ∀ x : X, beta (FreeGroup.of x) = delta (FreeGroup.of x) := by
    intro x
    simp only [zcFreeCrossedDifferentialCoordinateLift, LinearMap.coe_mk, AddHom.coe_mk,
  zcFreeGroupFoxDerivativeVector_of, Fintype.sum_single_smul, one_smul, beta, L]
  have hbeta_eq :
      beta =
        freeCrossedDifferentialWithCoeff
          (A := A) (zcCompletedGroupAlgebraScalar C ψ)
          (fun x : X => delta (FreeGroup.of x)) := by
    exact freeCrossedDifferentialWithCoeff_unique
      (A := A) (zcCompletedGroupAlgebraScalar C ψ)
      (fun x : X => delta (FreeGroup.of x)) beta hbeta hbasis
  have hdelta_eq :
      delta =
        freeCrossedDifferentialWithCoeff
          (A := A) (zcCompletedGroupAlgebraScalar C ψ)
          (fun x : X => delta (FreeGroup.of x)) := by
    exact freeCrossedDifferentialWithCoeff_unique
      (A := A) (zcCompletedGroupAlgebraScalar C ψ)
      (fun x : X => delta (FreeGroup.of x)) delta hdelta (by intro x; rfl)
  simpa [beta, L] using congrFun (hbeta_eq.trans hdelta_eq.symm) w

omit [Fact (ProCGroups.FiniteGroupClass.FiniteOnly C)] [DecidableEq X] in
/-- The coordinate lift is the representing universal-module lift composed with the
coordinate-to-module map. -/
theorem zcFreeCrossedDifferentialCoordinateLift_eq_completedLift_comp_coordinates
    (ψ : FreeGroup X →* H) (delta : FreeGroup X → A)
    (hdelta : IsCrossedDifferential (zcCompletedGroupAlgebraScalar C ψ) delta) :
    zcFreeCrossedDifferentialCoordinateLift (H := H) C delta =
      (zcCompletedDifferentialModuleLift (A := A) C ψ delta hdelta).comp
        (zcFreeFoxCoordinatesLinearMap C ψ) := by
  ext v
  simp only [zcFreeCrossedDifferentialCoordinateLift, LinearMap.coe_mk, AddHom.coe_mk,
  zcFreeFoxCoordinatesLinearMap, LinearMap.coe_comp, Function.comp_apply, map_sum, map_smul,
  zcCompletedDifferentialModuleLift_universal]

omit [Fact (ProCGroups.FiniteGroupClass.FiniteOnly C)] in
/-- The representing universal-module lift factors through completed Fox coordinates. -/
theorem zcCompletedDifferentialModuleLift_eq_coordinateLift_comp
    (ψ : FreeGroup X →* H) (delta : FreeGroup X → A)
    (hdelta : IsCrossedDifferential (zcCompletedGroupAlgebraScalar C ψ) delta) :
    zcCompletedDifferentialModuleLift (A := A) C ψ delta hdelta =
      (zcFreeCrossedDifferentialCoordinateLift (H := H) C delta).comp
        (zcDifferentialToFreeFoxCoordinates C ψ) := by
  apply zcCompletedDifferentialModuleHom_ext C ψ
  intro w
  simp only [zcCompletedDifferentialModuleLift_universal, LinearMap.comp_apply,
  zcDifferentialToFreeFoxCoordinates_universal,
  zcFreeCrossedDifferentialCoordinateLift_derivativeVector C ψ delta hdelta w]

variable [TopologicalSpace A]

omit [Fact (ProCGroups.FiniteGroupClass.FiniteOnly C)] in
variable {C} in
/-- Continuous representation theorem for finite-rank completed universal modules.

With the coordinate-induced topology on `ZCCompletedDifferentialModule`, the universal linear map
representing a completed crossed differential is continuous exactly when the finite coordinate
linear map determined by its generator values is continuous. -/
theorem continuous_zcCompletedDifferentialModuleLift_freeTopology_iff
    {ψ : FreeGroup X →* H} {delta : FreeGroup X → A}
    (hdelta : IsCrossedDifferential (zcCompletedGroupAlgebraScalar C ψ) delta) :
    @Continuous (ZCCompletedDifferentialModule C ψ) A
        (zcCompletedDifferentialModuleFreeTopology C ψ) inferInstance
        (zcCompletedDifferentialModuleLift (A := A) C ψ delta hdelta) ↔
      Continuous (zcFreeCrossedDifferentialCoordinateLift (H := H) C delta) := by
  constructor
  · intro h
    letI : TopologicalSpace (ZCCompletedDifferentialModule C ψ) :=
      zcCompletedDifferentialModuleFreeTopology C ψ
    have h' : Continuous (zcCompletedDifferentialModuleLift (A := A) C ψ delta hdelta) := h
    have hcoord :=
      continuous_zcFreeFoxCoordinatesLinearMap_freeTopology (X := X) (H := H) C ψ
    have heq :=
      zcFreeCrossedDifferentialCoordinateLift_eq_completedLift_comp_coordinates
        (A := A) C ψ delta hdelta
    simpa [heq, LinearMap.comp_apply] using h'.comp hcoord
  · intro h
    letI : TopologicalSpace (ZCCompletedDifferentialModule C ψ) :=
      zcCompletedDifferentialModuleFreeTopology C ψ
    have hcoord :=
      continuous_zcDifferentialToFreeFoxCoordinates_freeTopology (X := X) (H := H) C ψ
    have heq :=
      zcCompletedDifferentialModuleLift_eq_coordinateLift_comp
        (A := A) C ψ delta hdelta
    simpa [heq, LinearMap.comp_apply] using h.comp hcoord

section ContinuousLinearMapPackaging

variable (ψ : FreeGroup X →* H)

instance zcCompletedDifferentialModuleFreeTopologyInst :
    TopologicalSpace (ZCCompletedDifferentialModule C ψ) :=
  zcCompletedDifferentialModuleFreeTopology C ψ

/-- The completed coordinate map as a continuous linear map for the coordinate-induced topology. -/
def zcDifferentialToFreeFoxCoordinatesContinuousLinearMap :
    ZCCompletedDifferentialModule C ψ →L[ZCCompletedGroupAlgebra C H]
      ZCFreeFoxCoordinates C (X := X) (H := H) where
  toLinearMap := zcDifferentialToFreeFoxCoordinates C ψ
  cont := continuous_zcDifferentialToFreeFoxCoordinates_freeTopology (X := X) (H := H) C ψ

omit [Fact (ProCGroups.FiniteGroupClass.FiniteOnly C)] [Fintype X] in
/-- Evaluation of the continuous completed coordinate map. -/
@[simp]
theorem zcDifferentialToFreeFoxCoordinatesContinuousLinearMap_apply
    (m : ZCCompletedDifferentialModule C ψ) :
    zcDifferentialToFreeFoxCoordinatesContinuousLinearMap (X := X) (H := H) C ψ m =
      zcDifferentialToFreeFoxCoordinates C ψ m :=
  rfl

/-- The coordinate-to-universal map as a continuous linear map for the coordinate-induced
topology. -/
def zcFreeFoxCoordinatesContinuousLinearMap :
    ZCFreeFoxCoordinates C (X := X) (H := H) →L[ZCCompletedGroupAlgebra C H]
      ZCCompletedDifferentialModule C ψ where
  toLinearMap := zcFreeFoxCoordinatesLinearMap C ψ
  cont := continuous_zcFreeFoxCoordinatesLinearMap_freeTopology (X := X) (H := H) C ψ

omit [Fact (ProCGroups.FiniteGroupClass.FiniteOnly C)] in
/-- Evaluation of the continuous coordinate-to-universal map. -/
@[simp]
theorem zcFreeFoxCoordinatesContinuousLinearMap_apply
    (v : ZCFreeFoxCoordinates C (X := X) (H := H)) :
    zcFreeFoxCoordinatesContinuousLinearMap (X := X) (H := H) C ψ v =
      zcFreeFoxCoordinatesLinearMap C ψ v :=
  rfl

/-- A finite coordinate lift bundled as a continuous linear map, once its continuity is known. -/
def zcFreeCrossedDifferentialCoordinateContinuousLinearMap
    (delta : FreeGroup X → A)
    (hcont : Continuous (zcFreeCrossedDifferentialCoordinateLift (H := H) C delta)) :
    ZCFreeFoxCoordinates C (X := X) (H := H) →L[ZCCompletedGroupAlgebra C H] A where
  toLinearMap := zcFreeCrossedDifferentialCoordinateLift (H := H) C delta
  cont := hcont

omit [Fact (ProCGroups.FiniteGroupClass.FiniteOnly C)] [DecidableEq X] in
/-- Evaluation of the continuous coordinate lift attached to generator values. -/
@[simp]
theorem zcFreeCrossedDifferentialCoordinateContinuousLinearMap_apply
    (delta : FreeGroup X → A)
    (hcont : Continuous (zcFreeCrossedDifferentialCoordinateLift (H := H) C delta))
    (v : ZCFreeFoxCoordinates C (X := X) (H := H)) :
    zcFreeCrossedDifferentialCoordinateContinuousLinearMap
        (X := X) (H := H) (A := A) C delta hcont v =
      ∑ x : X, v x • delta (FreeGroup.of x) :=
  rfl

/-- The representing universal lift bundled as a continuous linear map, once its continuity for
the coordinate-induced topology is known. -/
def zcCompletedDifferentialModuleLiftContinuousLinearMap
    (delta : FreeGroup X → A)
    (hdelta : IsCrossedDifferential (zcCompletedGroupAlgebraScalar C ψ) delta)
    (hcont : Continuous (zcCompletedDifferentialModuleLift (A := A) C ψ delta hdelta)) :
    ZCCompletedDifferentialModule C ψ →L[ZCCompletedGroupAlgebra C H] A where
  toLinearMap := zcCompletedDifferentialModuleLift (A := A) C ψ delta hdelta
  cont := hcont

omit [Fact (ProCGroups.FiniteGroupClass.FiniteOnly C)] [Fintype X] in
/-- Evaluation of the continuous representing universal lift. -/
@[simp]
theorem zcCompletedDifferentialModuleLiftContinuousLinearMap_apply
    (delta : FreeGroup X → A)
    (hdelta : IsCrossedDifferential (zcCompletedGroupAlgebraScalar C ψ) delta)
    (hcont : Continuous (zcCompletedDifferentialModuleLift (A := A) C ψ delta hdelta))
    (m : ZCCompletedDifferentialModule C ψ) :
    zcCompletedDifferentialModuleLiftContinuousLinearMap
        (X := X) (H := H) (A := A) C ψ delta hdelta hcont m =
      zcCompletedDifferentialModuleLift (A := A) C ψ delta hdelta m :=
  rfl

/-- Continuous representation theorem packaged as a continuous linear map: it is enough to prove
continuity of the finite coordinate lift. -/
def zcCompletedDifferentialModuleLiftContinuousLinearMapOfCoordinate
    (delta : FreeGroup X → A)
    (hdelta : IsCrossedDifferential (zcCompletedGroupAlgebraScalar C ψ) delta)
    (hcoord : Continuous (zcFreeCrossedDifferentialCoordinateLift (H := H) C delta)) :
    ZCCompletedDifferentialModule C ψ →L[ZCCompletedGroupAlgebra C H] A :=
  zcCompletedDifferentialModuleLiftContinuousLinearMap
    (X := X) (H := H) (A := A) C ψ delta hdelta
    ((continuous_zcCompletedDifferentialModuleLift_freeTopology_iff
      (X := X) (H := H) (A := A) (ψ := ψ) (delta := delta) hdelta).2 hcoord)

omit [Fact (ProCGroups.FiniteGroupClass.FiniteOnly C)] in
/-- Evaluation of the continuous universal lift obtained from a continuous finite coordinate
lift. -/
@[simp]
theorem zcCompletedDifferentialModuleLiftContinuousLinearMapOfCoordinate_apply
    (delta : FreeGroup X → A)
    (hdelta : IsCrossedDifferential (zcCompletedGroupAlgebraScalar C ψ) delta)
    (hcoord : Continuous (zcFreeCrossedDifferentialCoordinateLift (H := H) C delta))
    (m : ZCCompletedDifferentialModule C ψ) :
    zcCompletedDifferentialModuleLiftContinuousLinearMapOfCoordinate
        (X := X) (H := H) (A := A) C ψ delta hdelta hcoord m =
      zcCompletedDifferentialModuleLift (A := A) C ψ delta hdelta m :=
  rfl

end ContinuousLinearMapPackaging

end FreeGroupUniversalTopology

end

end FoxDifferential
