import FoxDifferential.Completed.FreeProC.StageApproximation
import FoxDifferential.Completed.FiniteStage.RelationSubmodule
import FoxDifferential.Completed.FiniteStage.RelationIdealDerivative

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/FoxDifferential/Completed/FreeProC/RelationSubmoduleApproximation.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Completed density from finite-stage relation-submodule exactness

The finite-stage semidirect approximation theorem requires set-level coverage by source-kernel Fox
derivatives.  This file feeds it from a more structured finite-stage input:

* module exactness: `ker ∂` is contained in the submodule generated by relation boundaries.

The finite relation-boundary image is already stable under the target group algebra, so the
generated submodule is an honest source-kernel derivative image.
-/

namespace FoxDifferential

noncomputable section

universe u v

section CompletedFoxRelationSubmoduleExact

open scoped Topology

variable {ProC : ProCGroups.ProC.ProCGroupPredicate}
variable {X H : Type u}
variable [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
variable [DecidableEq X]
variable [TopologicalSpace (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
variable [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]

omit [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
/-- Completed Fox density from finite-stage relation-submodule exactness. -/
theorem boundaryCycles_subset_kernelClosure_of_relSubmoduleExact
    [Fintype X] (φ : X → H)
    {J : Type v}
    (Nstage : J → Subgroup (FreeGroup X))
    [∀ j, (Nstage j).Normal]
    (nstage : J → ℕ)
    (π : ∀ j : J,
      ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H →*
        FiniteFoxStageSemidirect (X := X) (Nstage j) (nstage j))
    (hbasis :
      HasLeftQuotientKernelNeighbourhoodBasis
        (Y := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) π)
    (hboundary_stage :
      ∀ y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H,
        y ∈ freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ →
          ∀ j : J,
            π j y ∈ finiteFoxStageSemidirectBoundaryCycleSet
              (X := X) (Nstage j) (nstage j))
    (hstage_module_exact :
      ∀ j : J,
        finiteFoxStageRelationBoundaryModuleExact
          (X := X) (Nstage j) (nstage j))
    (hNstage_kernel :
      ∀ j : J, ∀ {w : FreeGroup X}, w ∈ Nstage j → FreeGroup.lift φ w = 1)
    (hkernel_word_projection :
      ∀ j : J, ∀ w : FreeGroup X, w ∈ Nstage j →
        π j (freeProCZCCompletedFoxSemidirectKernelWordPoint (ProC := ProC) φ w) =
          finiteFoxStageSemidirectKernelWordPoint (X := X) (Nstage j) (nstage j) w) :
    freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ ⊆
      closure (freeProCZCCompletedFoxSemidirectKernelCycleSet (ProC := ProC) φ) := by
  refine
    freeProCZCFoxBoundaryCycles_subset_closure_kernelCycleSet_of_finiteStage_semi_exact
      (ProC := ProC) φ Nstage nstage π hbasis hboundary_stage ?_
      hNstage_kernel hkernel_word_projection
  intro j
  exact finiteFoxStageBoundaryCyclesCoveredBySourceKernel_of_relationBoundaryModuleExact
    (X := X) (Nstage j) (nstage j) (hstage_module_exact j)

/-- The same finite relation-submodule input places completed boundary cycles in the closed
generated Fox graph target. -/
theorem freeProCZCFoxBoundaryCycles_subset_closedGenTarget_of_finiteStage_relSubmodule_exact
    [Fintype X] (φ : X → H)
    {J : Type v}
    (Nstage : J → Subgroup (FreeGroup X))
    [∀ j, (Nstage j).Normal]
    (nstage : J → ℕ)
    (π : ∀ j : J,
      ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H →*
        FiniteFoxStageSemidirect (X := X) (Nstage j) (nstage j))
    (hbasis :
      HasLeftQuotientKernelNeighbourhoodBasis
        (Y := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) π)
    (hboundary_stage :
      ∀ y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H,
        y ∈ freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ →
          ∀ j : J,
            π j y ∈ finiteFoxStageSemidirectBoundaryCycleSet
              (X := X) (Nstage j) (nstage j))
    (hstage_module_exact :
      ∀ j : J,
        finiteFoxStageRelationBoundaryModuleExact
          (X := X) (Nstage j) (nstage j))
    (hNstage_kernel :
      ∀ j : J, ∀ {w : FreeGroup X}, w ∈ Nstage j → FreeGroup.lift φ w = 1)
    (hkernel_word_projection :
      ∀ j : J, ∀ w : FreeGroup X, w ∈ Nstage j →
        π j (freeProCZCCompletedFoxSemidirectKernelWordPoint (ProC := ProC) φ w) =
          finiteFoxStageSemidirectKernelWordPoint (X := X) (Nstage j) (nstage j) w) :
    freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ ⊆
      ((freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) : Set
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) := by
  exact
    freeProCZCFoxBoundaryCycles_subset_closedGenTarget_of_density
      (ProC := ProC) φ
      (boundaryCycles_subset_kernelClosure_of_relSubmoduleExact
        (ProC := ProC) φ Nstage nstage π hbasis hboundary_stage
        hstage_module_exact hNstage_kernel hkernel_word_projection)

omit [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
/-- Completed Fox density from the source-boundary relation-ideal reduction at every finite stage.

This is the next attack route below relation-submodule exactness: instead of assuming finite
module exactness directly, it suffices to prove that source-coordinate lifts whose source boundary
lies in the explicit relation augmentation ideal project to relation-boundary vectors. -/
theorem boundaryCycles_subset_kernelClosure_of_sourceBoundaryReduction
    [Fintype X] (φ : X → H)
    {J : Type v}
    (Nstage : J → Subgroup (FreeGroup X))
    [∀ j, (Nstage j).Normal]
    (nstage : J → ℕ)
    (π : ∀ j : J,
      ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H →*
        FiniteFoxStageSemidirect (X := X) (Nstage j) (nstage j))
    (hbasis :
      HasLeftQuotientKernelNeighbourhoodBasis
        (Y := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) π)
    (hboundary_stage :
      ∀ y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H,
        y ∈ freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ →
          ∀ j : J,
            π j y ∈ finiteFoxStageSemidirectBoundaryCycleSet
              (X := X) (Nstage j) (nstage j))
    (hstage_reduce :
      ∀ j : J,
        finiteFoxStageSourceBoundaryRelationIdealReduction
          (X := X) (Nstage j) (nstage j))
    (hNstage_kernel :
      ∀ j : J, ∀ {w : FreeGroup X}, w ∈ Nstage j → FreeGroup.lift φ w = 1)
    (hkernel_word_projection :
      ∀ j : J, ∀ w : FreeGroup X, w ∈ Nstage j →
        π j (freeProCZCCompletedFoxSemidirectKernelWordPoint (ProC := ProC) φ w) =
          finiteFoxStageSemidirectKernelWordPoint (X := X) (Nstage j) (nstage j) w) :
    freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ ⊆
      closure (freeProCZCCompletedFoxSemidirectKernelCycleSet (ProC := ProC) φ) := by
  refine
    boundaryCycles_subset_kernelClosure_of_relSubmoduleExact
      (ProC := ProC) φ Nstage nstage π hbasis hboundary_stage ?_
      hNstage_kernel hkernel_word_projection
  intro j
  exact finiteFoxStageRelationBoundaryModuleExact_of_sourceBoundaryRelReduction
    (X := X) (Nstage j) (nstage j) (hstage_reduce j)

/-- The source-boundary relation-ideal route also places completed boundary cycles inside the
closed-generated Fox graph target. -/
theorem boundaryCycles_subset_closedGenTarget_of_sourceBoundaryReduction
    [Fintype X] (φ : X → H)
    {J : Type v}
    (Nstage : J → Subgroup (FreeGroup X))
    [∀ j, (Nstage j).Normal]
    (nstage : J → ℕ)
    (π : ∀ j : J,
      ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H →*
        FiniteFoxStageSemidirect (X := X) (Nstage j) (nstage j))
    (hbasis :
      HasLeftQuotientKernelNeighbourhoodBasis
        (Y := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) π)
    (hboundary_stage :
      ∀ y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H,
        y ∈ freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ →
          ∀ j : J,
            π j y ∈ finiteFoxStageSemidirectBoundaryCycleSet
              (X := X) (Nstage j) (nstage j))
    (hstage_reduce :
      ∀ j : J,
        finiteFoxStageSourceBoundaryRelationIdealReduction
          (X := X) (Nstage j) (nstage j))
    (hNstage_kernel :
      ∀ j : J, ∀ {w : FreeGroup X}, w ∈ Nstage j → FreeGroup.lift φ w = 1)
    (hkernel_word_projection :
      ∀ j : J, ∀ w : FreeGroup X, w ∈ Nstage j →
        π j (freeProCZCCompletedFoxSemidirectKernelWordPoint (ProC := ProC) φ w) =
          finiteFoxStageSemidirectKernelWordPoint (X := X) (Nstage j) (nstage j) w) :
    freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ ⊆
      ((freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) : Set
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) := by
  exact
    freeProCZCFoxBoundaryCycles_subset_closedGenTarget_of_density
      (ProC := ProC) φ
      (boundaryCycles_subset_kernelClosure_of_sourceBoundaryReduction
        (ProC := ProC) φ Nstage nstage π hbasis hboundary_stage
        hstage_reduce hNstage_kernel hkernel_word_projection)



section
omit [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
/-- Completed Fox density from the finite-stage relation-ideal derivative theorem.

The finite-stage source-boundary relation-ideal reduction is supplied by
`RelationIdealDerivative.lean`.  The remaining inputs are the completion and approximation data:
the quotient-kernel neighbourhood basis, compatibility of completed boundary cycles with finite
stages, and compatibility of honest kernel-word points with their finite-stage projections. -/
theorem freeProCZCFoxBoundaryCycles_subset_closure_kernelCycleSet_of_finiteStage_relDeriv
    [Fintype X] (φ : X → H)
    {J : Type v}
    (Nstage : J → Subgroup (FreeGroup X))
    [∀ j, (Nstage j).Normal]
    (nstage : J → ℕ)
    (π : ∀ j : J,
      ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H →*
        FiniteFoxStageSemidirect (X := X) (Nstage j) (nstage j))
    (hbasis :
      HasLeftQuotientKernelNeighbourhoodBasis
        (Y := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) π)
    (hboundary_stage :
      ∀ y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H,
        y ∈ freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ →
          ∀ j : J,
            π j y ∈ finiteFoxStageSemidirectBoundaryCycleSet
              (X := X) (Nstage j) (nstage j))
    (hNstage_kernel :
      ∀ j : J, ∀ {w : FreeGroup X}, w ∈ Nstage j → FreeGroup.lift φ w = 1)
    (hkernel_word_projection :
      ∀ j : J, ∀ w : FreeGroup X, w ∈ Nstage j →
        π j (freeProCZCCompletedFoxSemidirectKernelWordPoint (ProC := ProC) φ w) =
          finiteFoxStageSemidirectKernelWordPoint (X := X) (Nstage j) (nstage j) w) :
    freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ ⊆
      closure (freeProCZCCompletedFoxSemidirectKernelCycleSet (ProC := ProC) φ) := by
  refine
    boundaryCycles_subset_kernelClosure_of_sourceBoundaryReduction
      (ProC := ProC) φ Nstage nstage π hbasis hboundary_stage ?_
      hNstage_kernel hkernel_word_projection
  intro j
  exact finiteFoxStageSourceBoundaryRelationIdealReduction_of_relationIdeal_derivatives
    (X := X) (Nstage j) (nstage j)

end

/-- Completed boundary cycles lie in the closed-generated Fox graph target using the finite-stage
relation-ideal derivative theorem. -/
theorem freeProCZCFoxBoundaryCycles_subset_closedGenTarget_of_finiteStage_relDeriv
    [Fintype X] (φ : X → H)
    {J : Type v}
    (Nstage : J → Subgroup (FreeGroup X))
    [∀ j, (Nstage j).Normal]
    (nstage : J → ℕ)
    (π : ∀ j : J,
      ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H →*
        FiniteFoxStageSemidirect (X := X) (Nstage j) (nstage j))
    (hbasis :
      HasLeftQuotientKernelNeighbourhoodBasis
        (Y := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) π)
    (hboundary_stage :
      ∀ y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H,
        y ∈ freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ →
          ∀ j : J,
            π j y ∈ finiteFoxStageSemidirectBoundaryCycleSet
              (X := X) (Nstage j) (nstage j))
    (hNstage_kernel :
      ∀ j : J, ∀ {w : FreeGroup X}, w ∈ Nstage j → FreeGroup.lift φ w = 1)
    (hkernel_word_projection :
      ∀ j : J, ∀ w : FreeGroup X, w ∈ Nstage j →
        π j (freeProCZCCompletedFoxSemidirectKernelWordPoint (ProC := ProC) φ w) =
          finiteFoxStageSemidirectKernelWordPoint (X := X) (Nstage j) (nstage j) w) :
    freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ ⊆
      ((freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) : Set
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) := by
  exact
    freeProCZCFoxBoundaryCycles_subset_closedGenTarget_of_density
      (ProC := ProC) φ
      (freeProCZCFoxBoundaryCycles_subset_closure_kernelCycleSet_of_finiteStage_relDeriv
        (ProC := ProC) φ Nstage nstage π hbasis hboundary_stage
        hNstage_kernel hkernel_word_projection)

end CompletedFoxRelationSubmoduleExact

end

end FoxDifferential
