import FoxDifferential.Completed.Semidirect
import ProCGroups.FreeProC.Basic

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/FoxDifferential/Completed/FreeProC/SemidirectLift.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Free pro-C completed Fox calculus

Free pro-C sources are treated through completed Fox derivatives, stage projections, density arguments, and semidirect lift formulas.
-/
namespace FoxDifferential

noncomputable section

open ProCGroups.FreeProC

universe u


variable {ProC : ProCGroups.ProC.ProCGroupPredicate}
variable {X F H : Type u}
variable [TopologicalSpace X]
variable [Group F] [TopologicalSpace F] [IsTopologicalGroup F]
variable [DecidableEq X]
variable [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
variable [TopologicalSpace (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
variable [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]

/-- The generator map into the completed Fox semidirect target attached to a basis-value map
`φ : X -> H`. -/
def freeProCZCCompletedFoxSemidirectGenerator (φ : X → H) :
    X → ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H :=
  fun x =>
    { left := Pi.single x (1 : ZCCompletedGroupAlgebra ProC.finiteQuotientClass H)
      right := φ x }

omit [TopologicalSpace X] [TopologicalSpace (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
  [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
/-- The generator map has the expected left coordinate. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectGenerator_left
    (φ : X → H) (x : X) :
    (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ x).left =
      Pi.single x (1 : ZCCompletedGroupAlgebra ProC.finiteQuotientClass H) :=
  rfl

omit [TopologicalSpace X] [TopologicalSpace (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
  [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
/-- The generator map has the expected right coordinate. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectGenerator_right
    (φ : X → H) (x : X) :
    (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ x).right = φ x :=
  rfl

omit [TopologicalSpace X]
  [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
/-- For a finite generator set, the completed Fox semidirect generator map automatically
converges to `1`. -/
theorem freeProCZCCompletedFoxSemidirectGenerator_convergesToOne_of_finite
    [Finite X] (φ : X → H) :
    FamilyConvergesToOne
      (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
      (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ) := by
  exact FamilyConvergesToOne.of_finite_domain
    (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
    (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)

omit [TopologicalSpace X] in
/-- The closed subgroup of the completed Fox semidirect target generated by the Fox graph
generators. -/
def freeProCZCCompletedFoxSemidirectClosedGeneratedTarget (φ : X → H) :
    ClosedSubgroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) :=
  ProCGroups.Generation.closedSubgroupGenerated
    (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
    (Set.range (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))

omit [TopologicalSpace X] in
/-- If the ambient completed Fox semidirect target is a pro-`C` group, then the closed target
generated by the Fox graph generators is pro-`C` by closed-subgroup permanence. -/
theorem freeProCZCCompletedFoxSemidirectClosedGeneratedTarget_proCGroup
    [ProC.HasFiniteQuotientMelnikovFormation] [ProC.HasFiniteQuotientHereditary]
    [ProC.DeterminedByFiniteQuotients]
    [ProCGroups.ProC.ProCGroup ProC
      (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
    (φ : X → H) :
    ProCGroups.ProC.ProCGroup ProC
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) :=
  ProCGroups.ProC.ProCGroup.of_closedSubgroup ProC
    (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget (ProC := ProC) φ)

omit [TopologicalSpace X] in
/-- Pro-`C` predicate form of
`freeProCZCCompletedFoxSemidirectClosedGeneratedTarget_proCGroup`. -/
theorem freeProCZCCompletedFoxSemidirectClosedGeneratedTarget_proC
    [ProC.HasFiniteQuotientMelnikovFormation] [ProC.HasFiniteQuotientHereditary]
    [ProC.DeterminedByFiniteQuotients]
    [ProCGroups.ProC.ProCGroup ProC
      (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
    (φ : X → H) :
    ProC
      (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))) :=
  (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget_proCGroup
    (ProC := ProC) φ).isProC

omit [TopologicalSpace X] in
/-- The Fox graph generator map, with codomain restricted to the closed subgroup it generates. -/
def freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (φ : X → H) :
    X →
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) :=
  ProCGroups.Generation.closedSubgroupGeneratedMap
    (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
    (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)

omit [TopologicalSpace X] in
@[simp]
theorem freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator_val
    (φ : X → H) (x : X) :
    (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ x :
      ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) =
      freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ x :=
  rfl

omit [TopologicalSpace X] in
/-- Each Fox graph generator belongs to the closed subgroup generated by the Fox graph. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectGenerator_mem_closedGeneratedTarget
    (φ : X → H) (x : X) :
    freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ x ∈
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) := by
  simpa using
    (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ x).2

omit [TopologicalSpace X] in
/-- The completed semidirect Fox graph of every abstract free-group word lies in the closed
subgroup generated by the Fox graph generators. -/
theorem zcCompletedFoxSemidirectLift_freeGroupLift_mem_closedGeneratedTarget
    (φ : X → H) (w : FreeGroup X) :
    zcCompletedFoxSemidirectLift ProC.finiteQuotientClass (FreeGroup.lift φ) w ∈
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) := by
  induction w using FreeGroup.induction_on with
  | C1 =>
      simp only [map_one, one_mem]
  | of x =>
      have hpoint :
          zcCompletedFoxSemidirectLift ProC.finiteQuotientClass
              (FreeGroup.lift φ) (FreeGroup.of x) =
            freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ x := by
        simp only [zcCompletedFoxSemidirectLift, FreeGroup.lift_apply_of, freeProCZCCompletedFoxSemidirectGenerator]
      rw [hpoint]
      exact
        freeProCZCCompletedFoxSemidirectGenerator_mem_closedGeneratedTarget
          (ProC := ProC) φ x
  | inv_of x hx =>
      simpa [map_inv] using
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)).inv_mem hx
  | mul u v hu hv =>
      simpa [map_mul] using
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)).mul_mem hu hv

omit [TopologicalSpace X] in
/-- Equivalently, the pair consisting of the completed free Fox derivative vector and the target
word value belongs to the closed generated Fox graph. -/
theorem freeProCZCFoxClosedGenTarget_mem_of_freeFoxDerivVec
    (φ : X → H) (w : FreeGroup X) :
    ({ left :=
        zcFreeGroupFoxDerivativeVector ProC.finiteQuotientClass (FreeGroup.lift φ) w,
       right := FreeGroup.lift φ w } :
      ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) ∈
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) := by
  simpa [zcCompletedFoxSemidirectLift_eq] using
    zcCompletedFoxSemidirectLift_freeGroupLift_mem_closedGeneratedTarget
      (ProC := ProC) φ w

omit [TopologicalSpace X] in
/-- If an abstract free-group word maps trivially to the target group, its completed Fox
derivative vector gives a genuine cycle point `(D w, 1)` in the closed generated Fox graph. -/
theorem freeProCZCFoxClosedGenTarget_mem_of_freeFoxDerivVec_kernel
    (φ : X → H) {w : FreeGroup X} (hw : FreeGroup.lift φ w = 1) :
    ({ left :=
        zcFreeGroupFoxDerivativeVector ProC.finiteQuotientClass (FreeGroup.lift φ) w,
       right := (1 : H) } :
      ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) ∈
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) := by
  simpa [hw] using
    freeProCZCFoxClosedGenTarget_mem_of_freeFoxDerivVec
      (ProC := ProC) φ w

omit [TopologicalSpace X] in
/-- The algebraic kernel-word cycle points in the completed Fox semidirect product.

These are the points `(D w, 1)` obtained from abstract free-group words whose target value is
`1`.  The remaining density step for the completed Fox cycles is formulated using the closure of
this set. -/
def freeProCZCCompletedFoxSemidirectKernelCycleSet (φ : X → H) :
    Set (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) :=
  { y | ∃ w : FreeGroup X, FreeGroup.lift φ w = 1 ∧
      y =
        ({ left :=
            zcFreeGroupFoxDerivativeVector ProC.finiteQuotientClass
              (FreeGroup.lift φ) w,
           right := (1 : H) } :
          ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) }


omit [TopologicalSpace X] in
/-- The completed Fox boundary-cycle set inside the completed Fox semidirect product.

Its points are exactly the pairs `(v, 1)` whose coordinate vector is killed by the source-shaped
completed Fox boundary.  The remaining density step can be stated as saying that this boundary
cycle set is contained in the closure of the algebraic kernel-word cycle set. -/
def freeProCZCCompletedFoxSemidirectBoundaryCycleSet [Fintype X] (φ : X → H) :
    Set (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) :=
  { y | y.right = 1 ∧
      zcFreeGroupFoxBoundary ProC.finiteQuotientClass (FreeGroup.lift φ) y.left = 0 }

/-! ## Graph-word points

Finite quotient stages naturally produce words whose image is trivial only after applying the
finite right quotient.  The completed approximant is therefore the genuine graph point
`(D w, φ(w))`, not the kernel-word point `(D w, 1)`.
-/

omit [TopologicalSpace X]
  [TopologicalSpace (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
  [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
/-- The genuine completed Fox graph point `(D w, φ(w))` attached to an abstract free-group word. -/
def freeProCZCCompletedFoxSemidirectGraphWordPoint (φ : X → H) (w : FreeGroup X) :
    ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H :=
  { left :=
      zcFreeGroupFoxDerivativeVector ProC.finiteQuotientClass (FreeGroup.lift φ) w,
    right := FreeGroup.lift φ w }

omit [TopologicalSpace X]
  [TopologicalSpace (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
  [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
@[simp]
theorem freeProCZCCompletedFoxSemidirectGraphWordPoint_left
    (φ : X → H) (w : FreeGroup X) :
    (freeProCZCCompletedFoxSemidirectGraphWordPoint (ProC := ProC) φ w).left =
      zcFreeGroupFoxDerivativeVector ProC.finiteQuotientClass (FreeGroup.lift φ) w :=
  rfl

omit [TopologicalSpace X]
  [TopologicalSpace (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
  [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
@[simp]
theorem freeProCZCCompletedFoxSemidirectGraphWordPoint_right
    (φ : X → H) (w : FreeGroup X) :
    (freeProCZCCompletedFoxSemidirectGraphWordPoint (ProC := ProC) φ w).right =
      FreeGroup.lift φ w :=
  rfl

omit [TopologicalSpace X]
  [TopologicalSpace (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
  [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
/-- The set of all completed Fox graph points attached to abstract free-group words. -/
def freeProCZCCompletedFoxSemidirectGraphWordSet (φ : X → H) :
    Set (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) :=
  { y | ∃ w : FreeGroup X,
      y = freeProCZCCompletedFoxSemidirectGraphWordPoint (ProC := ProC) φ w }

omit [TopologicalSpace X]
  [TopologicalSpace (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
  [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
theorem mem_freeProCZCCompletedFoxSemidirectGraphWordSet_iff
    (φ : X → H)
    (y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) :
    y ∈ freeProCZCCompletedFoxSemidirectGraphWordSet (ProC := ProC) φ ↔
      ∃ w : FreeGroup X,
        y = freeProCZCCompletedFoxSemidirectGraphWordPoint (ProC := ProC) φ w := by
  rfl

omit [TopologicalSpace X] in
/-- Every completed graph-word point lies in the closed subgroup generated by the Fox graph
generators. -/
theorem freeProCZCCompletedFoxSemidirectGraphWordPoint_mem_closedGeneratedTarget
    (φ : X → H) (w : FreeGroup X) :
    freeProCZCCompletedFoxSemidirectGraphWordPoint (ProC := ProC) φ w ∈
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) := by
  simpa [freeProCZCCompletedFoxSemidirectGraphWordPoint] using
    freeProCZCFoxClosedGenTarget_mem_of_freeFoxDerivVec
      (ProC := ProC) φ w

omit [TopologicalSpace X] in
/-- The graph-word set lies in the closed subgroup generated by the Fox graph generators. -/
theorem freeProCZCCompletedFoxSemidirectGraphWordSet_subset_closedGeneratedTarget
    (φ : X → H) :
    freeProCZCCompletedFoxSemidirectGraphWordSet (ProC := ProC) φ ⊆
      ((freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) : Set
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) := by
  rintro y ⟨w, rfl⟩
  exact freeProCZCCompletedFoxSemidirectGraphWordPoint_mem_closedGeneratedTarget
    (ProC := ProC) φ w

omit [TopologicalSpace X] in
/-- The closure of the graph-word set remains in the closed generated Fox graph target. -/
theorem closure_freeProCZCFoxSemiGraphWordSet_subset_closedGenTarget
    (φ : X → H) :
    closure (freeProCZCCompletedFoxSemidirectGraphWordSet (ProC := ProC) φ) ⊆
      ((freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) : Set
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) :=
  closure_minimal
    (freeProCZCCompletedFoxSemidirectGraphWordSet_subset_closedGeneratedTarget
      (ProC := ProC) φ)
    (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget (ProC := ProC) φ).isClosed'

omit [TopologicalSpace X] in
/-- Graph-word density places every completed boundary cycle in the closed generated Fox graph
target. -/
theorem freeProCZCFoxBoundaryCycles_subset_closedGenTarget_of_graphWord_density
    [Fintype X] (φ : X → H)
    (hdensity :
      freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ ⊆
        closure (freeProCZCCompletedFoxSemidirectGraphWordSet (ProC := ProC) φ)) :
    freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ ⊆
      ((freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) : Set
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) := by
  exact subset_trans hdensity
    (closure_freeProCZCFoxSemiGraphWordSet_subset_closedGenTarget
      (ProC := ProC) φ)

omit [TopologicalSpace X] [TopologicalSpace (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
/-- A kernel word has zero completed Fox boundary.

This is the completed Fox fundamental formula applied before taking closures: if
`w` maps to `1`, then the Euler boundary of its Fox derivative vector is zero. -/
theorem zcFreeGroupFoxBoundary_zcFreeGroupFoxDerivativeVector_of_kernel
    [Fintype X] (φ : X → H) {w : FreeGroup X}
    (hw : FreeGroup.lift φ w = 1) :
    zcFreeGroupFoxBoundary ProC.finiteQuotientClass (FreeGroup.lift φ)
        (zcFreeGroupFoxDerivativeVector ProC.finiteQuotientClass (FreeGroup.lift φ) w) = 0 := by
  rw [zcFreeGroupFoxBoundary_derivativeVector]
  exact zcCompletedGroupAlgebraBoundary_eq_zero_of_mem_ker
    (C := ProC.finiteQuotientClass) (ψ := FreeGroup.lift φ) hw

omit [TopologicalSpace X] in
omit [TopologicalSpace (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
/-- Every algebraic kernel-word cycle point is an actual completed Fox boundary cycle. -/
theorem freeProCZCCompletedFoxSemidirectKernelCycleSet_subset_boundaryCycleSet
    [Fintype X] (φ : X → H) :
    freeProCZCCompletedFoxSemidirectKernelCycleSet (ProC := ProC) φ ⊆
      freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ := by
  intro y hy
  rcases hy with ⟨w, hw, rfl⟩
  constructor
  · rfl
  · exact zcFreeGroupFoxBoundary_zcFreeGroupFoxDerivativeVector_of_kernel
      (ProC := ProC) φ hw

omit [TopologicalSpace X] in
/-- The boundary-cycle points form an honest subgroup of the completed Fox semidirect product.

Algebraically this is the additive kernel of the source-shaped completed Fox boundary, embedded
as the right-trivial subgroup `(v, 1)`. -/
def freeProCZCCompletedFoxSemidirectBoundaryCycleSubgroup
    [Fintype X] (φ : X → H) :
    Subgroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) where
  carrier := freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ
  one_mem' := by
    constructor
    · rfl
    · simp only [ZCCompletedFoxSemidirect.one_left, map_zero]
  mul_mem' := by
    intro a b ha hb
    rcases ha with ⟨ha_right, ha_boundary⟩
    rcases hb with ⟨hb_right, hb_boundary⟩
    constructor
    · simp only [ZCCompletedFoxSemidirect.mul_right, ha_right, hb_right, mul_one]
    · calc
        zcFreeGroupFoxBoundary ProC.finiteQuotientClass (FreeGroup.lift φ) (a * b).left
            = zcFreeGroupFoxBoundary ProC.finiteQuotientClass (FreeGroup.lift φ)
                (a.left + b.left) := by
                simp only [ZCCompletedFoxSemidirect.mul_left, ha_right, map_one, one_smul, map_add]
        _ = zcFreeGroupFoxBoundary ProC.finiteQuotientClass (FreeGroup.lift φ) a.left +
              zcFreeGroupFoxBoundary ProC.finiteQuotientClass (FreeGroup.lift φ) b.left := by
                rw [map_add]
        _ = 0 := by
                simp only [ha_boundary, hb_boundary, add_zero]
  inv_mem' := by
    intro a ha
    rcases ha with ⟨ha_right, ha_boundary⟩
    constructor
    · simp only [ZCCompletedFoxSemidirect.inv_right, ha_right, inv_one]
    · calc
        zcFreeGroupFoxBoundary ProC.finiteQuotientClass (FreeGroup.lift φ) a⁻¹.left
            = zcFreeGroupFoxBoundary ProC.finiteQuotientClass (FreeGroup.lift φ) (-a.left) := by
                simp only [ZCCompletedFoxSemidirect.inv_left, ha_right, inv_one, map_one, one_smul, map_neg]
        _ = -zcFreeGroupFoxBoundary ProC.finiteQuotientClass (FreeGroup.lift φ) a.left := by
                rw [map_neg]
        _ = 0 := by
                simp only [ha_boundary, neg_zero]

omit [TopologicalSpace X] [DecidableEq X] [TopologicalSpace (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
@[simp]
theorem freeProCZCCompletedFoxSemidirectBoundaryCycleSubgroup_coe
    [Fintype X] (φ : X → H) :
    ((freeProCZCCompletedFoxSemidirectBoundaryCycleSubgroup
      (ProC := ProC) φ : Subgroup
        (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) : Set
        (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) =
      freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ :=
  rfl

omit [TopologicalSpace X] [DecidableEq X] [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
/-- The completed Fox boundary-cycle set is closed whenever the two semidirect projections and the
source-shaped completed Fox boundary are continuous.

This is the topological half of the density frontier: algebraic kernel-word cycles stay inside
actual boundary cycles after taking closure. -/
theorem isClosed_freeProCZCCompletedFoxSemidirectBoundaryCycleSet_of_continuous
    [Fintype X] [T1Space H]
    [TopologicalSpace (ZCCompletedGroupAlgebra ProC.finiteQuotientClass H)]
    [T1Space (ZCCompletedGroupAlgebra ProC.finiteQuotientClass H)]
    (φ : X → H)
    (hleft :
      Continuous
        (fun y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H => y.left))
    (hright :
      Continuous
        (fun y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H => y.right))
    (hboundary :
      Continuous
        (zcFreeGroupFoxBoundary ProC.finiteQuotientClass (FreeGroup.lift φ))) :
    IsClosed (freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ) := by
  have hright_closed :
      IsClosed
        ((fun y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H => y.right) ⁻¹'
          ({1} : Set H)) :=
    isClosed_singleton.preimage hright
  have hboundary_closed :
      IsClosed
        ((fun y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H =>
            zcFreeGroupFoxBoundary ProC.finiteQuotientClass (FreeGroup.lift φ) y.left) ⁻¹'
          ({0} : Set (ZCCompletedGroupAlgebra ProC.finiteQuotientClass H))) :=
    isClosed_singleton.preimage (hboundary.comp hleft)
  simpa [freeProCZCCompletedFoxSemidirectBoundaryCycleSet] using
    hright_closed.inter hboundary_closed

omit [TopologicalSpace X] in
omit [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
/-- Closure of algebraic kernel-word cycle points remains inside the actual completed Fox
boundary-cycle set, assuming the displayed boundary-cycle set is topologically closed. -/
theorem closure_freeProCZCFoxSemiKernelCycleSet_subset_boundaryCycleSet_of_continuous
    [Fintype X] [T1Space H]
    [TopologicalSpace (ZCCompletedGroupAlgebra ProC.finiteQuotientClass H)]
    [T1Space (ZCCompletedGroupAlgebra ProC.finiteQuotientClass H)]
    (φ : X → H)
    (hleft :
      Continuous
        (fun y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H => y.left))
    (hright :
      Continuous
        (fun y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H => y.right))
    (hboundary :
      Continuous
        (zcFreeGroupFoxBoundary ProC.finiteQuotientClass (FreeGroup.lift φ))) :
    closure (freeProCZCCompletedFoxSemidirectKernelCycleSet (ProC := ProC) φ) ⊆
      freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ := by
  exact
    closure_minimal
      (freeProCZCCompletedFoxSemidirectKernelCycleSet_subset_boundaryCycleSet
        (ProC := ProC) φ)
      (isClosed_freeProCZCCompletedFoxSemidirectBoundaryCycleSet_of_continuous
        (ProC := ProC) φ hleft hright hboundary)

omit [TopologicalSpace X] in
omit [IsTopologicalGroup (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)] in
/-- With the continuity inputs in place, the remaining density statement is equivalently the
claim that the closure of algebraic kernel-word cycle points is exactly the boundary-cycle set. -/
theorem closure_freeProCZCFoxSemiKernelCycleSet_eq_boundaryCycleSet_iff_density
    [Fintype X] [T1Space H]
    [TopologicalSpace (ZCCompletedGroupAlgebra ProC.finiteQuotientClass H)]
    [T1Space (ZCCompletedGroupAlgebra ProC.finiteQuotientClass H)]
    (φ : X → H)
    (hleft :
      Continuous
        (fun y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H => y.left))
    (hright :
      Continuous
        (fun y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H => y.right))
    (hboundary :
      Continuous
        (zcFreeGroupFoxBoundary ProC.finiteQuotientClass (FreeGroup.lift φ))) :
    closure (freeProCZCCompletedFoxSemidirectKernelCycleSet (ProC := ProC) φ) =
        freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ ↔
      freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ ⊆
        closure (freeProCZCCompletedFoxSemidirectKernelCycleSet (ProC := ProC) φ) := by
  constructor
  · intro h y hy
    simpa [h] using hy
  · intro hdensity
    ext y
    constructor
    · intro hy
      exact
        closure_freeProCZCFoxSemiKernelCycleSet_subset_boundaryCycleSet_of_continuous
          (ProC := ProC) φ hleft hright hboundary hy
    · intro hy
      exact hdensity hy

omit [TopologicalSpace X] in
/-- Every algebraic kernel-word cycle point lies in the closed generated Fox graph target. -/
theorem freeProCZCCompletedFoxSemidirectKernelCycleSet_subset_closedGeneratedTarget
    (φ : X → H) :
    freeProCZCCompletedFoxSemidirectKernelCycleSet (ProC := ProC) φ ⊆
      ((freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) : Set
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) := by
  intro y hy
  rcases hy with ⟨w, hw, rfl⟩
  exact
    freeProCZCFoxClosedGenTarget_mem_of_freeFoxDerivVec_kernel
      (ProC := ProC) φ hw

omit [TopologicalSpace X] in
/-- The closure of algebraic kernel-word cycle points is still contained in the closed generated
Fox graph target. -/
theorem closure_freeProCZCFoxSemiKernelCycleSet_subset_closedGenTarget
    (φ : X → H) :
    closure (freeProCZCCompletedFoxSemidirectKernelCycleSet (ProC := ProC) φ) ⊆
      ((freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) : Set
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) := by
  exact
    closure_minimal
      (freeProCZCCompletedFoxSemidirectKernelCycleSet_subset_closedGeneratedTarget
        (ProC := ProC) φ)
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget (ProC := ProC) φ).isClosed'

omit [TopologicalSpace X] in
/-- If the boundary-cycle set is dense in the algebraic kernel-word closure, then every completed
Fox boundary cycle belongs to the closed subgroup generated by the Fox graph. -/
theorem freeProCZCFoxBoundaryCycles_subset_closedGenTarget_of_density
    [Fintype X] (φ : X → H)
    (hdensity :
      freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ ⊆
        closure (freeProCZCCompletedFoxSemidirectKernelCycleSet (ProC := ProC) φ)) :
    freeProCZCCompletedFoxSemidirectBoundaryCycleSet (ProC := ProC) φ ⊆
      ((freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) : Set
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) := by
  intro y hy
  exact
    closure_freeProCZCFoxSemiKernelCycleSet_subset_closedGenTarget
      (ProC := ProC) φ (hdensity hy)

omit [TopologicalSpace X] in
/-- Pointwise form of the closure step for algebraic kernel-word cycle points. -/
theorem freeProCZCFoxClosedGenTarget_mem_of_mem_closure_kernelCycleSet
    (φ : X → H)
    {y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H}
    (hy :
      y ∈ closure
        (freeProCZCCompletedFoxSemidirectKernelCycleSet (ProC := ProC) φ)) :
    y ∈
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) :=
  closure_freeProCZCFoxSemiKernelCycleSet_subset_closedGenTarget
    (ProC := ProC) φ hy

omit [TopologicalSpace X] in
/-- The restricted Fox graph generators topologically generate their closed generated target. -/
theorem freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator_topologicallyGenerates
    (φ : X → H) :
    ProCGroups.Generation.TopologicallyGenerates
      (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
      (Set.range
        (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ)) :=
  ProCGroups.Generation.closedSubgroupGeneratedMap_topologicallyGenerates
    (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
    (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)

omit [TopologicalSpace X] in
/-- For a finite generator set, the restricted Fox graph generators converge to `1`. -/
theorem freeProCZCFoxSemiClosedGenGenerator_convergesToOne_of_finite
    [Finite X] (φ : X → H) :
    FamilyConvergesToOne
      (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
      (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ) := by
  exact FamilyConvergesToOne.of_finite_domain
    (G :=
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
    (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ)

omit [TopologicalSpace X] in
/-- The completed Fox semidirect lift into the closed target generated by the graph generators.

This is the converging-set version needed when the graph generators do not generate the whole
semidirect product. -/
def freeProCZCCompletedFoxSemidirectLiftToClosedGenerated
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (φ : X → H)
    (htarget :
      ProC (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))))
    (hφconv :
      FamilyConvergesToOne
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC) φ : Subgroup
              (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
        (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ)) :
    F →*
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) :=
  hι.lift htarget
    (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ)
    hφconv
    (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator_topologicallyGenerates
      (ProC := ProC) φ)

omit [TopologicalSpace X] in
/-- Continuous homomorphism form of the closed-generated semidirect lift. -/
def freeProCZCCompletedFoxSemidirectLiftHomToClosedGenerated
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (φ : X → H)
    (htarget :
      ProC (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))))
    (hφconv :
      FamilyConvergesToOne
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC) φ : Subgroup
              (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
        (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ)) :
    F →ₜ*
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) :=
  hι.liftHom htarget
    (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ)
    hφconv
    (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator_topologicallyGenerates
      (ProC := ProC) φ)

omit [TopologicalSpace X] in
@[simp]
theorem freeProCZCCompletedFoxSemidirectLiftHomToClosedGenerated_toMonoidHom
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (φ : X → H)
    (htarget :
      ProC (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))))
    (hφconv :
      FamilyConvergesToOne
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC) φ : Subgroup
              (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
        (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ)) :
    (freeProCZCCompletedFoxSemidirectLiftHomToClosedGenerated
        (ProC := ProC) hι φ htarget hφconv).toMonoidHom =
      freeProCZCCompletedFoxSemidirectLiftToClosedGenerated
        (ProC := ProC) hι φ htarget hφconv :=
  rfl

omit [TopologicalSpace X] in
@[simp 900]
theorem freeProCZCCompletedFoxSemidirectLiftToClosedGenerated_generator
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (φ : X → H)
    (htarget :
      ProC (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))))
    (hφconv :
      FamilyConvergesToOne
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC) φ : Subgroup
              (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
        (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ))
    (x : X) :
    freeProCZCCompletedFoxSemidirectLiftToClosedGenerated
        (ProC := ProC) hι φ htarget hφconv (ι x) =
      freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ x :=
  (hι.lift_spec htarget
    (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ)
    hφconv
    (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator_topologicallyGenerates
      (ProC := ProC) φ)).2 x

omit [TopologicalSpace X] in
/-- The closed-generated semidirect lift is surjective onto the closed target generated by the
Fox graph generators.

This is the honest replacement for the generally false assertion that the Fox graph generators
fill the whole completed semidirect product: the universal map from the free pro-`C` group is
onto exactly the closed subgroup generated by those graph generators. -/
theorem freeProCZCCompletedFoxSemidirectLiftHomToClosedGenerated_surjective
    [CompactSpace F]
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (φ : X → H)
    [T2Space
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))]
    (htarget :
      ProC (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))))
    (hφconv :
      FamilyConvergesToOne
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC) φ : Subgroup
              (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
        (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ)) :
    Function.Surjective
      (freeProCZCCompletedFoxSemidirectLiftHomToClosedGenerated
        (ProC := ProC) hι φ htarget hφconv) := by
  refine
    ProCGroups.Generation.continuousMonoidHom_surjective_of_topologicallyGenerates_subset_range
      (f := freeProCZCCompletedFoxSemidirectLiftHomToClosedGenerated
        (ProC := ProC) hι φ htarget hφconv)
      (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator_topologicallyGenerates
        (ProC := ProC) φ) ?_
  rintro y ⟨x, rfl⟩
  refine ⟨ι x, ?_⟩
  change
    freeProCZCCompletedFoxSemidirectLiftToClosedGenerated
        (ProC := ProC) hι φ htarget hφconv (ι x) =
      freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ x
  exact freeProCZCCompletedFoxSemidirectLiftToClosedGenerated_generator
    (ProC := ProC) hι φ htarget hφconv x

omit [TopologicalSpace X] in
/-- The closed-generated lift, viewed in the full completed Fox semidirect product. -/
def freeProCZCCompletedFoxSemidirectLiftViaClosedGenerated
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (φ : X → H)
    (htarget :
      ProC (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))))
    (hφconv :
      FamilyConvergesToOne
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC) φ : Subgroup
              (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
        (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ)) :
    F →* ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H :=
  (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
      (ProC := ProC) φ : Subgroup
        (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)).subtype.comp
    (freeProCZCCompletedFoxSemidirectLiftToClosedGenerated
      (ProC := ProC) hι φ htarget hφconv)

omit [TopologicalSpace X] in
/-- Elementwise form of the semidirect lift theorem, stated in the ambient completed Fox semidirect
product.  Every element of the closed Fox graph target has a preimage under the free pro-`C`
semidirect lift. -/
theorem freeProCZCFoxSemiLiftViaClosedGen_exists_preimage_of_mem_closedGenTarget
    [CompactSpace F]
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (φ : X → H)
    [T2Space
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))]
    (htarget :
      ProC (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))))
    (hφconv :
      FamilyConvergesToOne
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC) φ : Subgroup
              (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
        (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ))
    {y : ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H}
    (hy : y ∈
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))) :
    ∃ g : F,
      freeProCZCCompletedFoxSemidirectLiftViaClosedGenerated
        (ProC := ProC) hι φ htarget hφconv g = y := by
  let yclosed :
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)) :=
    ⟨y, hy⟩
  rcases
    freeProCZCCompletedFoxSemidirectLiftHomToClosedGenerated_surjective
      (ProC := ProC) hι φ htarget hφconv yclosed with
    ⟨g, hg⟩
  refine ⟨g, ?_⟩
  simpa [freeProCZCCompletedFoxSemidirectLiftViaClosedGenerated, yclosed] using
    congrArg Subtype.val hg

omit [TopologicalSpace X] in
@[simp]
theorem freeProCZCCompletedFoxSemidirectLiftViaClosedGenerated_generator
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (φ : X → H)
    (htarget :
      ProC (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))))
    (hφconv :
      FamilyConvergesToOne
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC) φ : Subgroup
              (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
        (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ))
    (x : X) :
    freeProCZCCompletedFoxSemidirectLiftViaClosedGenerated
        (ProC := ProC) hι φ htarget hφconv (ι x) =
      freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ x := by
  simp only [freeProCZCCompletedFoxSemidirectLiftViaClosedGenerated, MonoidHom.coe_comp, Subgroup.coe_subtype,
  Function.comp_apply, freeProCZCCompletedFoxSemidirectLiftToClosedGenerated_generator,
  freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator_val]

omit [TopologicalSpace X] in
/-- The right component of the closed-generated semidirect lift. -/
def freeProCZCCompletedFoxRightHomViaClosedGenerated
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (φ : X → H)
    (htarget :
      ProC (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))))
    (hφconv :
      FamilyConvergesToOne
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC) φ : Subgroup
              (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
        (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ)) :
    F →* H :=
  (ZCCompletedFoxSemidirect.rightMonoidHom ProC.finiteQuotientClass X H).comp
    (freeProCZCCompletedFoxSemidirectLiftViaClosedGenerated
      (ProC := ProC) hι φ htarget hφconv)

omit [TopologicalSpace X] in
@[simp]
theorem freeProCZCCompletedFoxRightHomViaClosedGenerated_generator
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (φ : X → H)
    (htarget :
      ProC (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))))
    (hφconv :
      FamilyConvergesToOne
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC) φ : Subgroup
              (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
        (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ))
    (x : X) :
    freeProCZCCompletedFoxRightHomViaClosedGenerated
        (ProC := ProC) hι φ htarget hφconv (ι x) = φ x := by
  simp only [freeProCZCCompletedFoxRightHomViaClosedGenerated, MonoidHom.coe_comp, Function.comp_apply,
  freeProCZCCompletedFoxSemidirectLiftViaClosedGenerated_generator, ZCCompletedFoxSemidirect.rightMonoidHom_apply,
  freeProCZCCompletedFoxSemidirectGenerator_right]

omit [TopologicalSpace X] in
/-- The derivative-vector component of the closed-generated semidirect lift. -/
def freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (φ : X → H)
    (htarget :
      ProC (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))))
    (hφconv :
      FamilyConvergesToOne
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC) φ : Subgroup
              (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
        (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ))
    (g : F) :
    ZCFreeFoxCoordinates ProC.finiteQuotientClass (X := X) (H := H) :=
  (freeProCZCCompletedFoxSemidirectLiftViaClosedGenerated
      (ProC := ProC) hι φ htarget hφconv g).left

omit [TopologicalSpace X] in
@[simp]
theorem freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated_generator
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (φ : X → H)
    (htarget :
      ProC (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))))
    (hφconv :
      FamilyConvergesToOne
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC) φ : Subgroup
              (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
        (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ))
    (x : X) :
    freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
        (ProC := ProC) hι φ htarget hφconv (ι x) =
      Pi.single x (1 : ZCCompletedGroupAlgebra ProC.finiteQuotientClass H) := by
  simp only [freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated,
  freeProCZCCompletedFoxSemidirectLiftViaClosedGenerated_generator, freeProCZCCompletedFoxSemidirectGenerator_left]

omit [TopologicalSpace X] in
/-- The closed-generated derivative vector is crossed with respect to its right component. -/
theorem freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated_isCrossedDifferential
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (φ : X → H)
    (htarget :
      ProC (G :=
        (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
          (ProC := ProC) φ : Subgroup
            (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))))
    (hφconv :
      FamilyConvergesToOne
        (G :=
          (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
            (ProC := ProC) φ : Subgroup
              (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
        (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ)) :
    IsCrossedDifferential
      (zcCompletedGroupAlgebraScalar ProC.finiteQuotientClass
        (freeProCZCCompletedFoxRightHomViaClosedGenerated
          (ProC := ProC) hι φ htarget hφconv))
      (freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
        (ProC := ProC) hι φ htarget hφconv) := by
  intro g h
  have hmul := congrArg ZCCompletedFoxSemidirect.left
    (map_mul
      (freeProCZCCompletedFoxSemidirectLiftViaClosedGenerated
        (ProC := ProC) hι φ htarget hφconv) g h)
  change
    (freeProCZCCompletedFoxSemidirectLiftViaClosedGenerated
      (ProC := ProC) hι φ htarget hφconv (g * h)).left =
      (freeProCZCCompletedFoxSemidirectLiftViaClosedGenerated
        (ProC := ProC) hι φ htarget hφconv g).left +
        zcCompletedGroupAlgebraScalar ProC.finiteQuotientClass
          (freeProCZCCompletedFoxRightHomViaClosedGenerated
            (ProC := ProC) hι φ htarget hφconv) g •
          (freeProCZCCompletedFoxSemidirectLiftViaClosedGenerated
            (ProC := ProC) hι φ htarget hφconv h).left
  rw [hmul]
  simp only [ZCCompletedFoxSemidirect.mul_left, freeProCZCCompletedFoxRightHomViaClosedGenerated,
  zcCompletedGroupAlgebraScalar_apply, MonoidHom.coe_comp, Function.comp_apply,
  ZCCompletedFoxSemidirect.rightMonoidHom_apply]

/-- The continuous completed Fox semidirect lift from a free pro-`C` source. -/
def freeProCZCCompletedFoxSemidirectLift
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)) :
    F →* ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H :=
  hι.lift htarget (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ) hφ

/-- The continuous homomorphism form of the completed Fox semidirect lift from a free pro-`C`
source. -/
def freeProCZCCompletedFoxSemidirectLiftHom
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)) :
    F →ₜ* ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H :=
  hι.liftHom htarget (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ) hφ

/-- Forgetting continuity from the continuous semidirect lift gives the underlying semidirect
lift. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectLiftHom_toMonoidHom
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)) :
    (freeProCZCCompletedFoxSemidirectLiftHom
        (ProC := ProC) hι htarget φ hφ).toMonoidHom =
      freeProCZCCompletedFoxSemidirectLift
        (ProC := ProC) hι htarget φ hφ :=
  rfl

/-- The free pro-`C` semidirect lift is continuous. -/
theorem continuous_freeProCZCCompletedFoxSemidirectLift
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)) :
    Continuous (freeProCZCCompletedFoxSemidirectLift
        (ProC := ProC) hι htarget φ hφ) :=
  (freeProCZCCompletedFoxSemidirectLiftHom
        (ProC := ProC) hι htarget φ hφ).continuous_toFun

/-- The free pro-`C` semidirect lift has the prescribed completed Fox generator values. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectLift_generator
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (x : X) :
    freeProCZCCompletedFoxSemidirectLift
        (ProC := ProC) hι htarget φ hφ (ι x) =
      freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ x :=
  (hι.lift_spec htarget (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ) hφ).2 x

/-- The continuous semidirect lift has the prescribed completed Fox generator values. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectLiftHom_generator
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (x : X) :
    freeProCZCCompletedFoxSemidirectLiftHom
        (ProC := ProC) hι htarget φ hφ (ι x) =
      freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ x :=
  hι.liftHom_apply htarget (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ) hφ x

omit [TopologicalSpace X] in
/-- The completed Fox semidirect lift from a converging-set free pro-`C` source.  The generator
map into the semidirect target is required to converge to `1` and topologically generate the
target, matching the `IsFreeProCGroupOnConvergingSet` universal property. -/
def freeProCZCCompletedFoxSemidirectLiftOfConvergingSet
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφconv :
      FamilyConvergesToOne
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (hφgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (Set.range (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))) :
    F →* ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H :=
  hι.lift htarget (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)
    hφconv hφgen

omit [TopologicalSpace X] in
/-- Continuous homomorphism form of the converging-set completed Fox semidirect lift. -/
def freeProCZCCompletedFoxSemidirectLiftHomOfConvergingSet
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφconv :
      FamilyConvergesToOne
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (hφgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (Set.range (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))) :
    F →ₜ* ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H :=
  hι.liftHom htarget (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)
    hφconv hφgen

omit [TopologicalSpace X] in
/-- Forgetting continuity from the converging-set semidirect lift homomorphism gives the
unbundled lift. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectLiftHomOfConvergingSet_toMonoidHom
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφconv :
      FamilyConvergesToOne
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (hφgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (Set.range (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))) :
    (freeProCZCCompletedFoxSemidirectLiftHomOfConvergingSet
        (ProC := ProC) hι htarget φ hφconv hφgen).toMonoidHom =
      freeProCZCCompletedFoxSemidirectLiftOfConvergingSet
        (ProC := ProC) hι htarget φ hφconv hφgen :=
  rfl

omit [TopologicalSpace X] in
/-- The converging-set semidirect lift is continuous. -/
theorem continuous_freeProCZCCompletedFoxSemidirectLiftOfConvergingSet
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφconv :
      FamilyConvergesToOne
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (hφgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (Set.range (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))) :
    Continuous (freeProCZCCompletedFoxSemidirectLiftOfConvergingSet
        (ProC := ProC) hι htarget φ hφconv hφgen) :=
  (freeProCZCCompletedFoxSemidirectLiftHomOfConvergingSet
        (ProC := ProC) hι htarget φ hφconv hφgen).continuous_toFun

omit [TopologicalSpace X] in
/-- The converging-set semidirect lift has the prescribed generator values. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectLiftOfConvergingSet_generator
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφconv :
      FamilyConvergesToOne
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (hφgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (Set.range (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)))
    (x : X) :
    freeProCZCCompletedFoxSemidirectLiftOfConvergingSet
        (ProC := ProC) hι htarget φ hφconv hφgen (ι x) =
      freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ x :=
  (hι.lift_spec htarget (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)
    hφconv hφgen).2 x

omit [TopologicalSpace X] in
/-- The converging-set semidirect lift is surjective once its prescribed generator values
topologically generate the semidirect target. -/
theorem freeProCZCCompletedFoxSemidirectLiftHomOfConvergingSet_surjective
    [CompactSpace F]
    [T2Space (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφconv :
      FamilyConvergesToOne
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (hφgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (Set.range (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))) :
    Function.Surjective
      (freeProCZCCompletedFoxSemidirectLiftHomOfConvergingSet
        (ProC := ProC) hι htarget φ hφconv hφgen) := by
  refine
    ProCGroups.Generation.continuousMonoidHom_surjective_of_topologicallyGenerates_subset_range
      (f := freeProCZCCompletedFoxSemidirectLiftHomOfConvergingSet
        (ProC := ProC) hι htarget φ hφconv hφgen)
      hφgen ?_
  rintro y ⟨x, rfl⟩
  refine ⟨ι x, ?_⟩
  change
    freeProCZCCompletedFoxSemidirectLiftOfConvergingSet
        (ProC := ProC) hι htarget φ hφconv hφgen (ι x) =
      freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ x
  exact freeProCZCCompletedFoxSemidirectLiftOfConvergingSet_generator
    (ProC := ProC) hι htarget φ hφconv hφgen x

omit [TopologicalSpace X] in
/-- The right component of the converging-set semidirect lift. -/
def freeProCZCCompletedFoxRightHomOfConvergingSet
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφconv :
      FamilyConvergesToOne
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (hφgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (Set.range (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))) :
    F →* H :=
  (ZCCompletedFoxSemidirect.rightMonoidHom ProC.finiteQuotientClass X H).comp
    (freeProCZCCompletedFoxSemidirectLiftOfConvergingSet
      (ProC := ProC) hι htarget φ hφconv hφgen)

omit [TopologicalSpace X] in
/-- The derivative-vector component of the converging-set semidirect lift. -/
def freeProCZCCompletedFoxDerivativeVectorOfConvergingSet
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφconv :
      FamilyConvergesToOne
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (hφgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (Set.range (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)))
    (g : F) :
    ZCFreeFoxCoordinates ProC.finiteQuotientClass (X := X) (H := H) :=
  (freeProCZCCompletedFoxSemidirectLiftOfConvergingSet
    (ProC := ProC) hι htarget φ hφconv hφgen g).left

omit [TopologicalSpace X] in
@[simp]
theorem freeProCZCCompletedFoxRightHomOfConvergingSet_generator
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφconv :
      FamilyConvergesToOne
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (hφgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (Set.range (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)))
    (x : X) :
    freeProCZCCompletedFoxRightHomOfConvergingSet
        (ProC := ProC) hι htarget φ hφconv hφgen (ι x) = φ x := by
  simp only [freeProCZCCompletedFoxRightHomOfConvergingSet, MonoidHom.coe_comp, Function.comp_apply,
  freeProCZCCompletedFoxSemidirectLiftOfConvergingSet_generator, ZCCompletedFoxSemidirect.rightMonoidHom_apply,
  freeProCZCCompletedFoxSemidirectGenerator_right]

omit [TopologicalSpace X] in
@[simp]
theorem freeProCZCCompletedFoxDerivativeVectorOfConvergingSet_generator
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφconv :
      FamilyConvergesToOne
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (hφgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (Set.range (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)))
    (x : X) :
    freeProCZCCompletedFoxDerivativeVectorOfConvergingSet
        (ProC := ProC) hι htarget φ hφconv hφgen (ι x) =
      Pi.single x (1 : ZCCompletedGroupAlgebra ProC.finiteQuotientClass H) := by
  simp only [freeProCZCCompletedFoxDerivativeVectorOfConvergingSet,
  freeProCZCCompletedFoxSemidirectLiftOfConvergingSet_generator, freeProCZCCompletedFoxSemidirectGenerator_left]

omit [TopologicalSpace X] in
/-- The converging-set derivative vector is a crossed differential with respect to its right
component. -/
theorem freeProCZCCompletedFoxDerivativeVectorOfConvergingSet_isCrossedDifferential
    {ι : X → F} (hι : IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφconv :
      FamilyConvergesToOne
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (hφgen :
      ProCGroups.Generation.TopologicallyGenerates
        (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
        (Set.range (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))) :
    IsCrossedDifferential
      (zcCompletedGroupAlgebraScalar ProC.finiteQuotientClass
        (freeProCZCCompletedFoxRightHomOfConvergingSet
          (ProC := ProC) hι htarget φ hφconv hφgen))
      (freeProCZCCompletedFoxDerivativeVectorOfConvergingSet
        (ProC := ProC) hι htarget φ hφconv hφgen) := by
  intro g h
  change
    (freeProCZCCompletedFoxSemidirectLiftOfConvergingSet
      (ProC := ProC) hι htarget φ hφconv hφgen (g * h)).left =
      (freeProCZCCompletedFoxSemidirectLiftOfConvergingSet
        (ProC := ProC) hι htarget φ hφconv hφgen g).left +
        zcCompletedGroupAlgebraScalar ProC.finiteQuotientClass
          (freeProCZCCompletedFoxRightHomOfConvergingSet
            (ProC := ProC) hι htarget φ hφconv hφgen) g •
          (freeProCZCCompletedFoxSemidirectLiftOfConvergingSet
            (ProC := ProC) hι htarget φ hφconv hφgen h).left
  simp only [map_mul, ZCCompletedFoxSemidirect.mul_left, freeProCZCCompletedFoxRightHomOfConvergingSet,
  ZCCompletedFoxSemidirect.rightMonoidHom, zcCompletedGroupAlgebraScalar_apply, MonoidHom.coe_comp, MonoidHom.coe_mk,
  OneHom.coe_mk, Function.comp_apply]

/-- The categorical completed Fox semidirect lift from a free pro-`C` source, bundled as a
morphism in `ProCGrp`. -/
def freeProCZCCompletedFoxSemidirectLiftMorphism
    [ProCGroups.ProC.ProCGroup ProC F]
    [ProCGroups.ProC.ProCGroup ProC (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)) :
    ProCGrp.of ProC F ⟶
      ProCGrp.of ProC (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H) :=
  hι.liftMorphism
    (ProCGrp.of ProC (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ) hφ

/-- The underlying continuous homomorphism of the categorical completed Fox semidirect lift is
the free pro-`C` continuous homomorphism supplied by `liftHom`. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectLiftMorphism_hom
    [ProCGroups.ProC.ProCGroup ProC F]
    [ProCGroups.ProC.ProCGroup ProC (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)) :
    (freeProCZCCompletedFoxSemidirectLiftMorphism
      (ProC := ProC) hι φ hφ).hom =
      freeProCZCCompletedFoxSemidirectLiftHom
        (ProC := ProC) hι
        (inferInstanceAs
          (ProCGroups.ProC.ProCGroup ProC (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))).isProC
        φ hφ :=
  rfl

/-- The underlying homomorphism of the categorical completed Fox semidirect lift is the
unbundled completed Fox semidirect lift. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectLiftMorphism_hom_toMonoidHom
    [ProCGroups.ProC.ProCGroup ProC F]
    [ProCGroups.ProC.ProCGroup ProC (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)) :
    (freeProCZCCompletedFoxSemidirectLiftMorphism
      (ProC := ProC) hι φ hφ).hom.toMonoidHom =
      freeProCZCCompletedFoxSemidirectLift
        (ProC := ProC) hι
        (inferInstanceAs
          (ProCGroups.ProC.ProCGroup ProC (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))).isProC
        φ hφ :=
  rfl

/-- The categorical completed Fox semidirect lift has the prescribed generator values. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectLiftMorphism_generator
    [ProCGroups.ProC.ProCGroup ProC F]
    [ProCGroups.ProC.ProCGroup ProC (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (x : X) :
    freeProCZCCompletedFoxSemidirectLiftMorphism
      (ProC := ProC) hι φ hφ (ι x) =
      freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ x :=
  hι.liftMorphism_apply
    (ProCGrp.of ProC (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ) hφ x

/-- The left component of the categorical completed Fox semidirect lift has the standard Fox
coordinate on each generator. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectLiftMorphism_left_generator
    [ProCGroups.ProC.ProCGroup ProC F]
    [ProCGroups.ProC.ProCGroup ProC (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (x : X) :
    (freeProCZCCompletedFoxSemidirectLiftMorphism
      (ProC := ProC) hι φ hφ (ι x)).left =
      Pi.single x (1 : ZCCompletedGroupAlgebra ProC.finiteQuotientClass H) := by
  rw [freeProCZCCompletedFoxSemidirectLiftMorphism_generator]
  rfl

/-- The right component of the categorical completed Fox semidirect lift has the prescribed
generator value. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectLiftMorphism_right_generator
    [ProCGroups.ProC.ProCGroup ProC F]
    [ProCGroups.ProC.ProCGroup ProC (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)]
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (x : X) :
    (freeProCZCCompletedFoxSemidirectLiftMorphism
      (ProC := ProC) hι φ hφ (ι x)).right = φ x := by
  rw [freeProCZCCompletedFoxSemidirectLiftMorphism_generator]
  rfl

/-- The left component of the free pro-`C` semidirect lift has the standard Fox coordinate on
each generator. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectLift_left_generator
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (x : X) :
    (freeProCZCCompletedFoxSemidirectLift
        (ProC := ProC) hι htarget φ hφ (ι x)).left =
      Pi.single x (1 : ZCCompletedGroupAlgebra ProC.finiteQuotientClass H) := by
  rw [freeProCZCCompletedFoxSemidirectLift_generator]
  rfl

/-- The left component of the continuous free pro-`C` semidirect lift has the standard Fox
coordinate on each generator. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectLiftHom_left_generator
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (x : X) :
    (freeProCZCCompletedFoxSemidirectLiftHom
        (ProC := ProC) hι htarget φ hφ (ι x)).left =
      Pi.single x (1 : ZCCompletedGroupAlgebra ProC.finiteQuotientClass H) := by
  rw [freeProCZCCompletedFoxSemidirectLiftHom_generator]
  rfl

/-- The right component of the free pro-`C` semidirect lift has the prescribed generator value. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectLift_right_generator
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (x : X) :
    (freeProCZCCompletedFoxSemidirectLift
        (ProC := ProC) hι htarget φ hφ (ι x)).right = φ x := by
  rw [freeProCZCCompletedFoxSemidirectLift_generator]
  rfl

/-- The right component of the continuous free pro-`C` semidirect lift has the prescribed
generator value. -/
@[simp]
theorem freeProCZCCompletedFoxSemidirectLiftHom_right_generator
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (x : X) :
    (freeProCZCCompletedFoxSemidirectLiftHom
        (ProC := ProC) hι htarget φ hφ (ι x)).right = φ x := by
  rw [freeProCZCCompletedFoxSemidirectLiftHom_generator]
  rfl

/-- The target-group component of the continuous completed Fox semidirect lift. -/
def freeProCZCCompletedFoxRightHom
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)) :
    F →* H where
  toFun g := (freeProCZCCompletedFoxSemidirectLift
        (ProC := ProC) hι htarget φ hφ g).right
  map_one' := by
    simp only [map_one, ZCCompletedFoxSemidirect.one_right]
  map_mul' g h := by
    simp only [map_mul, ZCCompletedFoxSemidirect.mul_right]

/-- The right component of the continuous completed Fox semidirect lift is the associated
homomorphism. -/
@[simp]
theorem freeProCZCCompletedFoxRightHom_apply
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (g : F) :
    freeProCZCCompletedFoxRightHom (ProC := ProC) hι htarget φ hφ g =
      (freeProCZCCompletedFoxSemidirectLift
        (ProC := ProC) hι htarget φ hφ g).right :=
  rfl

/-- The target-group component has the prescribed generator values. -/
@[simp]
theorem freeProCZCCompletedFoxRightHom_generator
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (x : X) :
    freeProCZCCompletedFoxRightHom (ProC := ProC) hι htarget φ hφ (ι x) = φ x := by
  rw [freeProCZCCompletedFoxRightHom_apply,
    freeProCZCCompletedFoxSemidirectLift_right_generator]

/-- The completed Fox derivative vector obtained as the left component of the continuous
free pro-`C` semidirect lift. -/
def freeProCZCCompletedFoxDerivativeVector
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (g : F) :
    ZCFreeFoxCoordinates ProC.finiteQuotientClass (X := X) (H := H) :=
  (freeProCZCCompletedFoxSemidirectLift
        (ProC := ProC) hι htarget φ hφ g).left

/-- The free pro-`C` completed Fox derivative vector has the standard coordinate value on
generators. -/
@[simp]
theorem freeProCZCCompletedFoxDerivativeVector_generator
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
    (x : X) :
    freeProCZCCompletedFoxDerivativeVector
        (ProC := ProC) hι htarget φ hφ (ι x) =
      Pi.single x (1 : ZCCompletedGroupAlgebra ProC.finiteQuotientClass H) := by
  rw [freeProCZCCompletedFoxDerivativeVector,
    freeProCZCCompletedFoxSemidirectLift_left_generator]

/-- The free pro-`C` completed Fox derivative vector is crossed with respect to the target-group
component of the continuous semidirect lift. -/
theorem freeProCZCCompletedFoxDerivativeVector_isCrossedDifferential
    {ι : X → F} (hι : IsFreeProCGroup (ProC := ProC) ι)
    (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
    (φ : X → H)
    (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)) :
    IsCrossedDifferential
      (zcCompletedGroupAlgebraScalar ProC.finiteQuotientClass
        (freeProCZCCompletedFoxRightHom (ProC := ProC) hι htarget φ hφ))
      (freeProCZCCompletedFoxDerivativeVector
        (ProC := ProC) hι htarget φ hφ) := by
  intro g h
  have hmul := congrArg ZCCompletedFoxSemidirect.left
    (map_mul (freeProCZCCompletedFoxSemidirectLift
        (ProC := ProC) hι htarget φ hφ) g h)
  change (freeProCZCCompletedFoxSemidirectLift
        (ProC := ProC) hι htarget φ hφ (g * h)).left =
    (freeProCZCCompletedFoxSemidirectLift
        (ProC := ProC) hι htarget φ hφ g).left +
      zcCompletedGroupAlgebraScalar ProC.finiteQuotientClass
        (freeProCZCCompletedFoxRightHom (ProC := ProC) hι htarget φ hφ) g •
        (freeProCZCCompletedFoxSemidirectLift
        (ProC := ProC) hι htarget φ hφ h).left
  rw [hmul]
  simp only [ZCCompletedFoxSemidirect.mul_left, freeProCZCCompletedFoxRightHom,
  zcCompletedGroupAlgebraScalar_apply, MonoidHom.coe_mk, OneHom.coe_mk]


end

end FoxDifferential
