import CompletedGroupAlgebra.OpenFiniteQuotientTopology.CanonicalMaps
import CompletedGroupAlgebra.OpenFiniteQuotientTopology.FiniteQuotients
import CompletedGroupAlgebra.OpenFiniteQuotientTopology.OpenFiniteQuotients
import CompletedGroupAlgebra.OpenFiniteQuotientTopology.OpenFiniteLimit.CanonicalMap
import CompletedGroupAlgebra.OpenFiniteQuotientTopology.OpenFiniteComparison

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/CompletedGroupAlgebra/OpenFiniteQuotientTopology.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Kernel-neighborhood topology on completed group algebras

This namespace collects the kernel-neighborhood topology generated by open coefficient ideals and
open finite group quotients, together with the corresponding inverse-limit model and comparison
maps for RZ Lemma 5.3.5(a).
-/
