import FoxDifferential.Common.CrossedDifferentialModule
import Mathlib.Algebra.MonoidAlgebra.MapDomain

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/FoxDifferential/Discrete/DifferentialModule/Basic.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Discrete group-ring Fox calculus

The completed differential module is organized separately from coefficient algebras; its universal and quotient maps are used by completed crossed differentials.
-/
namespace FoxDifferential

noncomputable section

/-- The integral group ring `ℤ[H]`, realized as a monoid algebra. -/
abbrev GroupRing (H : Type*) : Type _ := MonoidAlgebra ℤ H

/-- The group-ring map induced by a group homomorphism. -/
def groupRingMap {H K : Type*} [Group H] [Group K] (φ : H →* K) :
    GroupRing H →+* GroupRing K :=
  MonoidAlgebra.mapDomainRingHom ℤ φ

/-- The induced group-ring map sends monomials to monomials. -/
@[simp]
theorem groupRingMap_of {H K : Type*} [Group H] [Group K]
    (φ : H →* K) (h : H) :
    groupRingMap φ (MonoidAlgebra.of ℤ H h) =
      MonoidAlgebra.of ℤ K (φ h) := by
  simp only [groupRingMap, MonoidAlgebra.of, MonoidHom.coe_mk, OneHom.coe_mk,
  MonoidAlgebra.mapDomainRingHom_apply, Finsupp.mapDomain_single]

/-- The induced group-ring map sends `Finsupp.single` basis terms along the group map. -/
@[simp]
theorem groupRingMap_single {H K : Type*} [Group H] [Group K]
    (φ : H →* K) (h : H) (z : ℤ) :
    groupRingMap φ (MonoidAlgebra.single h z : GroupRing H) =
      (MonoidAlgebra.single (φ h) z : GroupRing K) := by
  simp only [groupRingMap, MonoidAlgebra.mapDomainRingHom_apply, Finsupp.mapDomain_single]

/-- The free `ℤ[H]`-module on the underlying set of `G`. -/
abbrev DifferentialPreModule (H : Type*) (G : Type*) : Type _ :=
  G →₀ GroupRing H


variable {H G : Type*} [Group H] [Group G]

/-- The group-ring monomial attached to the group identity is the ring identity. -/
@[simp]
theorem groupRing_of_one : (MonoidAlgebra.of ℤ H (1 : H) : GroupRing H) = 1 := by
  classical
  ext a
  by_cases ha : a = 1
  · subst ha
    simp only [MonoidAlgebra.of_apply, Finsupp.single_eq_same, MonoidAlgebra.one_def]
  · simp only [MonoidAlgebra.of_apply, ne_eq, ha, not_false_eq_true, Finsupp.single_eq_of_ne,
  MonoidAlgebra.one_def]

/-- The basic Fox differential relation
`universalDifferential(g₁ g₂) =
  universalDifferential(g₁) + ψ(g₁) • universalDifferential(g₂)`. -/
def relationElement (ψ : G →* H) (g₁ g₂ : G) : DifferentialPreModule H G :=
  Finsupp.single (g₁ * g₂) 1 -
    (Finsupp.single g₁ 1 + (MonoidAlgebra.of ℤ H (ψ g₁)) • Finsupp.single g₂ 1)

/-- The submodule generated by the Fox differential relations. -/
def relationSubmodule (ψ : G →* H) : Submodule (GroupRing H) (DifferentialPreModule H G) :=
  Submodule.span (GroupRing H) (Set.range fun p : G × G => relationElement ψ p.1 p.2)

/-- The `ψ`-differential module. -/
abbrev DifferentialModule (ψ : G →* H) : Type _ := DifferentialPreModule H G ⧸ relationSubmodule ψ

/-- The universal differential `universalDifferential : G → A_ψ`. -/
def universalDifferential (ψ : G →* H) (g : G) : DifferentialModule ψ :=
  (relationSubmodule ψ).mkQ (Finsupp.single g 1)

/-- Every defining Fox relation belongs to the relation submodule. -/
theorem relationElement_mem (ψ : G →* H) (g₁ g₂ : G) :
    relationElement ψ g₁ g₂ ∈ relationSubmodule ψ := by
  exact Submodule.subset_span ⟨(g₁, g₂), rfl⟩

/-- The universal differential satisfies the Fox product rule. -/
theorem universalDifferential_mul (ψ : G →* H) (g₁ g₂ : G) :
    universalDifferential ψ (g₁ * g₂) =
      universalDifferential ψ g₁ +
        (MonoidAlgebra.of ℤ H (ψ g₁)) • universalDifferential ψ g₂ := by
  have hzero : (relationSubmodule ψ).mkQ (relationElement ψ g₁ g₂) = 0 := by
    exact
      (Submodule.Quotient.mk_eq_zero (p := relationSubmodule ψ) (x := relationElement ψ g₁ g₂)).2
        (relationElement_mem ψ g₁ g₂)
  have hzero' :
      universalDifferential ψ (g₁ * g₂) -
          (universalDifferential ψ g₁ +
            (relationSubmodule ψ).mkQ
              ((MonoidAlgebra.of ℤ H (ψ g₁)) • Finsupp.single g₂ 1)) = 0 := by
    simpa [universalDifferential, relationElement] using hzero
  have hsmul :
      (relationSubmodule ψ).mkQ ((MonoidAlgebra.of ℤ H (ψ g₁)) • Finsupp.single g₂ 1) =
        (MonoidAlgebra.of ℤ H (ψ g₁)) • universalDifferential ψ g₂ := by
    simpa [universalDifferential, Submodule.mkQ_apply] using
      (Submodule.Quotient.mk_smul (p := relationSubmodule ψ)
        (r := MonoidAlgebra.of ℤ H (ψ g₁)) (x := Finsupp.single g₂ 1))
  have hzero'' :
      universalDifferential ψ (g₁ * g₂) -
        (universalDifferential ψ g₁ +
          (MonoidAlgebra.of ℤ H (ψ g₁)) • universalDifferential ψ g₂) = 0 := by
    rw [hsmul] at hzero'
    exact hzero'
  exact sub_eq_zero.mp hzero''

/-- The universal differential vanishes at the group identity. -/
@[simp]
theorem universalDifferential_one (ψ : G →* H) : universalDifferential ψ (1 : G) = 0 := by
  have h := universalDifferential_mul ψ (1 : G) (1 : G)
  rw [map_one, groupRing_of_one (H := H), one_smul] at h
  have h' := congrArg (fun z : DifferentialModule ψ => z - universalDifferential ψ (1 : G)) h
  have h'' : 0 = universalDifferential ψ (1 : G) := by
    simpa [sub_eq_add_neg, add_assoc, add_left_comm, add_comm] using h'
  simpa using h''.symm

/-- The universal differential of `g` and `g⁻¹` add to zero with the Fox twist. -/
theorem universalDifferential_mul_inv_right (ψ : G →* H) (g : G) :
    universalDifferential ψ g + (MonoidAlgebra.of ℤ H (ψ g)) • universalDifferential ψ g⁻¹ = 0 := by
  have h : 0 = universalDifferential ψ g + (MonoidAlgebra.of ℤ H (ψ g)) • universalDifferential ψ g⁻¹ := by
    simpa using universalDifferential_mul ψ g g⁻¹
  simpa using h.symm

/-- Conjugation by `g` acts on the differential of a kernel element by the `ψ(g)` scalar. -/
theorem universalDifferential_conj_of_mem_ker (ψ : G →* H) (g n : G) (hn : ψ n = 1) :
    universalDifferential ψ (g * n * g⁻¹) = (MonoidAlgebra.of ℤ H (ψ g)) • universalDifferential ψ n := by
  calc
    universalDifferential ψ (g * n * g⁻¹)
        = universalDifferential ψ g + (MonoidAlgebra.of ℤ H (ψ g)) • universalDifferential ψ (n * g⁻¹) := by
            simpa [mul_assoc] using universalDifferential_mul ψ g (n * g⁻¹)
    _ = universalDifferential ψ g + (MonoidAlgebra.of ℤ H (ψ g)) •
          (universalDifferential ψ n + (MonoidAlgebra.of ℤ H (ψ n)) • universalDifferential ψ g⁻¹) := by
            rw [universalDifferential_mul]
    _ = universalDifferential ψ g +
          (MonoidAlgebra.of ℤ H (ψ g)) •
            (universalDifferential ψ n + universalDifferential ψ g⁻¹) := by
            rw [hn, groupRing_of_one (H := H), one_smul]
    _ = (universalDifferential ψ g + (MonoidAlgebra.of ℤ H (ψ g)) • universalDifferential ψ g⁻¹) +
          (MonoidAlgebra.of ℤ H (ψ g)) • universalDifferential ψ n := by
            simp only [MonoidAlgebra.of_apply, smul_add, add_comm, add_left_comm]
    _ = (0 : DifferentialModule ψ) + (MonoidAlgebra.of ℤ H (ψ g)) • universalDifferential ψ n := by
            rw [universalDifferential_mul_inv_right]
    _ = (MonoidAlgebra.of ℤ H (ψ g)) • universalDifferential ψ n := by
            simp only [MonoidAlgebra.of_apply, zero_add]

/-- The coefficient homomorphism `G -> ℤ[H]` induced by `ψ : G ->* H`. -/
def groupRingScalar (ψ : G →* H) : G →* GroupRing H :=
  (MonoidAlgebra.of ℤ H).comp ψ

/-- The scalar coefficient homomorphism is definitionally `g ↦ [ψ g]`. -/
@[simp]
theorem groupRingScalar_apply (ψ : G →* H) (g : G) :
    groupRingScalar ψ g = (MonoidAlgebra.of ℤ H (ψ g) : GroupRing H) :=
  rfl

/-- The discrete Fox relation is the coefficient-ring-agnostic crossed-differential relation for
the group-ring coefficient homomorphism. -/
@[simp]
theorem relationElement_eq_crossedDifferentialRelationElement
    (ψ : G →* H) (g₁ g₂ : G) :
    relationElement ψ g₁ g₂ =
      crossedDifferentialRelationElement (groupRingScalar ψ) g₁ g₂ :=
  rfl

/-- The discrete Fox relation submodule agrees with the generic crossed-differential relation
submodule for the group-ring coefficient homomorphism. -/
@[simp]
theorem relationSubmodule_eq_crossedDifferentialRelationSubmodule (ψ : G →* H) :
    relationSubmodule ψ =
      crossedDifferentialRelationSubmodule (groupRingScalar ψ) :=
  rfl

/-- The discrete universal differential module is linearly equivalent to the generic universal
crossed-differential module for the group-ring coefficient homomorphism. -/
def differentialModuleEquivCrossedDifferentialModule (ψ : G →* H) :
    DifferentialModule ψ ≃ₗ[GroupRing H]
      CrossedDifferentialModule (groupRingScalar ψ) :=
  LinearEquiv.refl _ _

/-- The generic universal crossed-differential module for `groupRingScalar ψ` is linearly
equivalent to the discrete universal differential module `A_ψ`. -/
def crossedDifferentialModuleEquivDifferentialModule (ψ : G →* H) :
    CrossedDifferentialModule (groupRingScalar ψ) ≃ₗ[GroupRing H]
      DifferentialModule ψ :=
  (differentialModuleEquivCrossedDifferentialModule ψ).symm

/-- The discrete universal differential is the generic universal crossed differential under the
canonical linear equivalence. -/
@[simp]
theorem differentialModuleEquivCrossedDifferentialModule_d
    (ψ : G →* H) (g : G) :
    differentialModuleEquivCrossedDifferentialModule ψ (universalDifferential ψ g) =
      universalCrossedDifferential (groupRingScalar ψ) g :=
  rfl

/-- The generic universal crossed differential maps back to the discrete universal differential
under the canonical linear equivalence. -/
@[simp]
theorem crossedDifferentialModuleEquivDifferentialModule_universal
    (ψ : G →* H) (g : G) :
    crossedDifferentialModuleEquivDifferentialModule ψ
        (universalCrossedDifferential (groupRingScalar ψ) g) =
      universalDifferential ψ g :=
  rfl


end

end FoxDifferential
