import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.AbelianizationKernel.Conditions
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.AbelianizationKernel.Periods
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.FirstReduction.ActualTransport
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.FirstReduction.KernelEquivalence
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.FirstReduction.QuotientAndBasis
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.FirstReduction.RelatorProofs
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.FirstReduction.Signatures
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.FirstReduction.TransportMaps
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.PeriodFamilies
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.PeriodOne.KernelEquivalence
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.PeriodOne.LowCardDihedral
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.PeriodOne.QuotientAndBasis
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.PeriodOne.RelatorProofs
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.PeriodOne.SourceMaps
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.PeriodOne.SourceSubgroup
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.PeriodOne.TargetMaps
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.PeriodOne.TargetSignatures
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.Quotients
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.KernelEquivalence
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.OrderedTargetSignature
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.QuotientAndBasis
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.RelatorProofs
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.Relators.SourceCore
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.Relators.SourceHead
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.Relators.SourceMiddleTail
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.Relators.SourceTotal
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.Relators.Target
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.Signatures
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.TransportMaps
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.ZeroGenus.CleanupData
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.ZeroGenus.FirstReductionData
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.ZeroGenus.Perfectness
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.ZeroGenus.Reductions
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.ZeroGenus.Reindexing
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.ZeroGenus.SecondReductionData
import FenchelNielsenZomorrodian.Discrete.MainTheorem

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/FenchelNielsenZomorrodian/Discrete/CompactFuchsian.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# FenchelNielsenZomorrodian.Discrete.CompactFuchsian

Wrapper for the `FenchelNielsenZomorrodian.Discrete.CompactFuchsian` folder.
-/
