import FoxDifferential.Completed.Continuous.Free.Continuity
import FoxDifferential.Completed.ProCIntegerCoefficients.Naturality

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/FoxDifferential/Completed/Continuous/Free/Rules.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Continuous crossed differentials

Crossed differentials, universal differential modules, Fox boundaries, Euler formulas, and Jacobians are the common algebraic layer used by Crowell and metabelian applications.
-/
namespace FoxDifferential

noncomputable section

open scoped BigOperators

universe u

variable {ProC : ProCGroups.ProC.ProCGroupPredicate.{u}}
variable {X F H : Type u}
variable [TopologicalSpace X] [DecidableEq X]
variable [Group F] [TopologicalSpace F] [IsTopologicalGroup F]
variable [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

section FreeProCCompletedRules

variable {ι : X → F}
variable (hι : ProCGroups.FreeProC.IsFreeProCGroup (ProC := ProC) ι)
variable (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
variable (φ : X → H)
variable (hφ : Continuous (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))

/-- The right component of the completed free pro-`C` Fox lift, bundled as a continuous
homomorphism. -/
def freeProCZCCompletedFoxRightHomContinuousMonoidHom : F →ₜ* H where
  toMonoidHom := freeProCZCCompletedFoxRightHom (ProC := ProC) hι htarget φ hφ
  continuous_toFun :=
    continuous_freeProCZCCompletedFoxRightHom (ProC := ProC) X H hι htarget φ hφ

/-- The bundled right homomorphism has the expected underlying monoid homomorphism. -/
@[simp]
theorem freeProCZCCompletedFoxRightHomContinuousMonoidHom_toMonoidHom :
    (freeProCZCCompletedFoxRightHomContinuousMonoidHom
      (ProC := ProC) hι htarget φ hφ).toMonoidHom =
      freeProCZCCompletedFoxRightHom (ProC := ProC) hι htarget φ hφ :=
  rfl

/-- Evaluation of the bundled right homomorphism. -/
@[simp]
theorem freeProCZCCompletedFoxRightHomContinuousMonoidHom_apply (g : F) :
    freeProCZCCompletedFoxRightHomContinuousMonoidHom
        (ProC := ProC) hι htarget φ hφ g =
      freeProCZCCompletedFoxRightHom (ProC := ProC) hι htarget φ hφ g :=
  rfl

/-- The bundled right homomorphism has the prescribed generator values. -/
@[simp]
theorem freeProCZCCompletedFoxRightHomContinuousMonoidHom_generator (x : X) :
    freeProCZCCompletedFoxRightHomContinuousMonoidHom
        (ProC := ProC) hι htarget φ hφ (ι x) = φ x := by
  exact freeProCZCCompletedFoxRightHom_generator (ProC := ProC) hι htarget φ hφ x

/-- The completed free pro-`C` Fox derivative vector, bundled as a continuous map.  It is a
crossed differential, not a homomorphism. -/
def freeProCZCCompletedFoxDerivativeVectorContinuousMap :
    ContinuousMap F (ZCFreeFoxCoordinates ProC.finiteQuotientClass (X := X) (H := H)) where
  toFun := freeProCZCCompletedFoxDerivativeVector (ProC := ProC) hι htarget φ hφ
  continuous_toFun :=
    continuous_freeProCZCCompletedFoxDerivativeVector (ProC := ProC) X H hι htarget φ hφ

/-- Evaluation of the bundled continuous completed Fox derivative vector. -/
@[simp]
theorem freeProCZCCompletedFoxDerivativeVectorContinuousMap_apply (g : F) :
    freeProCZCCompletedFoxDerivativeVectorContinuousMap
        (ProC := ProC) hι htarget φ hφ g =
      freeProCZCCompletedFoxDerivativeVector (ProC := ProC) hι htarget φ hφ g :=
  rfl

/-- The bundled continuous completed Fox derivative vector has the prescribed generator values. -/
@[simp]
theorem freeProCZCCompletedFoxDerivativeVectorContinuousMap_generator (x : X) :
    freeProCZCCompletedFoxDerivativeVectorContinuousMap
        (ProC := ProC) hι htarget φ hφ (ι x) =
      Pi.single x (1 : ZCCompletedGroupAlgebra ProC.finiteQuotientClass H) := by
  simp only [freeProCZCCompletedFoxDerivativeVectorContinuousMap, ContinuousMap.coe_mk,
  freeProCZCCompletedFoxDerivativeVector_generator]

/-- The bundled continuous completed Fox derivative is a crossed differential. -/
theorem freeProCZCCompletedFoxDerivativeVectorContinuousMap_isCrossedDifferential :
    IsCrossedDifferential
      (zcCompletedGroupAlgebraScalar ProC.finiteQuotientClass
        (freeProCZCCompletedFoxRightHom (ProC := ProC) hι htarget φ hφ))
      (freeProCZCCompletedFoxDerivativeVectorContinuousMap
        (ProC := ProC) hι htarget φ hφ) := by
  exact freeProCZCCompletedFoxDerivativeVector_isCrossedDifferential
    (ProC := ProC) hι htarget φ hφ

/-- Restricting the continuous completed Fox derivative to the abstract free group generated by
the chosen free pro-`C` basis recovers the completed free-group Fox derivative. -/
theorem zcFreeGroupFoxDerivativeVector_eq_freeProCCompletedFoxDerivativeVector_comp_lift
    (w : FreeGroup X) :
    zcFreeGroupFoxDerivativeVector ProC.finiteQuotientClass
        ((freeProCZCCompletedFoxRightHom (ProC := ProC) hι htarget φ hφ).comp
          (FreeGroup.lift ι)) w =
      freeProCZCCompletedFoxDerivativeVector
        (ProC := ProC) hι htarget φ hφ ((FreeGroup.lift ι) w) := by
  let ρ : F →* H :=
    freeProCZCCompletedFoxRightHom (ProC := ProC) hι htarget φ hφ
  let D : F → ZCFreeFoxCoordinates ProC.finiteQuotientClass (X := X) (H := H) :=
    freeProCZCCompletedFoxDerivativeVector (ProC := ProC) hι htarget φ hφ
  let δ : FreeGroup X →
      ZCFreeFoxCoordinates ProC.finiteQuotientClass (X := X) (H := H) :=
    fun w => D ((FreeGroup.lift ι) w)
  have hδ :
      IsCrossedDifferential
        (zcCompletedGroupAlgebraScalar ProC.finiteQuotientClass (ρ.comp (FreeGroup.lift ι))) δ := by
    intro u v
    simpa [δ, ρ, D, map_mul, MonoidHom.comp_apply] using
      freeProCZCCompletedFoxDerivativeVector_isCrossedDifferential
        (ProC := ProC) hι htarget φ hφ ((FreeGroup.lift ι) u) ((FreeGroup.lift ι) v)
  have hbasis :
      ∀ x : X, δ (FreeGroup.of x) =
        Pi.single x (1 : ZCCompletedGroupAlgebra ProC.finiteQuotientClass H) := by
    intro x
    simp only [FreeGroup.lift_apply_of, freeProCZCCompletedFoxDerivativeVector_generator, δ, D]
  have hδeq :
      δ =
        zcFreeGroupFoxDerivativeVector ProC.finiteQuotientClass
          (ρ.comp (FreeGroup.lift ι)) :=
    zcFreeGroupFoxDerivativeVector_unique
      ProC.finiteQuotientClass (ρ.comp (FreeGroup.lift ι)) δ hδ hbasis
  exact congrFun hδeq w |>.symm

/-- Source restriction and target naturality for the continuous completed Fox derivative. -/
theorem zcFreeFoxDerivVec_eq_freeProCCompletedFoxDerivVec_comp_lift_mapTarget
    (hC : ProCGroups.FiniteGroupClass.Hereditary ProC.finiteQuotientClass)
    {K : Type u} [Group K] [TopologicalSpace K] [IsTopologicalGroup K]
    (η : H →ₜ* K) (w : FreeGroup X) :
    zcFreeGroupFoxDerivativeVector ProC.finiteQuotientClass
        (η.toMonoidHom.comp
          ((freeProCZCCompletedFoxRightHom (ProC := ProC) hι htarget φ hφ).comp
            (FreeGroup.lift ι))) w =
      zcFreeFoxCoordinatesMap (X := X) ProC.finiteQuotientClass hC η
        (freeProCZCCompletedFoxDerivativeVector
          (ProC := ProC) hι htarget φ hφ ((FreeGroup.lift ι) w)) := by
  rw [zcFreeGroupFoxDerivativeVector_mapTarget]
  rw [zcFreeGroupFoxDerivativeVector_eq_freeProCCompletedFoxDerivativeVector_comp_lift
    (ProC := ProC) hι htarget φ hφ w]

end FreeProCCompletedRules

section FreeProCConvergingSetCompletedRules

variable {ι : X → F}
variable (hι :
  ProCGroups.FreeProC.IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
variable (htarget : ProC (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))
variable (φ : X → H)
variable (hφconv :
  ProCGroups.FreeProC.FamilyConvergesToOne
    (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
    (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ))
variable (hφgen :
  ProCGroups.Generation.TopologicallyGenerates
    (G := ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)
    (Set.range (freeProCZCCompletedFoxSemidirectGenerator (ProC := ProC) φ)))

omit [TopologicalSpace X] in
/-- Restricting the converging-set continuous completed Fox derivative to the abstract free
group generated by the chosen free pro-`C` basis recovers the completed free-group Fox
derivative. -/
theorem zcFreeFoxDerivVec_eq_freeProCDerivVecOfConvergingSet_comp_lift
    (w : FreeGroup X) :
    zcFreeGroupFoxDerivativeVector ProC.finiteQuotientClass
        ((freeProCZCCompletedFoxRightHomOfConvergingSet
            (ProC := ProC) hι htarget φ hφconv hφgen).comp
          (FreeGroup.lift ι)) w =
      freeProCZCCompletedFoxDerivativeVectorOfConvergingSet
        (ProC := ProC) hι htarget φ hφconv hφgen ((FreeGroup.lift ι) w) := by
  let ρ : F →* H :=
    freeProCZCCompletedFoxRightHomOfConvergingSet
      (ProC := ProC) hι htarget φ hφconv hφgen
  let D : F → ZCFreeFoxCoordinates ProC.finiteQuotientClass (X := X) (H := H) :=
    freeProCZCCompletedFoxDerivativeVectorOfConvergingSet
      (ProC := ProC) hι htarget φ hφconv hφgen
  let δ : FreeGroup X →
      ZCFreeFoxCoordinates ProC.finiteQuotientClass (X := X) (H := H) :=
    fun w => D ((FreeGroup.lift ι) w)
  have hδ :
      IsCrossedDifferential
        (zcCompletedGroupAlgebraScalar ProC.finiteQuotientClass (ρ.comp (FreeGroup.lift ι))) δ := by
    intro u v
    simpa [δ, ρ, D, map_mul, MonoidHom.comp_apply] using
      freeProCZCCompletedFoxDerivativeVectorOfConvergingSet_isCrossedDifferential
        (ProC := ProC) hι htarget φ hφconv hφgen
        ((FreeGroup.lift ι) u) ((FreeGroup.lift ι) v)
  have hbasis :
      ∀ x : X, δ (FreeGroup.of x) =
        Pi.single x (1 : ZCCompletedGroupAlgebra ProC.finiteQuotientClass H) := by
    intro x
    simp only [FreeGroup.lift_apply_of, freeProCZCCompletedFoxDerivativeVectorOfConvergingSet_generator, δ, D]
  have hδeq :
      δ =
        zcFreeGroupFoxDerivativeVector ProC.finiteQuotientClass
          (ρ.comp (FreeGroup.lift ι)) :=
    zcFreeGroupFoxDerivativeVector_unique
      ProC.finiteQuotientClass (ρ.comp (FreeGroup.lift ι)) δ hδ hbasis
  exact congrFun hδeq w |>.symm

omit [TopologicalSpace X] in
/-- Source restriction and target naturality for the converging-set continuous completed Fox
derivative. -/
theorem zcFreeFoxDerivVec_eq_freeProCDerivVecOfConvergingSet_comp_lift_mapTarget
    (hC : ProCGroups.FiniteGroupClass.Hereditary ProC.finiteQuotientClass)
    {K : Type u} [Group K] [TopologicalSpace K] [IsTopologicalGroup K]
    (η : H →ₜ* K) (w : FreeGroup X) :
    zcFreeGroupFoxDerivativeVector ProC.finiteQuotientClass
        (η.toMonoidHom.comp
          ((freeProCZCCompletedFoxRightHomOfConvergingSet
              (ProC := ProC) hι htarget φ hφconv hφgen).comp
            (FreeGroup.lift ι))) w =
      zcFreeFoxCoordinatesMap (X := X) ProC.finiteQuotientClass hC η
        (freeProCZCCompletedFoxDerivativeVectorOfConvergingSet
          (ProC := ProC) hι htarget φ hφconv hφgen ((FreeGroup.lift ι) w)) := by
  rw [zcFreeGroupFoxDerivativeVector_mapTarget]
  rw [zcFreeFoxDerivVec_eq_freeProCDerivVecOfConvergingSet_comp_lift
    (ProC := ProC) hι htarget φ hφconv hφgen w]

end FreeProCConvergingSetCompletedRules

section FreeProCClosedGeneratedCompletedRules

variable {ι : X → F}
variable (hι :
  ProCGroups.FreeProC.IsFreeProCGroupOnConvergingSet (ProC := ProC) X F ι)
variable (φ : X → H)
variable (htarget :
  ProC (G :=
    (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
      (ProC := ProC) φ : Subgroup
        (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H))))
variable (hφconv :
  ProCGroups.FreeProC.FamilyConvergesToOne
    (G :=
      (freeProCZCCompletedFoxSemidirectClosedGeneratedTarget
        (ProC := ProC) φ : Subgroup
          (ZCCompletedFoxSemidirect ProC.finiteQuotientClass X H)))
    (freeProCZCCompletedFoxSemidirectClosedGeneratedGenerator (ProC := ProC) φ))

omit [TopologicalSpace X] in
/-- Restricting the closed-generated continuous completed Fox derivative to the abstract free
group generated by the chosen free pro-`C` basis recovers the completed free-group Fox
derivative. -/
theorem zcFreeFoxDerivVec_eq_freeProCDerivVecViaClosedGen_comp_lift
    (w : FreeGroup X) :
    zcFreeGroupFoxDerivativeVector ProC.finiteQuotientClass
        ((freeProCZCCompletedFoxRightHomViaClosedGenerated
            (ProC := ProC) hι φ htarget hφconv).comp
          (FreeGroup.lift ι)) w =
      freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
        (ProC := ProC) hι φ htarget hφconv ((FreeGroup.lift ι) w) := by
  let ρ : F →* H :=
    freeProCZCCompletedFoxRightHomViaClosedGenerated
      (ProC := ProC) hι φ htarget hφconv
  let D : F → ZCFreeFoxCoordinates ProC.finiteQuotientClass (X := X) (H := H) :=
    freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
      (ProC := ProC) hι φ htarget hφconv
  let δ : FreeGroup X →
      ZCFreeFoxCoordinates ProC.finiteQuotientClass (X := X) (H := H) :=
    fun w => D ((FreeGroup.lift ι) w)
  have hδ :
      IsCrossedDifferential
        (zcCompletedGroupAlgebraScalar ProC.finiteQuotientClass (ρ.comp (FreeGroup.lift ι))) δ := by
    intro u v
    simpa [δ, ρ, D, map_mul, MonoidHom.comp_apply] using
      freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated_isCrossedDifferential
        (ProC := ProC) hι φ htarget hφconv
        ((FreeGroup.lift ι) u) ((FreeGroup.lift ι) v)
  have hbasis :
      ∀ x : X, δ (FreeGroup.of x) =
        Pi.single x (1 : ZCCompletedGroupAlgebra ProC.finiteQuotientClass H) := by
    intro x
    simp only [FreeGroup.lift_apply_of, freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated_generator, δ, D]
  have hδeq :
      δ =
        zcFreeGroupFoxDerivativeVector ProC.finiteQuotientClass
          (ρ.comp (FreeGroup.lift ι)) :=
    zcFreeGroupFoxDerivativeVector_unique
      ProC.finiteQuotientClass (ρ.comp (FreeGroup.lift ι)) δ hδ hbasis
  exact congrFun hδeq w |>.symm

omit [TopologicalSpace X] in
/-- Source restriction and target naturality for the closed-generated continuous completed Fox
derivative. -/
theorem zcFreeFoxDerivVec_eq_freeProCDerivVecViaClosedGen_comp_lift_mapTarget
    (hC : ProCGroups.FiniteGroupClass.Hereditary ProC.finiteQuotientClass)
    {K : Type u} [Group K] [TopologicalSpace K] [IsTopologicalGroup K]
    (η : H →ₜ* K) (w : FreeGroup X) :
    zcFreeGroupFoxDerivativeVector ProC.finiteQuotientClass
        (η.toMonoidHom.comp
          ((freeProCZCCompletedFoxRightHomViaClosedGenerated
              (ProC := ProC) hι φ htarget hφconv).comp
            (FreeGroup.lift ι))) w =
      zcFreeFoxCoordinatesMap (X := X) ProC.finiteQuotientClass hC η
        (freeProCZCCompletedFoxDerivativeVectorViaClosedGenerated
          (ProC := ProC) hι φ htarget hφconv ((FreeGroup.lift ι) w)) := by
  rw [zcFreeGroupFoxDerivativeVector_mapTarget]
  rw [zcFreeFoxDerivVec_eq_freeProCDerivVecViaClosedGen_comp_lift
    (ProC := ProC) hι φ htarget hφconv w]

end FreeProCClosedGeneratedCompletedRules

end

end FoxDifferential
