import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.KernelEquivalence
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.OrderedTargetSignature
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.QuotientAndBasis
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.RelatorProofs
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.Relators.SourceCore
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.Relators.SourceHead
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.Relators.SourceMiddleTail
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.Relators.SourceTotal
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.Relators.Target
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.Signatures
import FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction.TransportMaps

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/FenchelNielsenZomorrodian/Discrete/CompactFuchsian/SecondReduction.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction

Wrapper for the `FenchelNielsenZomorrodian.Discrete.CompactFuchsian.SecondReduction` folder.
-/
