import ProCGroups.FreeProC.Characterization.EmbeddingProblems

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/ProCGroups/FreeProC/Characterization/Quasifree.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Free pro-C groups

Develops free pro-C groups on spaces and pointed spaces, their universal properties, finite quotient characterizations, and standard comparison isomorphisms.
-/

noncomputable section

open scoped Cardinal

namespace ProCGroups.FreeProC.Characterization

universe u

/-- An abstract group has a generating set of cardinality `κ`.  This is not the right rank
condition for quasifree profinite groups; use
`HasTopologicalGeneratingSetOfCardinality` there. -/
def HasGeneratingSetOfCardinality (G : Type u) [Group G] (κ : Cardinal) : Prop :=
  ∃ S : Set G, Subgroup.closure S = ⊤ ∧ Cardinal.mk S = κ

/-- A topological group has a topological generating set of cardinality `κ`. -/
def HasTopologicalGeneratingSetOfCardinality
    (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    (κ : Cardinal) : Prop :=
  ∃ S : Set G, Generation.TopologicallyGenerates (G := G) S ∧ Cardinal.mk S = κ

/-- A pro-`C` group is projective for finite `C`-embedding problems, stated as the concrete
lifting property used by the quasifree API. -/
def IsProjectiveProCGroup (C : ProCGroups.FiniteGroupClass.{u})
    (G : Type u) [Group G] [TopologicalSpace G] : Prop :=
  ProCGroups.ProC.IsProCGroup C G ∧
    ∀ {A B : Type u} [Group A] [Group B]
      [TopologicalSpace A] [TopologicalSpace B]
      [IsTopologicalGroup A] [IsTopologicalGroup B],
      ProCGroups.ProC.IsProCGroup C A → ProCGroups.ProC.IsProCGroup C B →
        (φ : G →ₜ* B) → (π : A →ₜ* B) → Function.Surjective π →
          ∃ lift : G →ₜ* A, π.comp lift = φ

/-- A group has the quasifree proper-solution property at rank `κ` for finite split
`C`-embedding problems. -/
def HasQuasifreeProperSolutionProperty
    (C : ProCGroups.FiniteGroupClass.{u})
    (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    (κ : Cardinal) : Prop :=
  ∀ P : TopologicalEmbeddingProblem G,
    IsFiniteSplitCEmbeddingProblem C P → P.HasAtLeastProperSolutions κ

/-- Quasifreeness at infinite rank `κ`.

The rank field is deliberately topological: in profinite contexts an abstract generating set is
too weak and does not control the closed subgroup generated by the chosen family.  The lifting
field records the standard proper-solution condition for finite split embedding problems. -/
def IsQuasifreeOfRank (C : ProCGroups.FiniteGroupClass.{u})
    (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    (κ : Cardinal) : Prop :=
  ProCGroups.ProC.IsProCGroup C G ∧
    HasTopologicalGeneratingSetOfCardinality G κ ∧
      Cardinal.aleph0 ≤ κ ∧
        HasQuasifreeProperSolutionProperty C G κ

end ProCGroups.FreeProC.Characterization
