import Mathlib.GroupTheory.FreeGroup.Reduce
import Mathlib.Tactic.NormNum.LegendreSymbol

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/ReidemeisterSchreier/Discrete/Presentations/Relators.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Relators modulo normal closure

This file contains the elementary discrete API for working modulo the normal
closure of a relator set.  It is independent of the project libraries outside
mathlib.

`RelatorEquivalent R u v` means that `u * v⁻¹` lies in
`Subgroup.normalClosure R`. Equivalently, `u` and `v` define the same element in
the quotient by that normal closure.  In presentation proofs, do relator
calculations with `RelatorEquivalent` first, use the paired normal-closure
membership lemmas when needed, and convert to quotient equality only at the
boundary.
-/

namespace ReidemeisterSchreier.Discrete.Presentations

variable {G H : Type*} [Group G] [Group H]

/-- Equality modulo the normal closure generated by `R`. -/
def RelatorEquivalent (R : Set G) (u v : G) : Prop :=
  u * v⁻¹ ∈ Subgroup.normalClosure R

theorem relatorEquivalent_iff_eq_in_presentedQuotient {R : Set G} {u v : G} :
    RelatorEquivalent R u v ↔
      ((u : G ⧸ Subgroup.normalClosure R) =
        (v : G ⧸ Subgroup.normalClosure R)) := by
  simpa [RelatorEquivalent, div_eq_mul_inv] using
    (QuotientGroup.eq_iff_div_mem
      (N := Subgroup.normalClosure R) (x := u) (y := v)).symm

@[simp] theorem relatorEquivalent_one_right {R : Set G} {u : G} :
    RelatorEquivalent R u 1 ↔ u ∈ Subgroup.normalClosure R := by
  simp only [RelatorEquivalent, inv_one, mul_one]

@[simp] theorem relatorEquivalent_one_left {R : Set G} {u : G} :
    RelatorEquivalent R 1 u ↔ u ∈ Subgroup.normalClosure R := by
  constructor
  · intro h
    have huInv : u⁻¹ ∈ Subgroup.normalClosure R := by
      simpa [RelatorEquivalent] using h
    simpa using Subgroup.inv_mem (Subgroup.normalClosure R) huInv
  · intro h
    have huInv : u⁻¹ ∈ Subgroup.normalClosure R :=
      Subgroup.inv_mem (Subgroup.normalClosure R) h
    simpa [RelatorEquivalent] using huInv

def relatorEquivalentSetoid (R : Set G) : Setoid G where
  r := RelatorEquivalent R
  iseqv := by
    refine ⟨?_, ?_, ?_⟩
    · intro u
      rw [relatorEquivalent_iff_eq_in_presentedQuotient]
    · intro u v h
      rw [relatorEquivalent_iff_eq_in_presentedQuotient] at h ⊢
      exact h.symm
    · intro u v w huv hvw
      rw [relatorEquivalent_iff_eq_in_presentedQuotient] at huv hvw ⊢
      exact huv.trans hvw

namespace RelatorEquivalent

variable {R S : Set G} {u v w a b r : G}

@[refl]
theorem refl (R : Set G) (u : G) : RelatorEquivalent R u u := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient]

theorem of_eq (h : u = v) : RelatorEquivalent R u v := by
  rw [h]

theorem symm (h : RelatorEquivalent R u v) : RelatorEquivalent R v u := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at h ⊢
  exact h.symm

theorem trans (h₁ : RelatorEquivalent R u v) (h₂ : RelatorEquivalent R v w) : RelatorEquivalent R u w := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at h₁ h₂ ⊢
  exact h₁.trans h₂

theorem inv (h : RelatorEquivalent R u v) : RelatorEquivalent R u⁻¹ v⁻¹ := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at h ⊢
  simpa using congrArg Inv.inv h

theorem mul (h₁ : RelatorEquivalent R u v) (h₂ : RelatorEquivalent R a b) :
    RelatorEquivalent R (u * a) (v * b) := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at h₁ h₂ ⊢
  calc
    ((u * a : G) : G ⧸ Subgroup.normalClosure R) =
        (u : G ⧸ Subgroup.normalClosure R) * (a : G ⧸ Subgroup.normalClosure R) := rfl
    _ = (v : G ⧸ Subgroup.normalClosure R) * (b : G ⧸ Subgroup.normalClosure R) := by
      rw [h₁, h₂]
    _ = ((v * b : G) : G ⧸ Subgroup.normalClosure R) := rfl

theorem pow (h : RelatorEquivalent R u v) (n : ℕ) : RelatorEquivalent R (u ^ n) (v ^ n) := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at h ⊢
  simpa using congrArg (fun z : G ⧸ Subgroup.normalClosure R => z ^ n) h

theorem zpow (h : RelatorEquivalent R u v) (n : ℤ) : RelatorEquivalent R (u ^ n) (v ^ n) := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at h ⊢
  simpa using congrArg (fun z : G ⧸ Subgroup.normalClosure R => z ^ n) h

theorem mul_eq_one (h₁ : RelatorEquivalent R u 1) (h₂ : RelatorEquivalent R v 1) :
    RelatorEquivalent R (u * v) 1 := by
  simpa using mul h₁ h₂

theorem pow_eq_one (h : RelatorEquivalent R u 1) (n : ℕ) :
    RelatorEquivalent R (u ^ n) 1 := by
  simpa using pow h n

theorem zpow_eq_one (h : RelatorEquivalent R u 1) (n : ℤ) :
    RelatorEquivalent R (u ^ n) 1 := by
  simpa using zpow h n

theorem inv_eq_one (h : RelatorEquivalent R u 1) :
    RelatorEquivalent R u⁻¹ 1 := by
  simpa using inv h

theorem conjugate_pow_eq (a u : G) (n : ℕ) :
    (a * u * a⁻¹) ^ n = a * u ^ n * a⁻¹ := by
  induction n with
  | zero =>
      simp only [pow_zero, mul_one, mul_inv_cancel]
  | succ n ih =>
      calc
        (a * u * a⁻¹) ^ (n + 1) =
            a * u ^ n * a⁻¹ * (a * u * a⁻¹) := by
              rw [pow_succ, ih]
        _ = a * (u ^ n * u) * a⁻¹ := by
              simp only [mul_assoc, inv_mul_cancel_left]
        _ = a * u ^ (n + 1) * a⁻¹ := by
              rw [pow_succ]

theorem mul_eq_one_iff_eq_inv :
    RelatorEquivalent R (u * v) 1 ↔ RelatorEquivalent R u v⁻¹ := by
  constructor
  · intro h
    simpa only [RelatorEquivalent, inv_inv, inv_one, mul_one] using h
  · intro h
    simpa only [RelatorEquivalent, inv_inv, inv_one, mul_one] using h

theorem eq_inv_of_mul_eq_one (h : RelatorEquivalent R (u * v) 1) :
    RelatorEquivalent R u v⁻¹ :=
  mul_eq_one_iff_eq_inv.1 h

theorem mul_eq_one_of_eq_inv (h : RelatorEquivalent R u v⁻¹) :
    RelatorEquivalent R (u * v) 1 :=
  mul_eq_one_iff_eq_inv.2 h

theorem eq_one_of_mul_eq_one_left
    (hu : RelatorEquivalent R u 1)
    (huv : RelatorEquivalent R (u * v) 1) :
    RelatorEquivalent R v 1 := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at hu huv ⊢
  calc
    (v : G ⧸ Subgroup.normalClosure R) =
        (1 : G ⧸ Subgroup.normalClosure R) * v := by simp only [one_mul]
    _ = (u : G ⧸ Subgroup.normalClosure R) * v := by
      simpa using congrArg
        (fun z : G ⧸ Subgroup.normalClosure R =>
          z * (v : G ⧸ Subgroup.normalClosure R)) hu.symm
    _ = ((u * v : G) : G ⧸ Subgroup.normalClosure R) := rfl
    _ = 1 := huv

theorem eq_one_of_mul_eq_one_right
    (huv : RelatorEquivalent R (u * v) 1)
    (hv : RelatorEquivalent R v 1) :
    RelatorEquivalent R u 1 := by
  rw [relatorEquivalent_iff_eq_in_presentedQuotient] at huv hv ⊢
  calc
    (u : G ⧸ Subgroup.normalClosure R) =
        (u : G ⧸ Subgroup.normalClosure R) * 1 := by simp only [mul_one]
    _ = (u : G ⧸ Subgroup.normalClosure R) * v := by
      simpa using congrArg
        (fun z : G ⧸ Subgroup.normalClosure R =>
          (u : G ⧸ Subgroup.normalClosure R) * z) hv.symm
    _ = ((u * v : G) : G ⧸ Subgroup.normalClosure R) := rfl
    _ = 1 := huv

theorem mul_left (h : RelatorEquivalent R u v) (a : G) : RelatorEquivalent R (a * u) (a * v) :=
  mul (refl R a) h

theorem mul_right (h : RelatorEquivalent R u v) (a : G) : RelatorEquivalent R (u * a) (v * a) :=
  mul h (refl R a)

/-- Replace a subword inside a two-sided context. -/
theorem context (h : RelatorEquivalent R u v) (a b : G) :
    RelatorEquivalent R (a * u * b) (a * v * b) :=
  mul_right (mul_left h a) b

theorem conj (h : RelatorEquivalent R u v) (a : G) :
    RelatorEquivalent R (a * u * a⁻¹) (a * v * a⁻¹) :=
  context h a a⁻¹

theorem conj_eq_one (h : RelatorEquivalent R u 1) (a : G) :
    RelatorEquivalent R (a * u * a⁻¹) 1 := by
  simpa using conj h a

theorem conj_pow_eq_one
    {n : ℕ} (h : RelatorEquivalent R (u ^ n) 1) (a : G) :
    RelatorEquivalent R ((a * u * a⁻¹) ^ n) 1 := by
  simpa [conjugate_pow_eq] using conj_eq_one h a

theorem of_mem (hr : r ∈ R) : RelatorEquivalent R r 1 := by
  simpa [RelatorEquivalent] using (Subgroup.subset_normalClosure hr :
    r ∈ Subgroup.normalClosure R)

theorem of_mem_normalClosure (hr : r ∈ Subgroup.normalClosure R) :
    RelatorEquivalent R r 1 := by
  simpa [RelatorEquivalent] using hr

theorem mono (hR_to_S : R ⊆ S) (h : RelatorEquivalent R u v) :
    RelatorEquivalent S u v := by
  have hx : u * v⁻¹ ∈ Subgroup.normalClosure S :=
    Subgroup.normalClosure_mono hR_to_S
      (by simpa [RelatorEquivalent] using h)
  simpa [RelatorEquivalent] using hx

theorem mono_iUnion {ι : Sort*} (R : ι → Set G)
    (i : ι) (h : RelatorEquivalent (R i) u v) :
    RelatorEquivalent (Set.iUnion R) u v :=
  mono (R := R i) (S := Set.iUnion R)
    (fun _ hx => Set.mem_iUnion.2 ⟨i, hx⟩) h

theorem mono_iUnion₂ {ι : Sort*} {κ : ι → Sort*}
    (R : ∀ i : ι, κ i → Set G)
    (i : ι) (j : κ i) (h : RelatorEquivalent (R i j) u v) :
    RelatorEquivalent (Set.iUnion fun i : ι => Set.iUnion (R i)) u v :=
  mono (R := R i j) (S := Set.iUnion fun i : ι => Set.iUnion (R i))
    (fun _ hx => Set.mem_iUnion.2 ⟨i, Set.mem_iUnion.2 ⟨j, hx⟩⟩) h

theorem mem_normalClosure_of_eq_one (h : RelatorEquivalent R r 1) :
    r ∈ Subgroup.normalClosure R := by
  simpa [RelatorEquivalent] using h

theorem mul_inv_mem_normalClosure (h : RelatorEquivalent R u v) :
    u * v⁻¹ ∈ Subgroup.normalClosure R := by
  simpa [RelatorEquivalent] using h

theorem div_mem_normalClosure (h : RelatorEquivalent R u v) :
    u / v ∈ Subgroup.normalClosure R := by
  simpa [div_eq_mul_inv] using h.mul_inv_mem_normalClosure

theorem mul_inv_eq_one (h : RelatorEquivalent R u v) :
    RelatorEquivalent R (u * v⁻¹) 1 :=
  of_mem_normalClosure h.mul_inv_mem_normalClosure

theorem div_eq_one (h : RelatorEquivalent R u v) :
    RelatorEquivalent R (u / v) 1 := by
  simpa [div_eq_mul_inv] using h.mul_inv_eq_one

theorem one_eq_of_mem_inv (hr : r ∈ R) : RelatorEquivalent R 1 r :=
  (of_mem hr).symm

end RelatorEquivalent

section NormalClosure

variable {R S : Set G} {r a b : G}

theorem mem_normalClosure_of_subset
    (hR_to_S : R ⊆ S) {x : G}
    (hx : x ∈ Subgroup.normalClosure R) :
    x ∈ Subgroup.normalClosure S :=
  Subgroup.normalClosure_mono hR_to_S hx

theorem mem_normalClosure_union_left
    {x : G} (hx : x ∈ Subgroup.normalClosure R) :
    x ∈ Subgroup.normalClosure (R ∪ S) :=
  mem_normalClosure_of_subset (R := R) (S := R ∪ S)
    (Set.subset_union_left) hx

theorem mem_normalClosure_union_right
    {x : G} (hx : x ∈ Subgroup.normalClosure S) :
    x ∈ Subgroup.normalClosure (R ∪ S) :=
  mem_normalClosure_of_subset (R := S) (S := R ∪ S)
    (Set.subset_union_right) hx

theorem mem_normalClosure_iUnion
    {ι : Sort*} (R : ι → Set G) (i : ι)
    {x : G} (hx : x ∈ Subgroup.normalClosure (R i)) :
    x ∈ Subgroup.normalClosure (Set.iUnion R) :=
  mem_normalClosure_of_subset (R := R i) (S := Set.iUnion R)
    (fun _ hy => Set.mem_iUnion.2 ⟨i, hy⟩) hx

theorem mem_normalClosure_iUnion₂
    {ι : Sort*} {κ : ι → Sort*}
    (R : ∀ i : ι, κ i → Set G) (i : ι) (j : κ i)
    {x : G} (hx : x ∈ Subgroup.normalClosure (R i j)) :
    x ∈ Subgroup.normalClosure
        (Set.iUnion fun i : ι => Set.iUnion (R i)) :=
  mem_normalClosure_of_subset
    (R := R i j)
    (S := Set.iUnion fun i : ι => Set.iUnion (R i))
    (fun _ hy => Set.mem_iUnion.2 ⟨i, Set.mem_iUnion.2 ⟨j, hy⟩⟩) hx

theorem mem_normalClosure_iUnion₂_of_exists
    {ι : Sort*} {κ : ι → Sort*}
    (R : ∀ i : ι, κ i → Set G)
    {x : G} (hx : ∃ i : ι, ∃ j : κ i,
      x ∈ Subgroup.normalClosure (R i j)) :
    x ∈ Subgroup.normalClosure
        (Set.iUnion fun i : ι => Set.iUnion (R i)) := by
  rcases hx with ⟨i, j, hij⟩
  exact mem_normalClosure_iUnion₂ (R := R) i j hij

theorem maps_iUnion_relators_mem_normalClosure
    {ι : Sort*} (f : G →* H) {R : ι → Set G} {S : Set H}
    (hR : ∀ i : ι, ∀ r ∈ R i, f r ∈ Subgroup.normalClosure S) :
    ∀ r ∈ Set.iUnion R, f r ∈ Subgroup.normalClosure S := by
  intro r hr
  rcases Set.mem_iUnion.1 hr with ⟨i, hi⟩
  exact hR i r hi

theorem maps_iUnion₂_relators_mem_normalClosure
    {ι : Sort*} {κ : ι → Sort*}
    (f : G →* H) {R : ∀ i : ι, κ i → Set G} {S : Set H}
    (hR : ∀ i : ι, ∀ j : κ i, ∀ r ∈ R i j,
      f r ∈ Subgroup.normalClosure S) :
    ∀ r ∈ Set.iUnion (fun i : ι => Set.iUnion (R i)),
      f r ∈ Subgroup.normalClosure S := by
  intro r hr
  rcases Set.mem_iUnion.1 hr with ⟨i, hi⟩
  rcases Set.mem_iUnion.1 hi with ⟨j, hj⟩
  exact hR i j r hj

theorem map_mem_normalClosure_of_relators
    (f : G →* H) {R : Set G} {S : Set H}
    (hR : ∀ r ∈ R, f r ∈ Subgroup.normalClosure S)
    {x : G} (hx : x ∈ Subgroup.normalClosure R) :
    f x ∈ Subgroup.normalClosure S := by
  let N : Subgroup G := Subgroup.comap f (Subgroup.normalClosure S)
  have hle : Subgroup.normalClosure R ≤ N := by
    refine Subgroup.normalClosure_le_normal ?_
    intro r hr
    exact hR r hr
  exact hle hx

theorem hom_relatorEquivalent_of_maps_relators
    (f : G →* H) {R : Set G} {S : Set H}
    (hR : ∀ r ∈ R, f r ∈ Subgroup.normalClosure S)
    {u v : G} (h : RelatorEquivalent R u v) :
    RelatorEquivalent S (f u) (f v) := by
  have hx :
      f (u * v⁻¹) ∈ Subgroup.normalClosure S :=
    map_mem_normalClosure_of_relators f hR (by simpa [RelatorEquivalent] using h)
  simpa [RelatorEquivalent, map_mul] using hx

theorem hom_relatorEquivalent_of_maps_relators_relatorEquivalent
    (f : G →* H) {R : Set G} {S : Set H}
    (hR : ∀ r ∈ R, RelatorEquivalent S (f r) 1)
    {u v : G} (h : RelatorEquivalent R u v) :
    RelatorEquivalent S (f u) (f v) :=
  hom_relatorEquivalent_of_maps_relators f
    (fun r hr => RelatorEquivalent.mem_normalClosure_of_eq_one (hR r hr)) h

theorem map_mem_normalClosure_iUnion_of_relators
    {ι : Sort*} (f : G →* H) {R : ι → Set G} {S : Set H}
    (hR : ∀ i : ι, ∀ r ∈ R i, f r ∈ Subgroup.normalClosure S)
    {x : G} (hx : x ∈ Subgroup.normalClosure (Set.iUnion R)) :
    f x ∈ Subgroup.normalClosure S :=
  map_mem_normalClosure_of_relators f
    (maps_iUnion_relators_mem_normalClosure f hR) hx

theorem map_mem_normalClosure_iUnion₂_of_relators
    {ι : Sort*} {κ : ι → Sort*}
    (f : G →* H) {R : ∀ i : ι, κ i → Set G} {S : Set H}
    (hR : ∀ i : ι, ∀ j : κ i, ∀ r ∈ R i j,
      f r ∈ Subgroup.normalClosure S)
    {x : G}
    (hx : x ∈ Subgroup.normalClosure
      (Set.iUnion fun i : ι => Set.iUnion (R i))) :
    f x ∈ Subgroup.normalClosure S :=
  map_mem_normalClosure_of_relators f
    (maps_iUnion₂_relators_mem_normalClosure f hR) hx

theorem hom_relatorEquivalent_of_maps_iUnion_relators
    {ι : Sort*} (f : G →* H) {R : ι → Set G} {S : Set H}
    (hR : ∀ i : ι, ∀ r ∈ R i, f r ∈ Subgroup.normalClosure S)
    {u v : G} (h : RelatorEquivalent (Set.iUnion R) u v) :
    RelatorEquivalent S (f u) (f v) :=
  hom_relatorEquivalent_of_maps_relators f
    (maps_iUnion_relators_mem_normalClosure f hR) h

theorem hom_relatorEquivalent_of_maps_iUnion_relators_relatorEquivalent
    {ι : Sort*} (f : G →* H) {R : ι → Set G} {S : Set H}
    (hR : ∀ i : ι, ∀ r ∈ R i, RelatorEquivalent S (f r) 1)
    {u v : G} (h : RelatorEquivalent (Set.iUnion R) u v) :
    RelatorEquivalent S (f u) (f v) :=
  hom_relatorEquivalent_of_maps_iUnion_relators f
    (fun i r hr => RelatorEquivalent.mem_normalClosure_of_eq_one (hR i r hr)) h

theorem hom_relatorEquivalent_of_maps_iUnion₂_relators
    {ι : Sort*} {κ : ι → Sort*}
    (f : G →* H) {R : ∀ i : ι, κ i → Set G} {S : Set H}
    (hR : ∀ i : ι, ∀ j : κ i, ∀ r ∈ R i j,
      f r ∈ Subgroup.normalClosure S)
    {u v : G}
    (h : RelatorEquivalent
      (Set.iUnion fun i : ι => Set.iUnion (R i)) u v) :
    RelatorEquivalent S (f u) (f v) :=
  hom_relatorEquivalent_of_maps_relators f
    (maps_iUnion₂_relators_mem_normalClosure f hR) h

theorem hom_relatorEquivalent_of_maps_iUnion₂_relators_relatorEquivalent
    {ι : Sort*} {κ : ι → Sort*}
    (f : G →* H) {R : ∀ i : ι, κ i → Set G} {S : Set H}
    (hR : ∀ i : ι, ∀ j : κ i, ∀ r ∈ R i j,
      RelatorEquivalent S (f r) 1)
    {u v : G}
    (h : RelatorEquivalent
      (Set.iUnion fun i : ι => Set.iUnion (R i)) u v) :
    RelatorEquivalent S (f u) (f v) :=
  hom_relatorEquivalent_of_maps_iUnion₂_relators f
    (fun i j r hr => RelatorEquivalent.mem_normalClosure_of_eq_one (hR i j r hr)) h

section FreeGroupLift

variable {X : Type*}

theorem freeGroup_relatorEquivalent_of_toWord_eq_reduce
    [DecidableEq X]
    {R : Set (FreeGroup X)} {u : FreeGroup X} {w : List (X × Bool)}
    (h : u.toWord = FreeGroup.reduce w) :
    RelatorEquivalent R u (FreeGroup.mk w) := by
  apply RelatorEquivalent.of_eq
  rw [← FreeGroup.toWord_inj]
  simp only [h, FreeGroup.toWord_mk]

theorem freeGroup_relatorEquivalent_mk_of_reduce_eq
    [DecidableEq X]
    {R : Set (FreeGroup X)} {u : FreeGroup X} {w : List (X × Bool)}
    (h : FreeGroup.reduce w = u.toWord) :
    RelatorEquivalent R (FreeGroup.mk w) u :=
  (freeGroup_relatorEquivalent_of_toWord_eq_reduce
    (R := R) (u := u) (w := w) h.symm).symm

def freeGroupSubstitutionWord {Y : Type*} [DecidableEq Y]
    (f : X → FreeGroup Y) :
    List (X × Bool) → List (Y × Bool)
  | [] => []
  | (x, true) :: xs => (f x).toWord ++ freeGroupSubstitutionWord f xs
  | (x, false) :: xs => FreeGroup.invRev (f x).toWord ++ freeGroupSubstitutionWord f xs

@[simp]
theorem freeGroupSubstitutionWord_nil {Y : Type*} [DecidableEq Y]
    (f : X → FreeGroup Y) :
    freeGroupSubstitutionWord f [] = [] :=
  rfl

@[simp]
theorem freeGroupSubstitutionWord_cons_true {Y : Type*} [DecidableEq Y]
    (f : X → FreeGroup Y) (x : X) (xs : List (X × Bool)) :
    freeGroupSubstitutionWord f ((x, true) :: xs) =
      (f x).toWord ++ freeGroupSubstitutionWord f xs :=
  rfl

@[simp]
theorem freeGroupSubstitutionWord_cons_false {Y : Type*} [DecidableEq Y]
    (f : X → FreeGroup Y) (x : X) (xs : List (X × Bool)) :
    freeGroupSubstitutionWord f ((x, false) :: xs) =
      FreeGroup.invRev (f x).toWord ++ freeGroupSubstitutionWord f xs :=
  rfl

theorem freeGroupSubstitutionWord_append {Y : Type*} [DecidableEq Y]
    (f : X → FreeGroup Y) (xs ys : List (X × Bool)) :
    freeGroupSubstitutionWord f (xs ++ ys) =
      freeGroupSubstitutionWord f xs ++ freeGroupSubstitutionWord f ys := by
  induction xs with
  | nil => simp
  | cons xb xs ih =>
      rcases xb with ⟨x, b⟩
      cases b
      · simp only [List.cons_append, freeGroupSubstitutionWord_cons_false, ih, List.append_assoc]
      · simp only [List.cons_append, freeGroupSubstitutionWord_cons_true, ih, List.append_assoc]

theorem freeGroup_mk_substitutionWord {Y : Type*} [DecidableEq Y]
    (f : X → FreeGroup Y) (xs : List (X × Bool)) :
    FreeGroup.mk (freeGroupSubstitutionWord f xs) =
      FreeGroup.lift f (FreeGroup.mk xs) := by
  induction xs with
  | nil => exact FreeGroup.one_eq_mk.symm
  | cons xb xs ih =>
      rcases xb with ⟨x, b⟩
      cases b
      · rw [freeGroupSubstitutionWord_cons_false, ← FreeGroup.mul_mk,
          ← FreeGroup.inv_mk, FreeGroup.mk_toWord, ih]
        simp only [FreeGroup.lift_mk, List.map_cons, cond_false, List.prod_cons]
      · rw [freeGroupSubstitutionWord_cons_true, ← FreeGroup.mul_mk,
          FreeGroup.mk_toWord, ih]
        simp only [FreeGroup.lift_mk, List.map_cons, cond_true, List.prod_cons]

theorem freeGroup_toWord_lift_mk {Y : Type*} [DecidableEq Y]
    (f : X → FreeGroup Y) (xs : List (X × Bool)) :
    (FreeGroup.lift f (FreeGroup.mk xs)).toWord =
      FreeGroup.reduce (freeGroupSubstitutionWord f xs) := by
  rw [← freeGroup_mk_substitutionWord (f := f) (xs := xs)]
  simp only [FreeGroup.toWord_mk]

theorem freeGroup_lift_mk_eq_mk_of_substitutionWord_reduce_eq
    {Y : Type*} [DecidableEq Y]
    {f : X → FreeGroup Y} {xs : List (X × Bool)}
    {ys : List (Y × Bool)}
    (h :
      FreeGroup.reduce (freeGroupSubstitutionWord f xs) =
        FreeGroup.reduce ys) :
    FreeGroup.lift f (FreeGroup.mk xs) = FreeGroup.mk ys := by
  rw [← FreeGroup.toWord_inj]
  rw [freeGroup_toWord_lift_mk, FreeGroup.toWord_mk, h]

theorem freeGroup_relatorEquivalent_lift_mk_of_substitutionWord_reduce_eq
    {Y : Type*} [DecidableEq Y]
    {R : Set (FreeGroup Y)}
    {f : X → FreeGroup Y} {xs : List (X × Bool)}
    {ys : List (Y × Bool)}
    (h :
      FreeGroup.reduce (freeGroupSubstitutionWord f xs) =
        FreeGroup.reduce ys) :
    RelatorEquivalent R (FreeGroup.lift f (FreeGroup.mk xs))
      (FreeGroup.mk ys) :=
  RelatorEquivalent.of_eq
    (freeGroup_lift_mk_eq_mk_of_substitutionWord_reduce_eq h)

theorem freeGroup_relatorEquivalent_lift_mk_one_of_substitutionWord_reduce_eq
    {Y : Type*} [DecidableEq Y]
    {R : Set (FreeGroup Y)}
    {f : X → FreeGroup Y} {xs : List (X × Bool)}
    {ys : List (Y × Bool)}
    (h :
      FreeGroup.reduce (freeGroupSubstitutionWord f xs) =
        FreeGroup.reduce ys)
    (hy : RelatorEquivalent R (FreeGroup.mk ys) 1) :
    RelatorEquivalent R (FreeGroup.lift f (FreeGroup.mk xs)) 1 :=
  (freeGroup_relatorEquivalent_lift_mk_of_substitutionWord_reduce_eq
    (R := R) h).trans hy

theorem freeGroup_lift_relatorEquivalent_of_generator_relatorEquivalent
    {R : Set G} {f g : X → G}
    (h : ∀ x : X, RelatorEquivalent R (f x) (g x))
    (w : FreeGroup X) :
    RelatorEquivalent R (FreeGroup.lift f w) (FreeGroup.lift g w) := by
  let N : Subgroup G := Subgroup.normalClosure R
  let F : FreeGroup X →* G ⧸ N :=
    (QuotientGroup.mk' N).comp (FreeGroup.lift f)
  let K : FreeGroup X →* G ⧸ N :=
    (QuotientGroup.mk' N).comp (FreeGroup.lift g)
  have hhom : F = K := by
    ext x
    dsimp [F, K]
    simp only [FreeGroup.lift_apply_of]
    rw [← relatorEquivalent_iff_eq_in_presentedQuotient]
    exact h x
  have hw := congrArg (fun φ : FreeGroup X →* G ⧸ N => φ w) hhom
  change ((FreeGroup.lift f w : G) : G ⧸ N) =
    ((FreeGroup.lift g w : G) : G ⧸ N) at hw
  exact relatorEquivalent_iff_eq_in_presentedQuotient.2 hw

theorem freeGroup_lift_relatorEquivalent_one_of_generator_relatorEquivalent
    {R : Set G} {f : X → G}
    (h : ∀ x : X, RelatorEquivalent R (f x) 1)
    (w : FreeGroup X) :
    RelatorEquivalent R (FreeGroup.lift f w) 1 := by
  let trivialLift : FreeGroup X →* G :=
    FreeGroup.lift (fun _ : X => (1 : G))
  have htrivial : trivialLift w = 1 := by
    have hhom : trivialLift = 1 := by
      ext x
      simp only [FreeGroup.lift_apply_of, MonoidHom.one_apply, trivialLift]
    exact congrArg (fun φ : FreeGroup X →* G => φ w) hhom
  simpa [trivialLift, htrivial] using
    freeGroup_lift_relatorEquivalent_of_generator_relatorEquivalent
      (R := R) (f := f) (g := fun _ : X => (1 : G)) h w

theorem freeGroup_lift_relatorEquivalent_of_generator_eq
    {R : Set G} {f g : X → G}
    (h : ∀ x : X, f x = g x)
    (w : FreeGroup X) :
    RelatorEquivalent R (FreeGroup.lift f w) (FreeGroup.lift g w) :=
  freeGroup_lift_relatorEquivalent_of_generator_relatorEquivalent
    (R := R) (f := f) (g := g)
    (fun x => RelatorEquivalent.of_eq (h x)) w

end FreeGroupLift

/-- If every relator on each side is trivial modulo the other side, the normal
closures are equal. -/
theorem normalClosure_eq_of_relatorEquivalent
    (hR_to_S : ∀ r ∈ R, RelatorEquivalent S r 1)
    (hS_to_R : ∀ s ∈ S, RelatorEquivalent R s 1) :
    Subgroup.normalClosure R = Subgroup.normalClosure S := by
  apply le_antisymm
  · refine Subgroup.normalClosure_le_normal ?_
    intro r hr
    exact RelatorEquivalent.mem_normalClosure_of_eq_one (hR_to_S r hr)
  · refine Subgroup.normalClosure_le_normal ?_
    intro s hs
    exact RelatorEquivalent.mem_normalClosure_of_eq_one (hS_to_R s hs)

theorem normalClosure_insert_eq_of_mem
    (hr : r ∈ Subgroup.normalClosure R) :
    Subgroup.normalClosure (insert r R) = Subgroup.normalClosure R := by
  apply le_antisymm
  · refine Subgroup.normalClosure_le_normal ?_
    intro x hx
    rcases hx with rfl | hx
    · exact hr
    · exact Subgroup.subset_normalClosure hx
  · exact Subgroup.normalClosure_mono (by
      intro x hx
      exact Set.mem_insert_of_mem r hx)

theorem normalClosure_diff_singleton_eq_of_mem
    (hr : r ∈ Subgroup.normalClosure (R \ {r})) :
    Subgroup.normalClosure R = Subgroup.normalClosure (R \ {r}) := by
  apply le_antisymm
  · refine Subgroup.normalClosure_le_normal ?_
    intro x hx
    by_cases hxr : x = r
    · simpa [hxr] using hr
    · exact Subgroup.subset_normalClosure ⟨hx, by simpa [Set.mem_singleton_iff] using hxr⟩
  · exact Subgroup.normalClosure_mono (by
      intro x hx
      exact hx.1)

theorem normalClosure_eq_of_subset_normalClosure
    (hR_to_S : R ⊆ Subgroup.normalClosure S)
    (hS_to_R : S ⊆ Subgroup.normalClosure R) :
    Subgroup.normalClosure R = Subgroup.normalClosure S := by
  apply le_antisymm
  · exact Subgroup.normalClosure_le_normal hR_to_S
  · exact Subgroup.normalClosure_le_normal hS_to_R

theorem conjugate_mem_normalClosure_of_mem
    (hr : r ∈ R) (a : G) :
    a * r * a⁻¹ ∈ Subgroup.normalClosure R := by
  simpa [mul_assoc] using
    (Subgroup.normalClosure_normal.conj_mem r
      (Subgroup.subset_normalClosure hr) a)

theorem conjugate_mem_normalClosure
    (hr : r ∈ Subgroup.normalClosure R) (a : G) :
    a * r * a⁻¹ ∈ Subgroup.normalClosure R := by
  simpa [mul_assoc] using
    (Subgroup.normalClosure_normal.conj_mem r hr a)

/-- Cyclically rotating a relator keeps it in the same normal closure. -/
theorem cyclic_rotation_mem_normalClosure
    (h : a * b ∈ Subgroup.normalClosure R) :
    b * a ∈ Subgroup.normalClosure R := by
  have hc := conjugate_mem_normalClosure (R := R) h b
  simpa [mul_assoc] using hc

theorem mem_of_left_mul_mem_normalClosure
    {a b : G}
    (ha : a ∈ Subgroup.normalClosure R)
    (hab : a * b ∈ Subgroup.normalClosure R) :
    b ∈ Subgroup.normalClosure R := by
  let N : Subgroup G := Subgroup.normalClosure R
  have h : a⁻¹ * (a * b) ∈ N := N.mul_mem (N.inv_mem ha) hab
  simpa [N, mul_assoc] using h

theorem cyclic_rotation_pow_mem_normalClosure
    {a b : G} {n : ℕ}
    (h : (a * b) ^ n ∈ Subgroup.normalClosure R) :
    (b * a) ^ n ∈ Subgroup.normalClosure R := by
  let N : Subgroup G := Subgroup.normalClosure R
  have hconj : b * ((a * b) ^ n) * b⁻¹ ∈ N := by
    simpa [N, MulAut.conj_apply] using
      (Subgroup.normalClosure_normal.conj_mem ((a * b) ^ n) h b)
  have hpow : b * ((a * b) ^ n) * b⁻¹ = (b * a) ^ n := by
    clear h hconj
    induction n with
    | zero =>
        simp only [pow_zero, mul_one, mul_inv_cancel]
    | succ n ih =>
        rw [pow_succ, pow_succ, ← ih]
        group
  simpa [hpow] using hconj

theorem pow_mem_normalClosure_of_mul_inv_mem
    {u v : G} {n : ℕ}
    (huv : u * v⁻¹ ∈ Subgroup.normalClosure R)
    (hv : v ^ n ∈ Subgroup.normalClosure R) :
    u ^ n ∈ Subgroup.normalClosure R := by
  let N : Subgroup G := Subgroup.normalClosure R
  let q : G →* G ⧸ N := QuotientGroup.mk' N
  have hq : q u = q v := by
    exact
      (QuotientGroup.eq_iff_div_mem (N := N) (x := u) (y := v)).2
        (by simpa [N, div_eq_mul_inv] using huv)
  have hqv : q (v ^ n) = 1 :=
    (QuotientGroup.eq_one_iff (N := N) (v ^ n)).2 hv
  have hqu : q (u ^ n) = 1 := by
    rw [map_pow, hq, ← map_pow]
    exact hqv
  exact (QuotientGroup.eq_one_iff (N := N) (u ^ n)).1 hqu

theorem list_prod_mem_normalClosure
    {l : List G}
    (h : ∀ x ∈ l, x ∈ Subgroup.normalClosure R) :
    l.prod ∈ Subgroup.normalClosure R := by
  induction l with
  | nil =>
      simp only [List.prod_nil, one_mem]
  | cons x xs ih =>
      simp only [List.mem_cons] at h
      exact Subgroup.mul_mem (Subgroup.normalClosure R)
        (h x (Or.inl rfl))
        (ih (by
          intro y hy
          exact h y (Or.inr hy)))

theorem list_prod_map_relatorEquivalent
    {ι : Type*} (l : List ι) {f g : ι → G}
    (h : ∀ i ∈ l, RelatorEquivalent R (f i) (g i)) :
    RelatorEquivalent R (l.map f).prod (l.map g).prod := by
  induction l with
  | nil =>
      exact RelatorEquivalent.refl R 1
  | cons i is ih =>
      simp only [List.mem_cons] at h
      simpa using RelatorEquivalent.mul
        (h i (Or.inl rfl))
        (ih (by
          intro j hj
          exact h j (Or.inr hj)))

theorem list_prod_map_relatorEquivalent_one
    {ι : Type*} (l : List ι) {f : ι → G}
    (h : ∀ i ∈ l, RelatorEquivalent R (f i) 1) :
    RelatorEquivalent R (l.map f).prod 1 := by
  simpa using
    list_prod_map_relatorEquivalent (R := R) l
      (f := f) (g := fun _ => (1 : G)) h

theorem list_prod_map_inv_reverse (l : List G) :
    (l.map Inv.inv).reverse.prod = l.prod⁻¹ := by
  induction l with
  | nil =>
      simp only [List.map_nil, List.reverse_nil, List.prod_nil, inv_one]
  | cons x xs ih =>
      simp only [List.map_cons, List.reverse_cons, List.prod_append, ih, List.prod_cons, List.prod_nil, mul_one,
  mul_inv_rev]

theorem list_prod_reverse_map_inv (l : List G) :
    (l.reverse.map Inv.inv).prod = l.prod⁻¹ := by
  simpa [List.map_reverse] using list_prod_map_inv_reverse (G := G) l

theorem list_prod_reverse_inv_relatorEquivalent
    {l m : List G}
    (h : RelatorEquivalent R l.prod m.prod) :
    RelatorEquivalent R (l.reverse.map Inv.inv).prod
      (m.reverse.map Inv.inv).prod := by
  simpa [List.map_reverse, list_prod_map_inv_reverse] using
    RelatorEquivalent.inv h

theorem list_prod_append_relatorEquivalent
    {l₁ l₂ m₁ m₂ : List G}
    (h₁ : RelatorEquivalent R l₁.prod m₁.prod)
    (h₂ : RelatorEquivalent R l₂.prod m₂.prod) :
    RelatorEquivalent R (l₁ ++ l₂).prod (m₁ ++ m₂).prod := by
  simpa using RelatorEquivalent.mul h₁ h₂

theorem list_prod_append_left_relatorEquivalent
    (l : List G) {m n : List G}
    (h : RelatorEquivalent R m.prod n.prod) :
    RelatorEquivalent R (l ++ m).prod (l ++ n).prod := by
  exact list_prod_append_relatorEquivalent
    (R := R) (l₁ := l) (l₂ := m) (m₁ := l) (m₂ := n)
    (RelatorEquivalent.refl R l.prod) h

theorem list_prod_middle_eq_one_relatorEquivalent
    (l m : List G) {u : G}
    (h : RelatorEquivalent R u 1) :
    RelatorEquivalent R (l ++ u :: m).prod (l ++ m).prod := by
  have htail :
      RelatorEquivalent R (u :: m).prod m.prod := by
    simpa using RelatorEquivalent.mul h (RelatorEquivalent.refl R m.prod)
  simpa [List.singleton_append] using
    list_prod_append_left_relatorEquivalent (R := R) l htail

theorem list_prod_middle_mul_inv_relatorEquivalent
    (l m : List G) {u v : G}
    (h : RelatorEquivalent R u v) :
    RelatorEquivalent R (l ++ (u * v⁻¹) :: m).prod
      (l ++ m).prod :=
  list_prod_middle_eq_one_relatorEquivalent (R := R) l m
    (RelatorEquivalent.mul_inv_eq_one h)

theorem list_prod_append_rotate_mem_normalClosure
    {l m : List G}
    (h : (l ++ m).prod ∈ Subgroup.normalClosure R) :
    (m ++ l).prod ∈ Subgroup.normalClosure R := by
  have hprod : l.prod * m.prod ∈ Subgroup.normalClosure R := by
    simpa using h
  have hrot :
      m.prod * l.prod ∈ Subgroup.normalClosure R :=
    cyclic_rotation_mem_normalClosure (R := R)
      (a := l.prod) (b := m.prod) hprod
  simpa using hrot

theorem list_prod_append_rotate_relatorEquivalent
    {l m : List G}
    (h : RelatorEquivalent R (l ++ m).prod 1) :
    RelatorEquivalent R (m ++ l).prod 1 := by
  exact RelatorEquivalent.of_mem_normalClosure
    (list_prod_append_rotate_mem_normalClosure (R := R)
      (by simpa [RelatorEquivalent] using h))

theorem list_prod_rotate_to_front_relatorEquivalent
    {l m : List G}
    (h : RelatorEquivalent R (l ++ m).prod 1) :
    RelatorEquivalent R (m ++ l).prod 1 :=
  list_prod_append_rotate_relatorEquivalent (R := R) h

theorem list_prod_take_drop_rotate_relatorEquivalent
    (l : List G) (n : ℕ)
    (h : RelatorEquivalent R l.prod 1) :
    RelatorEquivalent R ((l.drop n) ++ (l.take n)).prod 1 := by
  have hsplit :
      RelatorEquivalent R ((l.take n) ++ (l.drop n)).prod 1 := by
    simpa [List.take_append_drop] using h
  exact list_prod_append_rotate_relatorEquivalent (R := R) hsplit

theorem list_prod_take_drop_rotate_mem_normalClosure
    (l : List G) (n : ℕ)
    (h : l.prod ∈ Subgroup.normalClosure R) :
    ((l.drop n) ++ (l.take n)).prod ∈ Subgroup.normalClosure R :=
  RelatorEquivalent.mem_normalClosure_of_eq_one
    (list_prod_take_drop_rotate_relatorEquivalent (R := R) l n
      (RelatorEquivalent.of_mem_normalClosure (by simpa [RelatorEquivalent] using h)))

section OrderedFinsetProduct

variable {ι : Type*} [LinearOrder ι]

/-- A noncommutative product indexed by a finite set, using the ambient
`LinearOrder` to choose the order.  This is the right finite-indexed dispatcher
for relator calculations in noncommutative groups. -/
def orderedFinsetProduct (s : Finset ι) (f : ι → G) : G :=
  ((s.sort (· ≤ ·)).map f).prod

theorem orderedFinsetProduct_mem_normalClosure
    (s : Finset ι) {f : ι → G}
    (h : ∀ i ∈ s, f i ∈ Subgroup.normalClosure R) :
    orderedFinsetProduct s f ∈ Subgroup.normalClosure R := by
  unfold orderedFinsetProduct
  exact list_prod_mem_normalClosure (R := R) (by
    intro x hx
    rcases List.mem_map.1 hx with ⟨i, hi, rfl⟩
    exact h i (by
      exact (Finset.mem_sort (s := s) (r := fun a b : ι => a ≤ b)).1 hi))

theorem orderedFinsetProduct_relatorEquivalent
    (s : Finset ι) {f g : ι → G}
    (h : ∀ i ∈ s, RelatorEquivalent R (f i) (g i)) :
    RelatorEquivalent R (orderedFinsetProduct s f)
      (orderedFinsetProduct s g) := by
  unfold orderedFinsetProduct
  exact list_prod_map_relatorEquivalent (R := R) (s.sort (· ≤ ·))
    (f := f) (g := g) (by
      intro i hi
      exact h i (by
        exact (Finset.mem_sort (s := s) (r := fun a b : ι => a ≤ b)).1 hi))

theorem orderedFinsetProduct_relatorEquivalent_one
    (s : Finset ι) {f : ι → G}
    (h : ∀ i ∈ s, RelatorEquivalent R (f i) 1) :
    RelatorEquivalent R (orderedFinsetProduct s f) 1 := by
  unfold orderedFinsetProduct
  simpa using
    list_prod_map_relatorEquivalent_one (R := R) (s.sort (· ≤ ·))
      (f := f) (by
        intro i hi
        exact h i (by
          exact (Finset.mem_sort (s := s) (r := fun a b : ι => a ≤ b)).1 hi))

theorem orderedFinsetProduct_congr
    (s : Finset ι) {f g : ι → G}
    (h : ∀ i ∈ s, f i = g i) :
    orderedFinsetProduct s f = orderedFinsetProduct s g := by
  unfold orderedFinsetProduct
  congr 1
  apply List.map_congr_left
  intro i hi
  exact h i ((Finset.mem_sort (s := s) (r := fun a b : ι => a ≤ b)).1 hi)

end OrderedFinsetProduct


theorem conjugate_list_prod {G : Type*} [Group G] (x : G) :
    ∀ l : List G, x * l.prod * x⁻¹ = (l.map fun t => x * t * x⁻¹).prod
  | [] => by
      simp only [List.prod_nil, mul_one, mul_inv_cancel, List.map_nil]
  | t :: ts => by
      rw [List.prod_cons, List.map_cons, List.prod_cons]
      calc
        x * (t * ts.prod) * x⁻¹ = (x * t * x⁻¹) * (x * ts.prod * x⁻¹) := by
          group
        _ = x * t * x⁻¹ * (List.map (fun t => x * t * x⁻¹) ts).prod := by
          rw [conjugate_list_prod x ts]

theorem nested_conjugate_list_prod {G : Type*} [Group G]
    (x : G) {p n : ℕ} (f : Fin p → Fin n → G) :
    (List.ofFn (fun b : Fin p =>
      (List.ofFn (fun j : Fin n => x * f b j * x⁻¹)).prod)).prod =
        x * (List.ofFn (fun b : Fin p =>
          (List.ofFn (fun j : Fin n => f b j)).prod)).prod * x⁻¹ := by
  have hinner :
      (List.ofFn (fun b : Fin p =>
        (List.ofFn (fun j : Fin n => x * f b j * x⁻¹)).prod)) =
          List.ofFn (fun b : Fin p =>
            x * (List.ofFn (fun j : Fin n => f b j)).prod * x⁻¹) := by
    apply List.ofFn_inj.2
    funext b
    simpa using
      (conjugate_list_prod x (List.ofFn (fun j : Fin n => f b j))).symm
  rw [hinner]
  simpa using
    (conjugate_list_prod x
      (List.ofFn (fun b : Fin p =>
        (List.ofFn (fun j : Fin n => f b j)).prod))).symm

theorem subgroup_list_prod_val {G : Type*} [Group G]
    {H : Subgroup G} {n : ℕ} (f : Fin n → H) :
    (((List.ofFn f).prod : H) : G) =
      (List.ofFn (fun i : Fin n => ((f i : H) : G))).prod := by
  change H.subtype ((List.ofFn f).prod) =
    (List.ofFn (fun i : Fin n => ((f i : H) : G))).prod
  rw [map_list_prod, List.map_ofFn]
  apply congrArg List.prod
  apply List.ofFn_inj.2
  funext i
  rfl

theorem subgroup_nested_list_prod_val {G : Type*} [Group G]
    {H : Subgroup G} {p n : ℕ} (f : Fin p → Fin n → H) :
    (((List.ofFn (fun b : Fin p =>
      (List.ofFn (fun j : Fin n => f b j)).prod)).prod : H) : G) =
        (List.ofFn (fun b : Fin p =>
          (List.ofFn (fun j : Fin n => ((f b j : H) : G))).prod)).prod := by
  change H.subtype
      ((List.ofFn (fun b : Fin p =>
        (List.ofFn (fun j : Fin n => f b j)).prod)).prod) =
    (List.ofFn (fun b : Fin p =>
      (List.ofFn (fun j : Fin n => ((f b j : H) : G))).prod)).prod
  rw [map_list_prod, List.map_ofFn]
  apply congrArg List.prod
  apply List.ofFn_inj.2
  funext b
  exact subgroup_list_prod_val (fun j : Fin n => f b j)



theorem freeGroup_endomorph_mul_inv_mem_normalClosure_of_generator_mul_inv
    {Y : Type*} (R : Set (FreeGroup Y)) (F : FreeGroup Y →* FreeGroup Y)
    (hgen :
      ∀ y : Y,
        F (FreeGroup.of y) * (FreeGroup.of y)⁻¹ ∈ Subgroup.normalClosure R) :
    ∀ w : FreeGroup Y, F w * w⁻¹ ∈ Subgroup.normalClosure R := by
  classical
  let N : Subgroup (FreeGroup Y) := Subgroup.normalClosure R
  let q : FreeGroup Y →* FreeGroup Y ⧸ N := QuotientGroup.mk' N
  have hq : q.comp F = q := by
    apply FreeGroup.ext_hom
    intro y
    change q (F (FreeGroup.of y)) = q (FreeGroup.of y)
    exact
      (QuotientGroup.eq_iff_div_mem
        (N := N) (x := F (FreeGroup.of y)) (y := FreeGroup.of y)).2
        (by simpa [N, div_eq_mul_inv] using hgen y)
  intro w
  have hw :
      q (F w) = q w := by
    simpa using congrArg (fun ψ : FreeGroup Y →* FreeGroup Y ⧸ N => ψ w) hq
  exact
    (QuotientGroup.eq_iff_div_mem (N := N) (x := F w) (y := w)).1
      (by simpa [N, div_eq_mul_inv] using hw)


end NormalClosure

end ReidemeisterSchreier.Discrete.Presentations
