import FoxDifferential.Completed.ProCIntegerCoefficients.Core
import Mathlib.RingTheory.Ideal.Basic

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/FoxDifferential/Completed/ProCIntegerCoefficients/AugmentationIdeal/Basic.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Completed group algebra coefficients

This module records augmentation-ideal statements for pro-\(C\) integer completed coefficient rings, including closure, finite-stage membership, and kernel descriptions.
-/
namespace FoxDifferential

noncomputable section

universe u

section AugmentationIdeal

variable (C : ProCGroups.FiniteGroupClass.{u})
variable (H : Type u) [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

/-- The algebraic ideal generated by the standard completed augmentation generators `[h] - 1`.

The completed augmentation ideal itself is the kernel of the completed augmentation map, defined
in `FoxDifferential.Completed.ProCIntegerCoefficients.Augmentation`. -/
def zcCompletedGroupAlgebraStandardAugmentationIdeal :
    Ideal (ZCCompletedGroupAlgebra C H) :=
  Ideal.span (Set.range fun h : H => zcGroupLike C H h - 1)

/-- The standard completed augmentation-generator ideal, viewed as a submodule, is the submodule
span of the standard generators. -/
theorem zcCompletedGroupAlgebraStandardAugmentationIdeal_eq_span :
    ((zcCompletedGroupAlgebraStandardAugmentationIdeal C H :
      Ideal (ZCCompletedGroupAlgebra C H)) :
      Submodule (ZCCompletedGroupAlgebra C H) (ZCCompletedGroupAlgebra C H)) =
      Submodule.span (ZCCompletedGroupAlgebra C H)
        (Set.range fun h : H => zcGroupLike C H h - 1) :=
  rfl

/-- Each standard completed augmentation generator `[h] - 1` lies in the algebraic ideal
generated by such standard generators. -/
theorem zcGroupLike_sub_one_mem_standardAugmentationIdeal (h : H) :
    zcGroupLike C H h - 1 ∈ zcCompletedGroupAlgebraStandardAugmentationIdeal C H :=
  Ideal.subset_span (Set.mem_range_self h)

variable {G : Type u} [Group G]

/-- The completed Fox boundary lands in the algebraic standard-generator ideal. -/
theorem zcCompletedGroupAlgebraBoundary_mem_standardAugmentationIdeal
    (ψ : G →* H) (g : G) :
    zcCompletedGroupAlgebraBoundary C ψ g ∈
      zcCompletedGroupAlgebraStandardAugmentationIdeal C H := by
  simpa [zcCompletedGroupAlgebraBoundary] using
    zcGroupLike_sub_one_mem_standardAugmentationIdeal C H (ψ g)

/-- The completed Fox boundary, with codomain restricted to the algebraic standard
augmentation-generator ideal. -/
def zcCompletedGroupAlgebraBoundaryToStandardAugmentationIdeal
    (ψ : G →* H) (g : G) :
    zcCompletedGroupAlgebraStandardAugmentationIdeal C H :=
  ⟨zcCompletedGroupAlgebraBoundary C ψ g,
    zcCompletedGroupAlgebraBoundary_mem_standardAugmentationIdeal C H ψ g⟩

/-- The standard-augmentation-ideal-valued completed Fox boundary is a crossed differential. -/
theorem zcCompletedGroupAlgebraBoundaryToStandardAugmentationIdeal_isCrossedDifferential
    (ψ : G →* H) :
    IsCrossedDifferential
      (zcCompletedGroupAlgebraScalar C ψ)
      (zcCompletedGroupAlgebraBoundaryToStandardAugmentationIdeal C H ψ) := by
  intro g h
  apply Subtype.ext
  exact zcCompletedGroupAlgebraBoundary_mul C ψ g h

/-- The completed Fox tail with codomain restricted to the algebraic standard augmentation
ideal. -/
def zcToStdAugIdeal
    (ψ : G →* H) :
    ZCCompletedDifferentialModule C ψ →ₗ[ZCCompletedGroupAlgebra C H]
      zcCompletedGroupAlgebraStandardAugmentationIdeal C H :=
  zcCompletedDifferentialModuleLift
    (A := zcCompletedGroupAlgebraStandardAugmentationIdeal C H) C ψ
    (zcCompletedGroupAlgebraBoundaryToStandardAugmentationIdeal C H ψ)
    (zcCompletedGroupAlgebraBoundaryToStandardAugmentationIdeal_isCrossedDifferential C H ψ)

@[simp]
theorem zcToStdAugIdeal_val
    (ψ : G →* H) (x : ZCCompletedDifferentialModule C ψ) :
    ((zcToStdAugIdeal C H ψ x :
      ZCCompletedGroupAlgebra C H)) =
      zcToCompletedGroupAlgebra C ψ x := by
  let L := zcToStdAugIdeal C H ψ
  have hL :
      (zcCompletedGroupAlgebraStandardAugmentationIdeal C H).subtype.comp L =
        zcToCompletedGroupAlgebra C ψ := by
    apply zcCompletedDifferentialModuleHom_ext C ψ
    intro g
    simp only [zcToStdAugIdeal, LinearMap.coe_comp, Submodule.coe_subtype, Function.comp_apply,
  zcCompletedDifferentialModuleLift_universal, zcCompletedGroupAlgebraBoundaryToStandardAugmentationIdeal,
  zcToCompletedGroupAlgebra_universal, L]
  simpa [L] using congrArg (fun f => f x) hL

/-- The completed Fox tail lands in the algebraic standard augmentation-generator ideal. -/
theorem zcToCompletedGroupAlgebra_mem_standardAugmentationIdeal
    (ψ : G →* H) (x : ZCCompletedDifferentialModule C ψ) :
    zcToCompletedGroupAlgebra C ψ x ∈
      zcCompletedGroupAlgebraStandardAugmentationIdeal C H := by
  simpa [zcToStdAugIdeal_val] using
    (zcToStdAugIdeal C H ψ x).2

/-- The range of the completed Fox tail is contained in the algebraic standard augmentation
ideal. -/
theorem zcToCompletedGroupAlgebra_range_le_standardAugmentationIdeal
    (ψ : G →* H) :
    LinearMap.range (zcToCompletedGroupAlgebra C ψ) ≤
      (zcCompletedGroupAlgebraStandardAugmentationIdeal C H :
        Submodule (ZCCompletedGroupAlgebra C H) (ZCCompletedGroupAlgebra C H)) := by
  rintro x ⟨m, rfl⟩
  exact zcToCompletedGroupAlgebra_mem_standardAugmentationIdeal C H ψ m

/-- If `ψ` is surjective, the completed Fox tail has range exactly the algebraic standard
augmentation-generator ideal. -/
theorem zcToCompletedGroupAlgebra_range_eq_standardAugmentationIdeal_of_surjective
    (ψ : G →* H) (hψ : Function.Surjective ψ) :
    LinearMap.range (zcToCompletedGroupAlgebra C ψ) =
      (zcCompletedGroupAlgebraStandardAugmentationIdeal C H :
        Submodule (ZCCompletedGroupAlgebra C H) (ZCCompletedGroupAlgebra C H)) := by
  refine le_antisymm
    (zcToCompletedGroupAlgebra_range_le_standardAugmentationIdeal C H ψ) ?_
  rw [zcCompletedGroupAlgebraStandardAugmentationIdeal_eq_span]
  refine Submodule.span_le.2 ?_
  rintro _ ⟨h, rfl⟩
  rcases hψ h with ⟨g, rfl⟩
  exact ⟨zcUniversalDifferential C ψ g, by simp only [zcToCompletedGroupAlgebra_universal, zcCompletedGroupAlgebraBoundary]⟩

/-- If `ψ` is surjective, the standard-augmentation-ideal-valued completed Fox tail is
surjective. -/
theorem zcToStdAugIdeal_surjective_of_surjective
    (ψ : G →* H) (hψ : Function.Surjective ψ) :
    Function.Surjective
      (zcToStdAugIdeal C H ψ) := by
  intro y
  have hy :
      (y : ZCCompletedGroupAlgebra C H) ∈
        LinearMap.range (zcToCompletedGroupAlgebra C ψ) := by
    rw [zcToCompletedGroupAlgebra_range_eq_standardAugmentationIdeal_of_surjective
      C H ψ hψ]
    exact y.2
  rcases hy with ⟨x, hx⟩
  refine ⟨x, Subtype.ext ?_⟩
  simpa [zcToStdAugIdeal_val] using hx

end AugmentationIdeal

end

end FoxDifferential
