import Mathlib.GroupTheory.PGroup
import ProCGroups.FreeProC.Basic
import ProCGroups.Topologies.TopologicallyCharacteristicSubgroups

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/ProCGroups/Presentations/Profinite.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Profinite presentations

Presentation-level API for profinite groups, finite quotients, relators, and Schreier-Tietze restrictions.
-/

noncomputable section

namespace ProCGroups.Presentations

universe u

section ClosedNormalClosure

variable {F : Type u} [Group F] [TopologicalSpace F] [IsTopologicalGroup F]

/-- The closed normal subgroup generated by a set of profinite relators. -/
def Subgroup.closedNormalClosure (R : Set F) : Subgroup F :=
  (Subgroup.normalClosure R).topologicalClosure

/-- The closed normal subgroup generated by a set of profinite relators. -/
abbrev closedNormalClosure (R : Set F) : Subgroup F :=
  Subgroup.closedNormalClosure R

instance closedNormalClosure_normal (R : Set F) : (closedNormalClosure R).Normal := by
  dsimp [closedNormalClosure, Subgroup.closedNormalClosure]
  exact Subgroup.is_normal_topologicalClosure (Subgroup.normalClosure R)

theorem closedNormalClosure_isClosed (R : Set F) :
    IsClosed ((closedNormalClosure R : Subgroup F) : Set F) := by
  exact Subgroup.isClosed_topologicalClosure _

theorem subset_closedNormalClosure (R : Set F) :
    R ⊆ closedNormalClosure R := by
  intro x hx
  exact Subgroup.le_topologicalClosure _
    (Subgroup.subset_normalClosure hx)

theorem one_mem_closedNormalClosure (R : Set F) :
    (1 : F) ∈ closedNormalClosure R :=
  Subgroup.one_mem _

theorem singleton_one_subset_closedNormalClosure (R : Set F) :
    ({1} : Set F) ⊆ closedNormalClosure R := by
  intro x hx
  subst x
  exact one_mem_closedNormalClosure (F := F) R

theorem subset_closedNormalClosure_of_subset_singleton_one
    {R D : Set F} (hD : D ⊆ ({1} : Set F)) :
    D ⊆ closedNormalClosure R := by
  intro x hx
  exact singleton_one_subset_closedNormalClosure (F := F) R (hD hx)

theorem closedNormalClosure_le_closed_normal
    {R : Set F} {N : Subgroup F} [N.Normal]
    (hNclosed : IsClosed (N : Set F)) (hR : R ⊆ N) :
    closedNormalClosure R ≤ N := by
  exact Subgroup.topologicalClosure_minimal _
    (Subgroup.normalClosure_le_normal hR) hNclosed

theorem closedNormalClosure_mono {R S : Set F} (hRS : R ⊆ S) :
    closedNormalClosure R ≤ closedNormalClosure S := by
  refine closedNormalClosure_le_closed_normal
    (F := F) (N := closedNormalClosure S)
    (closedNormalClosure_isClosed (F := F) S) ?_
  exact fun x hx => subset_closedNormalClosure (F := F) S (hRS hx)

theorem closedNormalClosure_eq_of_mutual_le
    {R S : Set F}
    (hRS : R ⊆ closedNormalClosure S)
    (hSR : S ⊆ closedNormalClosure R) :
    closedNormalClosure R = closedNormalClosure S := by
  apply le_antisymm
  · exact closedNormalClosure_le_closed_normal
      (F := F) (N := closedNormalClosure S)
      (closedNormalClosure_isClosed (F := F) S) hRS
  · exact closedNormalClosure_le_closed_normal
      (F := F) (N := closedNormalClosure R)
      (closedNormalClosure_isClosed (F := F) R) hSR

theorem closedNormalClosure_union_eq_left
    {R D : Set F} (hD : D ⊆ closedNormalClosure R) :
    closedNormalClosure (R ∪ D) = closedNormalClosure R := by
  apply le_antisymm
  · refine closedNormalClosure_le_closed_normal
      (F := F) (N := closedNormalClosure R)
      (closedNormalClosure_isClosed (F := F) R) ?_
    intro x hx
    exact hx.elim
      (fun hxR => subset_closedNormalClosure (F := F) R hxR)
      (fun hxD => hD hxD)
  · exact closedNormalClosure_mono (F := F) (Set.subset_union_left)

end ClosedNormalClosure

/-- A quotient-by-kernel record `1 → K → F → G → 1`.

The source `F` is left explicit: in applications it is normally supplied by
`FreeProC.IsFreeProCGroup`, while Tietze moves only need to know the kernel and the
continuous epimorphism being transported. -/
def IsQuotientByKernel (C : ProCGroups.FiniteGroupClass.{u})
    {F G : Type u} [Group F] [Group G]
    [TopologicalSpace F] [TopologicalSpace G]
    [IsTopologicalGroup F] [IsTopologicalGroup G]
    (K : Subgroup F) : Prop :=
  ProCGroups.ProC.IsProCGroup C G ∧
    ∃ π : F →ₜ* G, Function.Surjective π ∧ π.toMonoidHom.ker = K

/-- A relator presentation whose source is a chosen free pro-`C` group. -/
def IsFreePresentationOf
    (ProC : ProCGroups.ProC.ProCGroupPredicate.{u})
    {X F G : Type u} [TopologicalSpace X]
    [Group F] [Group G]
    [TopologicalSpace F] [TopologicalSpace G]
    [IsTopologicalGroup F] [IsTopologicalGroup G]
    (ι : X → F) (R : Set F) : Prop :=
  ProCGroups.FreeProC.IsFreeProCGroup (ProC := ProC) ι ∧
    ProC (G := G) ∧
      ∃ π : F →ₜ* G, Function.Surjective π ∧ π.toMonoidHom.ker = closedNormalClosure R

/-- The concrete finite-class specialization of `IsFreePresentationOf`. -/
def IsFreePresentationOfClass (C : ProCGroups.FiniteGroupClass.{u})
    {X F G : Type u} [TopologicalSpace X]
    [Group F] [Group G]
    [TopologicalSpace F] [TopologicalSpace G]
    [IsTopologicalGroup F] [IsTopologicalGroup G]
    (ι : X → F) (R : Set F) : Prop :=
  IsFreePresentationOf
    (ProC := ProCGroups.ProC.finiteGroupClassProCPredicate C)
    (G := G) ι R

namespace IsFreePresentationOf

variable {ProC : ProCGroups.ProC.ProCGroupPredicate.{u}}
variable {X F G : Type u} [TopologicalSpace X]
variable [Group F] [Group G]
variable [TopologicalSpace F] [TopologicalSpace G]
variable [IsTopologicalGroup F] [IsTopologicalGroup G]
variable {ι : X → F} {R : Set F}

/-- The chosen quotient map recorded by a free pro-`C` presentation. -/
def π (h : IsFreePresentationOf (G := G) ProC ι R) : F →ₜ* G :=
  Classical.choose h.2.2

/-- The source of a free presentation is free pro-`C`. -/
theorem freeSource (h : IsFreePresentationOf (G := G) ProC ι R) :
    ProCGroups.FreeProC.IsFreeProCGroup (ProC := ProC) ι :=
  h.1

/-- The target of a free presentation is pro-`C`. -/
theorem targetProC (h : IsFreePresentationOf (G := G) ProC ι R) :
    ProC (G := G) :=
  h.2.1

/-- The chosen quotient map is surjective. -/
theorem π_surjective (h : IsFreePresentationOf (G := G) ProC ι R) :
    Function.Surjective h.π :=
  (Classical.choose_spec h.2.2).1

/-- The kernel of the chosen quotient map is the closed normal closure of the relators. -/
theorem kernel_eq_closedNormalClosure (h : IsFreePresentationOf (G := G) ProC ι R) :
    h.π.toMonoidHom.ker = closedNormalClosure R :=
  (Classical.choose_spec h.2.2).2

end IsFreePresentationOf

/-- Forget the chosen free source from a concrete free pro-`C` relator presentation. -/
theorem IsFreePresentationOfClass.isQuotientByKernel
    (C : ProCGroups.FiniteGroupClass.{u})
    {X F G : Type u} [TopologicalSpace X]
    [Group F] [Group G]
    [TopologicalSpace F] [TopologicalSpace G]
    [IsTopologicalGroup F] [IsTopologicalGroup G]
    {ι : X → F} {R : Set F} :
    IsFreePresentationOfClass (G := G) C ι R →
      IsQuotientByKernel C (F := F) (G := G) (closedNormalClosure R) := by
  intro h
  rcases h with ⟨_hfree, hG, π, hπsurj, hπker⟩
  exact ⟨hG, π, hπsurj, hπker⟩

/-- Transport a pro-`C'` presentation to a pro-`C` presentation along inclusion of
finite classes. -/
theorem isPresentationOf_of_class_subset
    (C' C : ProCGroups.FiniteGroupClass.{u})
    {F G : Type u} [Group F] [Group G]
    [TopologicalSpace F] [TopologicalSpace G]
    [IsTopologicalGroup F] [IsTopologicalGroup G]
    (K : Subgroup F) :
    (∀ {Q : Type u} [Group Q], C' Q → C Q) →
      IsQuotientByKernel C' (F := F) (G := G) K →
        IsQuotientByKernel C (F := F) (G := G) K := by
  intro hsub hpres
  rcases hpres with ⟨hG, π, hπsurj, hπker⟩
  exact ⟨hG.mono hsub, π, hπsurj, hπker⟩

/-- Continuous Tietze data between two presentation kernels.  It is the profinite
analogue of the mutual-map data used in the discrete ReidemeisterSchreier library, but stated directly
for closed kernels rather than syntactic relator sets. -/
structure KernelTietzeData
    {F E : Type u} [Group F] [Group E]
    [TopologicalSpace F] [TopologicalSpace E]
    (K : Subgroup F) (L : Subgroup E) where
  toHom : F →ₜ* E
  invHom : E →ₜ* F
  mapsKernel : K ≤ Subgroup.comap toHom.toMonoidHom L
  mapsTargetKernel : L ≤ Subgroup.comap invHom.toMonoidHom K
  inv_toHom : ∀ x : F, invHom (toHom x) * x⁻¹ ∈ K
  to_invHom : ∀ y : E, toHom (invHom y) * y⁻¹ ∈ L

namespace KernelTietzeData

variable {F E H : Type u}
variable [Group F] [Group E] [Group H]
variable [TopologicalSpace F] [TopologicalSpace E] [TopologicalSpace H]
variable {K : Subgroup F} {L : Subgroup E} {M : Subgroup H}

/-- The identity Tietze datum. -/
def refl (K : Subgroup F) : KernelTietzeData K K where
  toHom := ContinuousMonoidHom.id F
  invHom := ContinuousMonoidHom.id F
  mapsKernel := by intro x hx; exact hx
  mapsTargetKernel := by intro x hx; exact hx
  inv_toHom := by intro x; simp only [ContinuousMonoidHom.id_toFun, mul_inv_cancel, one_mem]
  to_invHom := by intro x; simp only [ContinuousMonoidHom.id_toFun, mul_inv_cancel, one_mem]

/-- Reverse a Tietze datum. -/
def symm (D : KernelTietzeData K L) : KernelTietzeData L K where
  toHom := D.invHom
  invHom := D.toHom
  mapsKernel := D.mapsTargetKernel
  mapsTargetKernel := D.mapsKernel
  inv_toHom := D.to_invHom
  to_invHom := D.inv_toHom

/-- Compose Tietze data. -/
def trans (D₁ : KernelTietzeData K L) (D₂ : KernelTietzeData L M) :
    KernelTietzeData K M where
  toHom := D₂.toHom.comp D₁.toHom
  invHom := D₁.invHom.comp D₂.invHom
  mapsKernel := by
    intro x hx
    exact D₂.mapsKernel (D₁.mapsKernel hx)
  mapsTargetKernel := by
    intro x hx
    exact D₁.mapsTargetKernel (D₂.mapsTargetKernel hx)
  inv_toHom := by
    intro x
    let y : E := D₁.toHom x
    have h₂ : D₂.invHom (D₂.toHom y) * y⁻¹ ∈ L :=
      D₂.inv_toHom y
    have h₂map : D₁.invHom (D₂.invHom (D₂.toHom y) * y⁻¹) ∈ K :=
      D₁.mapsTargetKernel h₂
    have h₂map' :
        D₁.invHom (D₂.invHom (D₂.toHom y)) *
            (D₁.invHom y)⁻¹ ∈ K := by
      simpa using h₂map
    have h₁ : D₁.invHom y * x⁻¹ ∈ K :=
      D₁.inv_toHom x
    have hprod := K.mul_mem h₂map' h₁
    have hmul :
        (D₁.invHom (D₂.invHom (D₂.toHom y)) *
              (D₁.invHom y)⁻¹) *
            (D₁.invHom y * x⁻¹) =
          D₁.invHom (D₂.invHom (D₂.toHom y)) * x⁻¹ := by
      group
    simpa [MonoidHom.comp_apply, y, hmul] using hprod
  to_invHom := by
    intro z
    let y : E := D₂.invHom z
    have h₁ : D₁.toHom (D₁.invHom y) * y⁻¹ ∈ L :=
      D₁.to_invHom y
    have h₁map : D₂.toHom (D₁.toHom (D₁.invHom y) * y⁻¹) ∈ M :=
      D₂.mapsKernel h₁
    have h₁map' :
        D₂.toHom (D₁.toHom (D₁.invHom y)) *
            (D₂.toHom y)⁻¹ ∈ M := by
      simpa using h₁map
    have h₂ : D₂.toHom y * z⁻¹ ∈ M :=
      D₂.to_invHom z
    have hprod := M.mul_mem h₁map' h₂
    have hmul :
        (D₂.toHom (D₁.toHom (D₁.invHom y)) *
              (D₂.toHom y)⁻¹) *
            (D₂.toHom y * z⁻¹) =
          D₂.toHom (D₁.toHom (D₁.invHom y)) * z⁻¹ := by
      group
    simpa [MonoidHom.comp_apply, y, hmul] using hprod

/-- Tietze data induce an algebraic equivalence of quotient groups. -/
def quotientMulEquiv (D : KernelTietzeData K L) [K.Normal] [L.Normal] :
    F ⧸ K ≃* E ⧸ L := by
  let F₁ : F ⧸ K →* E ⧸ L :=
    QuotientGroup.lift K ((QuotientGroup.mk' L).comp D.toHom.toMonoidHom) (by
      intro x hx
      rw [MonoidHom.mem_ker]
      exact (QuotientGroup.eq_one_iff (N := L) (D.toHom x)).2 (D.mapsKernel hx))
  let F₂ : E ⧸ L →* F ⧸ K :=
    QuotientGroup.lift L ((QuotientGroup.mk' K).comp D.invHom.toMonoidHom) (by
      intro y hy
      rw [MonoidHom.mem_ker]
      exact (QuotientGroup.eq_one_iff (N := K) (D.invHom y)).2
        (D.mapsTargetKernel hy))
  refine
    { toFun := F₁
      invFun := F₂
      left_inv := ?_
      right_inv := ?_
      map_mul' := fun a b => F₁.map_mul a b }
  · intro x
    rcases QuotientGroup.mk'_surjective K x with ⟨x, rfl⟩
    simp only [QuotientGroup.mk'_apply]
    exact (QuotientGroup.eq_iff_div_mem (N := K)
        (x := D.invHom (D.toHom x)) (y := x)).2
      (by simpa [div_eq_mul_inv] using D.inv_toHom x)
  · intro y
    rcases QuotientGroup.mk'_surjective L y with ⟨y, rfl⟩
    simp only [QuotientGroup.mk'_apply]
    exact (QuotientGroup.eq_iff_div_mem (N := L)
        (x := D.toHom (D.invHom y)) (y := y)).2
      (by simpa [div_eq_mul_inv] using D.to_invHom y)

/-- A continuous multiplicative equivalence gives Tietze data for matching kernels. -/
def ofContinuousMulEquiv
    {K : Subgroup F} {L : Subgroup E} (e : F ≃ₜ* E)
    (hK : ∀ x : F, x ∈ K ↔ e x ∈ L)
    (hL : ∀ y : E, y ∈ L ↔ e.symm y ∈ K) :
    KernelTietzeData K L where
  toHom := e.toContinuousMonoidHom
  invHom := e.symm.toContinuousMonoidHom
  mapsKernel := by
    intro x hx
    exact (hK x).1 hx
  mapsTargetKernel := by
    intro y hy
    exact (hL y).1 hy
  inv_toHom := by
    intro x
    simp only [ContinuousMulEquiv.toContinuousMonoidHom_apply, ContinuousMulEquiv.symm_apply_apply,
  mul_inv_cancel, one_mem]
  to_invHom := by
    intro y
    simp only [ContinuousMulEquiv.toContinuousMonoidHom_apply, ContinuousMulEquiv.apply_symm_apply,
  mul_inv_cancel, one_mem]

/-- A continuous multiplicative equivalence gives Tietze data when it maps one kernel
onto the other. -/
def ofContinuousMulEquivMapEq
    {K : Subgroup F} {L : Subgroup E} (e : F ≃ₜ* E)
    (hmap : K.map e.toContinuousMonoidHom.toMonoidHom = L) :
    KernelTietzeData K L where
  toHom := e.toContinuousMonoidHom
  invHom := e.symm.toContinuousMonoidHom
  mapsKernel := by
    intro x hx
    change e x ∈ L
    rw [← hmap]
    exact ⟨x, hx, rfl⟩
  mapsTargetKernel := by
    intro y hy
    have hyMap : y ∈ K.map e.toContinuousMonoidHom.toMonoidHom := by
      rw [hmap]
      exact hy
    rcases hyMap with ⟨x, hx, hxy⟩
    have hsymm : e.symm y = x := by
      simp only [← hxy, ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_coe,
  ContinuousMulEquiv.toContinuousMonoidHom_apply, ContinuousMulEquiv.symm_apply_apply]
    simpa [hsymm] using hx
  inv_toHom := by
    intro x
    simp only [ContinuousMulEquiv.toContinuousMonoidHom_apply, ContinuousMulEquiv.symm_apply_apply,
  mul_inv_cancel, one_mem]
  to_invHom := by
    intro y
    simp only [ContinuousMulEquiv.toContinuousMonoidHom_apply, ContinuousMulEquiv.apply_symm_apply,
  mul_inv_cancel, one_mem]

end KernelTietzeData

/-- Transport a presentation along profinite Tietze data between its source kernels. -/
theorem isPresentationOf_of_kernelTietzeData
    (C : ProCGroups.FiniteGroupClass.{u})
    {F E G : Type u} [Group F] [Group E] [Group G]
    [TopologicalSpace F] [TopologicalSpace E] [TopologicalSpace G]
    [IsTopologicalGroup F] [IsTopologicalGroup E] [IsTopologicalGroup G]
    {K : Subgroup F} {L : Subgroup E}
    (D : KernelTietzeData K L) :
    IsQuotientByKernel C (F := F) (G := G) K →
      IsQuotientByKernel C (F := E) (G := G) L := by
  intro hpres
  rcases hpres with ⟨hG, π, hπsurj, hπker⟩
  subst K
  let ρ : E →ₜ* G := π.comp D.invHom
  have hρsurj : Function.Surjective ρ := by
    intro g
    rcases hπsurj g with ⟨x, rfl⟩
    refine ⟨D.toHom x, ?_⟩
    have hx : D.invHom (D.toHom x) * x⁻¹ ∈ π.toMonoidHom.ker := by
      exact D.inv_toHom x
    have hmul : π (D.invHom (D.toHom x) * x⁻¹) = 1 := by
      simpa [MonoidHom.mem_ker] using hx
    have hmain : π (D.invHom (D.toHom x)) = π x := by
      have h := congrArg (fun z : G => z * π x) hmul
      simpa [map_mul, map_inv, mul_assoc] using h
    exact hmain
  have hρker : ρ.toMonoidHom.ker = L := by
    ext y
    constructor
    · intro hy
      have hyK : D.invHom y ∈ π.toMonoidHom.ker := by
        simpa [ρ, MonoidHom.mem_ker] using hy
      have hmap : D.toHom (D.invHom y) ∈ L := D.mapsKernel hyK
      have hrel : D.toHom (D.invHom y) * y⁻¹ ∈ L := D.to_invHom y
      have hinv : (D.toHom (D.invHom y) * y⁻¹)⁻¹ ∈ L := L.inv_mem hrel
      have hprod := L.mul_mem hinv hmap
      simpa using hprod
    · intro hy
      have hyKer : D.invHom y ∈ π.toMonoidHom.ker := D.mapsTargetKernel hy
      rw [MonoidHom.mem_ker]
      change π (D.invHom y) = 1
      simpa [MonoidHom.mem_ker] using hyKer
  exact ⟨hG, ρ, hρsurj, hρker⟩

/-- Transport a presentation along a continuous multiplicative equivalence of sources. -/
theorem isPresentationOf_of_source_equiv
    (C : ProCGroups.FiniteGroupClass.{u})
    {F E G : Type u} [Group F] [Group E] [Group G]
    [TopologicalSpace F] [TopologicalSpace E] [TopologicalSpace G]
    [IsTopologicalGroup F] [IsTopologicalGroup E] [IsTopologicalGroup G]
    {K : Subgroup F} {L : Subgroup E}
    (e : F ≃ₜ* E)
    (hK : ∀ x : F, x ∈ K ↔ e x ∈ L)
    (hL : ∀ y : E, y ∈ L ↔ e.symm y ∈ K) :
    IsQuotientByKernel C (F := F) (G := G) K →
      IsQuotientByKernel C (F := E) (G := G) L :=
  isPresentationOf_of_kernelTietzeData C
    (KernelTietzeData.ofContinuousMulEquiv (K := K) (L := L) e hK hL)

/-- Transport a presentation along a continuous multiplicative equivalence of targets,
recording the pro-`C` witness for the new target explicitly. -/
theorem isPresentationOf_of_target_equiv
    (C : ProCGroups.FiniteGroupClass.{u})
    {F G H : Type u} [Group F] [Group G] [Group H]
    [TopologicalSpace F] [TopologicalSpace G] [TopologicalSpace H]
    [IsTopologicalGroup F] [IsTopologicalGroup G] [IsTopologicalGroup H]
    {K : Subgroup F}
    (e : G ≃ₜ* H)
    (hH : ProCGroups.ProC.IsProCGroup C H) :
    IsQuotientByKernel C (F := F) (G := G) K →
      IsQuotientByKernel C (F := F) (G := H) K := by
  intro hpres
  rcases hpres with ⟨_hG, π, hπsurj, hπker⟩
  subst K
  let ρ : F →ₜ* H := e.toContinuousMonoidHom.comp π
  have hρsurj : Function.Surjective ρ := by
    intro h
    rcases hπsurj (e.symm h) with ⟨x, hx⟩
    refine ⟨x, ?_⟩
    change e (π x) = h
    rw [hx]
    simp only [ContinuousMulEquiv.apply_symm_apply]
  have hρker : ρ.toMonoidHom.ker = π.toMonoidHom.ker := by
    ext x
    constructor
    · intro hx
      have hxKer : x ∈ π.toMonoidHom.ker := by
        rw [MonoidHom.mem_ker] at hx ⊢
        have hsame : e (π x) = e (1 : G) := by
          simpa [ρ] using hx
        exact e.injective hsame
      exact hxKer
    · intro hx
      rw [MonoidHom.mem_ker] at hx ⊢
      change e (π x) = 1
      simpa using congrArg e hx
  exact ⟨hH, ρ, hρsurj, hρker⟩

end ProCGroups.Presentations
