import Mathlib.GroupTheory.FreeGroup.Basic
import ProCGroups.Generation.QuotientGeneratorConvergingPairs

/-
PUBLIC_PAGE_SNAPSHOT
generated_at: 2026-05-27T09:47:29+09:00
lean_source: lean4/ProCGroups/FiniteGeneration/Basic.lean
translation_root: data/translation
purpose: identifies the local data snapshot used to build pages/
placement: after imports, never before imports
-/
/-!
# Finite generation and characteristic chains

Records finite generation criteria for profinite groups, finite-index/open-subgroup counting, characteristic cores, and index bounds.
-/

open Set
open scoped Topology Pointwise

namespace ProCGroups.FiniteGeneration

universe u v w

open ProCGroups.Generation

section Basic

variable {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- Finitely generated as a topological group. -/
def TopologicallyFinitelyGenerated
    (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G] : Prop :=
  ∃ s : Finset G, TopologicallyGenerates (G := G) (↑s : Set G)

/-- A subgroup is characteristic if every continuous automorphism preserves it. -/
def IsTopologicallyCharacteristic
    (G : Type u) [Group G] [TopologicalSpace G] (H : Subgroup G) : Prop :=
  ∀ φ : G ≃ₜ* G, ∀ g : G, φ g ∈ H ↔ g ∈ H

section Characteristic

omit [IsTopologicalGroup G]

/-- Membership in a characteristic subgroup is invariant under a continuous automorphism. -/
theorem IsTopologicallyCharacteristic.apply_mem_iff {H : Subgroup G}
    (hH : IsTopologicallyCharacteristic (G := G) H) (φ : G ≃ₜ* G) {g : G} :
    φ g ∈ H ↔ g ∈ H :=
  hH φ g

/-- Intersections of characteristic subgroups are characteristic. -/
theorem IsTopologicallyCharacteristic.inf {H K : Subgroup G}
    (hH : IsTopologicallyCharacteristic (G := G) H) (hK : IsTopologicallyCharacteristic (G := G) K) :
    IsTopologicallyCharacteristic (G := G) (H ⊓ K) := by
  intro φ g
  simp only [Subgroup.mem_inf, hH φ g, hK φ g]

/-- Arbitrary infima of characteristic subgroups are characteristic. -/
theorem IsTopologicallyCharacteristic.sInf {S : Set (Subgroup G)}
    (hS : ∀ H ∈ S, IsTopologicallyCharacteristic (G := G) H) :
    IsTopologicallyCharacteristic (G := G) (sInf S) := by
  intro φ g
  simp only [Subgroup.mem_sInf]
  constructor
  · intro hg H hH
    exact (hS H hH φ g).1 (hg H hH)
  · intro hg H hH
    exact (hS H hH φ g).2 (hg H hH)

/-- Indexed infima of characteristic subgroups are characteristic. -/
theorem IsTopologicallyCharacteristic.iInf {ι : Sort*} {S : ι → Subgroup G}
    (hS : ∀ i, IsTopologicallyCharacteristic (G := G) (S i)) :
    IsTopologicallyCharacteristic (G := G) (iInf S) := by
  intro φ g
  simp only [Subgroup.mem_iInf]
  constructor
  · intro hg i
    exact (hS i φ g).1 (hg i)
  · intro hg i
    exact (hS i φ g).2 (hg i)

/-- The whole group is characteristic. -/
@[simp] theorem IsTopologicallyCharacteristic.top :
    IsTopologicallyCharacteristic (G := G) (⊤ : Subgroup G) := by
  intro φ g
  simp only [Subgroup.mem_top]

end Characteristic

/-- `G` can be topologically generated by at most `n` elements. -/
def TopologicallyGeneratedByAtMost
    (n : ℕ) (G : Type u) [Group G] [TopologicalSpace G] [IsTopologicalGroup G] :
    Prop :=
  ∃ s : Finset G, s.card ≤ n ∧ TopologicallyGenerates (G := G) (↑s : Set G)

/-- Increasing the allowed number of generators preserves bounded topological generation. -/
theorem TopologicallyGeneratedByAtMost.mono {m n : ℕ}
    (hmn : m ≤ n)
    (hG : TopologicallyGeneratedByAtMost (G := G) m) :
    TopologicallyGeneratedByAtMost (G := G) n := by
  rcases hG with ⟨s, hs, hgen⟩
  exact ⟨s, hs.trans hmn, hgen⟩

/-- A group is topologically finitely generated iff it is generated by at most `n` elements for
some natural number `n`. -/
theorem topologicallyFinitelyGenerated_iff_exists_topologicallyGeneratedByAtMost :
    TopologicallyFinitelyGenerated G ↔
      ∃ n, TopologicallyGeneratedByAtMost (G := G) n := by
  constructor
  · rintro ⟨s, hs⟩
    exact ⟨s.card, s, le_rfl, hs⟩
  · rintro ⟨_n, s, _hs, hgen⟩
    exact ⟨s, hgen⟩

omit [IsTopologicalGroup G] in
/-- A finite set of elements converges to `1` in the profinite generating-family sense. -/
theorem finiteSet_convergesToOne (s : Finset G) :
    ConvergesToOne (G := G) (↑s : Set G) :=
  ConvergesToOne.of_finite s.finite_toSet

/-- If `G` is topologically generated by at most `n` elements, its topological rank is at most
`n`. -/
theorem topologicalRank_le_of_topologicallyGeneratedByAtMost {n : ℕ}
    (h : TopologicallyGeneratedByAtMost (G := G) n) :
    topologicalRank G ≤ n := by
  rcases h with ⟨s, hs, hgen⟩
  have hconv : ConvergesToOne (G := G) (↑s : Set G) :=
    finiteSet_convergesToOne (G := G) s
  calc
    topologicalRank G ≤ Cardinal.mk (↑s : Set G) :=
      topologicalRank_le_mk_of_generatesAndConvergesToOne (G := G) ⟨hgen, hconv⟩
    _ = (s.card : Cardinal) := by
      exact Cardinal.mk_coe_finset (s := s)
    _ ≤ n := by
      exact_mod_cast hs

/-- The image of a topological generating family under a continuous surjective homomorphism
topologically generates the codomain. -/
theorem topologicallyGenerates_range_comp_of_surjective
    {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (φ : G →ₜ* H) (hφ : Function.Surjective φ)
    {ι : Sort w} (g : ι → G)
    (hg : TopologicallyGenerates (G := G) (Set.range g)) :
    TopologicallyGenerates (G := H) (Set.range (φ ∘ g)) := by
  simpa [Set.range_comp, Function.comp] using
    topologicallyGenerates_image_of_continuousMonoidHom_surjective
      (G := G) (H := H) φ hφ hg

/-- Bounded topological generation descends along continuous surjective homomorphisms. -/
theorem TopologicallyGeneratedByAtMost.of_surjective
    {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (φ : G →ₜ* H) (hφ : Function.Surjective φ) {n : ℕ}
    (hG : TopologicallyGeneratedByAtMost (G := G) n) :
    TopologicallyGeneratedByAtMost (G := H) n := by
  classical
  rcases hG with ⟨s, hs, hgen⟩
  refine ⟨s.image φ, (Finset.card_image_le).trans hs, ?_⟩
  simpa [Finset.coe_image] using
    topologicallyGenerates_image_of_continuousMonoidHom_surjective
      (G := G) (H := H) φ hφ hgen

/-- Topological finite generation descends along continuous surjective homomorphisms. -/
theorem topologicallyFinitelyGenerated_of_continuousSurjective
    {H : Type v} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (φ : G →ₜ* H) (hφ : Function.Surjective φ)
    (hG : TopologicallyFinitelyGenerated G) :
    TopologicallyFinitelyGenerated H := by
  rw [topologicallyFinitelyGenerated_iff_exists_topologicallyGeneratedByAtMost] at hG ⊢
  rcases hG with ⟨n, hn⟩
  exact ⟨n, TopologicallyGeneratedByAtMost.of_surjective (G := G) (H := H) φ hφ hn⟩

/-- In the discrete case, topological generation is abstract subgroup generation. -/
theorem topologicallyGenerates_iff_subgroupClosure_eq_top_of_discrete
    [DiscreteTopology G] {X : Set G} :
    TopologicallyGenerates (G := G) X ↔ Subgroup.closure X = ⊤ := by
  have htc : (Subgroup.closure X).topologicalClosure = Subgroup.closure X := by
    apply SetLike.ext'
    rw [Subgroup.topologicalClosure_coe]
    exact closure_discrete ((Subgroup.closure X : Subgroup G) : Set G)
  rw [TopologicallyGenerates, htc]

/-- A map from a free group onto a discrete topologically generated group is surjective.

This is the finite-stage bridge used by Magnus arguments: after passing to a discrete quotient,
topological generation of the images of the chosen generators is exactly abstract generation. -/
theorem freeGroup_lift_surjective_of_topologicallyGenerates_discrete
    {X : Type v} [DiscreteTopology G] (g : X → G)
    (hg : TopologicallyGenerates (G := G) (Set.range g)) :
    Function.Surjective (FreeGroup.lift g) := by
  rw [topologicallyGenerates_iff_subgroupClosure_eq_top_of_discrete] at hg
  have hclosure_le_range :
      Subgroup.closure (Set.range g) ≤ (FreeGroup.lift g).range := by
    refine (Subgroup.closure_le (K := (FreeGroup.lift g).range)).2 ?_
    rintro y ⟨x, rfl⟩
    exact ⟨FreeGroup.of x, by simp only [FreeGroup.lift_apply_of]⟩
  intro y
  have hy : y ∈ Subgroup.closure (Set.range g) := by
    rw [hg]
    trivial
  exact hclosure_le_range hy

/-- A finite discrete group is topologically finitely generated. -/
theorem topologicallyFinitelyGenerated_of_finite [Finite G] [DiscreteTopology G] :
    TopologicallyFinitelyGenerated G := by
  classical
  letI : Fintype G := Fintype.ofFinite G
  refine ⟨Finset.univ, ?_⟩
  rw [topologicallyGenerates_iff_subgroupClosure_eq_top_of_discrete]
  simp only [Finset.coe_univ, Subgroup.closure_univ]

/-- If the topological rank of a profinite group is the natural number `n`, then the group is
topologically generated by at most `n` elements. -/
theorem topologicallyGeneratedByAtMost_of_topologicalRank_eq_nat
    (hG : ProCGroups.IsProfiniteGroup G) {n : ℕ}
    (hd : topologicalRank G = n) :
    TopologicallyGeneratedByAtMost (G := G) n := by
  classical
  let C : Set Cardinal := {κ : Cardinal |
    ∃ X : Set G,
      GeneratesAndConvergesToOne (G := G) X ∧ Cardinal.mk X = κ}
  have hCne : C.Nonempty := by
    rcases exists_generatorsConvergingToOne (G := G) hG with ⟨X, hX⟩
    exact ⟨Cardinal.mk X, X, hX, rfl⟩
  have hdmem : topologicalRank G ∈ C := by
    simpa [topologicalRank, C] using (csInf_mem hCne)
  rcases hdmem with ⟨X, hX, hXcard⟩
  have hXlt : Cardinal.mk X < Cardinal.aleph0 := by
    calc
      Cardinal.mk X = topologicalRank G := hXcard
      _ = n := hd
      _ < Cardinal.aleph0 := Cardinal.natCast_lt_aleph0 (n := n)
  letI : Finite X := (Cardinal.lt_aleph0_iff_finite (α := X)).mp hXlt
  have hXfin : X.Finite := Set.toFinite X
  let s : Finset G := hXfin.toFinset
  have hs_card : s.card = n := by
    have hs_mk : (s.card : Cardinal) = Cardinal.mk X := by
      simpa [s] using (Cardinal.mk_coe_finset (s := hXfin.toFinset)).symm
    exact_mod_cast (hs_mk.trans (hXcard.trans hd))
  refine ⟨s, hs_card.le, ?_⟩
  simpa [s] using hX.1

/-- A finite upper bound on the topological rank gives an explicit generating tuple of that
length. -/
theorem exists_generatingTuple_of_topologicalRank_le_of_finite
    (hG : TopologicallyFinitelyGenerated G) {n : ℕ} (hd : topologicalRank G ≤ n) :
    ∃ g : Fin n → G, TopologicallyGenerates (G := G) (Set.range g) := by
  classical
  have hdfin : topologicalRank G < Cardinal.aleph0 := by
    rcases hG with ⟨s, hs⟩
    have hconv : ConvergesToOne (G := G) (↑s : Set G) :=
      finiteSet_convergesToOne (G := G) s
    have hdle : topologicalRank G ≤ Cardinal.mk (↑s : Set G) :=
      topologicalRank_le_mk_of_generatesAndConvergesToOne (G := G) ⟨hs, hconv⟩
    exact hdle.trans_lt <| by
      have hsMk : Cardinal.mk (↑s : Set G) = (s.card : Cardinal) :=
        Cardinal.mk_coe_finset (s := s)
      rw [hsMk]
      exact Cardinal.natCast_lt_aleph0 (n := s.card)
  let m := Cardinal.toNat (topologicalRank G)
  have hm : topologicalRank G = m := by
    symm
    exact Cardinal.cast_toNat_of_lt_aleph0 hdfin
  have hExists : ∃ X : Set G, GeneratesAndConvergesToOne (G := G) X := by
    rcases hG with ⟨s, hs⟩
    exact ⟨(↑s : Set G), ⟨hs, finiteSet_convergesToOne (G := G) s⟩⟩
  rcases exists_generatesAndConvergesToOne_card_eq_topologicalRank (G := G) hExists with
    ⟨X, hX, hXcard⟩
  have hXfin : X.Finite := by
    have hXlt : Cardinal.mk X < Cardinal.aleph0 := by
      calc
        Cardinal.mk X = topologicalRank G := hXcard
        _ = m := hm
        _ < Cardinal.aleph0 := Cardinal.natCast_lt_aleph0 (n := m)
    letI : Finite X := (Cardinal.lt_aleph0_iff_finite (α := X)).mp <| by
       simpa using hXlt
    exact Set.toFinite X
  let s : Finset G := hXfin.toFinset
  have hs_gen : TopologicallyGenerates (G := G) (↑s : Set G) := by
    simpa [s] using hX.1
  have hs_card : s.card = m := by
    have hs_mk : (s.card : Cardinal) = Cardinal.mk X := by
      simpa [s] using (Cardinal.mk_coe_finset (s := hXfin.toFinset)).symm
    exact_mod_cast (hs_mk.trans (hXcard.trans hm))
  have hmle : m ≤ n := by
    simpa [m] using
      (Cardinal.toNat_le_toNat hd (Cardinal.natCast_lt_aleph0 (n := n)))
  have hs_le : s.card ≤ n := by
    simpa [hs_card] using hmle
  let e : Fin s.card ≃ s := by
     simpa using (Fintype.equivFin s).symm
  let g0 : Fin s.card → G := fun i => (e i : G)
  have hs_subset_range : (↑s : Set G) ⊆ Set.range g0 := by
    intro x hx
    refine ⟨e.symm ⟨x, hx⟩, ?_⟩
    simp only [Equiv.apply_symm_apply, g0]
  have hg0 : TopologicallyGenerates (G := G) (Set.range g0) :=
    topologicallyGenerates_mono hs_gen hs_subset_range
  let g : Fin n → G := fun i =>
    if hi : i.1 < s.card then g0 ⟨i.1, hi⟩ else 1
  have hg0_subset : Set.range g0 ⊆ Set.range g := by
    intro x hx
    rcases hx with ⟨i, rfl⟩
    refine ⟨Fin.castLE hs_le i, ?_⟩
    have hi : (Fin.castLE hs_le i).1 < s.card := i.2
    simp only [Fin.val_castLE, Fin.is_lt, ↓reduceDIte, Fin.eta, g]
  exact ⟨g, topologicallyGenerates_mono hg0 hg0_subset⟩

end Basic


/-- If every finite stage of a surjective inverse system has topological rank at most `n`, then so
does the inverse limit. -/
theorem topologicalRank_inverseLimit_le_of_componentBound
    {I : Type v} [Preorder I]
    (S : ProCGroups.InverseSystems.InverseSystem (I := I))
    [Nonempty I] [∀ i, Group (S.X i)] [ProCGroups.InverseSystems.IsGroupSystem S]
    [∀ i, IsTopologicalGroup (S.X i)] [∀ i, Finite (S.X i)]
    [∀ i, CompactSpace (S.X i)] [∀ i, T2Space (S.X i)]
    (hdir : Directed (· ≤ ·) (id : I → I))
    (hsurj : ∀ {i j : I} (hij : i ≤ j), Function.Surjective (S.map hij))
    {n : ℕ} (hbound : ∀ i, topologicalRank (S.X i) ≤ n) :
    topologicalRank S.inverseLimit ≤ n := by
  classical
  letI : ∀ i, DiscreteTopology (S.X i) := fun _ => by infer_instance
  let T : ProCGroups.InverseSystems.InverseSystem (I := I) := {
    X := fun i => { g : Fin n → S.X i // TopologicallyGenerates (G := S.X i) (Set.range g) }
    topologicalSpace := fun _ => inferInstance
    map := fun {i j} hij g =>
      ⟨fun a => S.map hij (g.1 a), by
        let φij : ContinuousMonoidHom (S.X j) (S.X i) :=
          { toMonoidHom :=
              { toFun := S.map hij
                map_one' := ProCGroups.InverseSystems.IsGroupSystem.map_one (S := S) hij
                map_mul' := ProCGroups.InverseSystems.IsGroupSystem.map_mul (S := S) hij }
            continuous_toFun := S.continuous_map hij }
        simpa [Function.comp] using
          topologicallyGenerates_range_comp_of_surjective
            (G := S.X j) (H := S.X i) φij (hsurj hij) g.1 g.2⟩
    continuous_map := fun {_i _j} _hij => by
      exact continuous_of_discreteTopology
    map_id := fun i => by
      ext g a
      simp only [InverseSystems.InverseSystem.map_id_apply, id_eq]
    map_comp := fun hij hjk => by
      ext g a
      simp only [Function.comp_apply, InverseSystems.InverseSystem.map_comp_apply]}
  have hTnonempty : ∀ i, Nonempty (T.X i) := by
    intro i
    have hfg : TopologicallyFinitelyGenerated (S.X i) :=
      topologicallyFinitelyGenerated_of_finite (G := S.X i)
    rcases exists_generatingTuple_of_topologicalRank_le_of_finite
        (G := S.X i) hfg (hbound i) with ⟨g, hg⟩
    exact ⟨⟨g, hg⟩⟩
  letI : ∀ i, Nonempty (T.X i) := hTnonempty
  letI : ∀ i, Finite (T.X i) := fun _ => inferInstance
  rcases ProCGroups.InverseSystems.InverseSystem.nonempty_inverseLimit_of_finite
      (S := T) hdir with ⟨x⟩
  let g : Fin n → S.inverseLimit := fun a =>
    ⟨fun i => (x.1 i).1 a, by
      intro i j hij
      have hcompat := congrArg Subtype.val (x.2 i j hij)
      exact congrArg (fun f => f a) hcompat⟩
  have hgproj : ∀ i, TopologicallyGenerates (G := S.X i) (S.projection i '' Set.range g) := by
    intro i
    rw [← Set.range_comp (S.projection i) g]
    simpa [g, Function.comp] using (x.1 i).2
  have hggen : TopologicallyGenerates (G := S.inverseLimit) (Set.range g) := by
    exact
      (topologicallyGenerates_iff_forall_projection_inverseLimit
        (S := S) hdir hsurj (X := Set.range g)).2 hgproj
  let s : Finset S.inverseLimit := Finset.univ.image g
  have hs_card : s.card ≤ n := by
    simpa [s] using (Finset.card_image_le (f := g) (s := (Finset.univ : Finset (Fin n))))
  have hsgen : TopologicallyGenerates (G := S.inverseLimit) (↑s : Set S.inverseLimit) := by
    simpa [s, Finset.coe_image] using hggen
  exact topologicalRank_le_of_topologicallyGeneratedByAtMost (G := S.inverseLimit)
    ⟨s, hs_card, hsgen⟩


end ProCGroups.FiniteGeneration
